<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Manual de R</title>
  <meta name="description" content="A book example for a Chapman &amp; Hall book.">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="Manual de R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book example for a Chapman &amp; Hall book." />
  <meta name="github-repo" content="yihui/bookdown-crc" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Manual de R" />
  
  <meta name="twitter:description" content="A book example for a Chapman &amp; Hall book." />
  



<meta name="date" content="2017-08-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="distribuciones-continuas.html">
<link rel="next" href="estudiando-la-normalidad.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="css\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Manual de R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> install the packages needed by this book; you fill out c(), e.g. c(‘ggplot2’, ‘dplyr’)</a></li>
<li class="chapter" data-level="" data-path="sobre-los-autores.html"><a href="sobre-los-autores.html"><i class="fa fa-check"></i>Sobre los autores</a></li>
<li class="chapter" data-level="2" data-path="introduccion.html"><a href="introduccion.html"><i class="fa fa-check"></i><b>2</b> Introducción </a></li>
<li class="chapter" data-level="3" data-path="tipos-de-objetos.html"><a href="tipos-de-objetos.html"><i class="fa fa-check"></i><b>3</b> Tipos de objetos  </a></li>
<li class="chapter" data-level="4" data-path="guia-de-estilo.html"><a href="guia-de-estilo.html"><i class="fa fa-check"></i><b>4</b> Guía de estilo  </a></li>
<li class="chapter" data-level="5" data-path="funciones-basicas-de.html"><a href="funciones-basicas-de.html"><i class="fa fa-check"></i><b>5</b> Funciones básicas de  </a></li>
<li class="chapter" data-level="6" data-path="instrucciones-de-control.html"><a href="instrucciones-de-control.html"><i class="fa fa-check"></i><b>6</b> Instrucciones de control </a></li>
<li class="chapter" data-level="7" data-path="creacion-de-funciones-en.html"><a href="creacion-de-funciones-en.html"><i class="fa fa-check"></i><b>7</b> Creación de funciones en  </a></li>
<li class="chapter" data-level="8" data-path="lectura-de-bases-de-datos.html"><a href="lectura-de-bases-de-datos.html"><i class="fa fa-check"></i><b>8</b> Lectura de bases de datos  </a></li>
<li class="chapter" data-level="9" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html"><i class="fa fa-check"></i><b>9</b> Tablas de frecuencia  </a></li>
<li class="chapter" data-level="10" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html"><i class="fa fa-check"></i><b>10</b> Medidas de tendencia central </a></li>
<li class="chapter" data-level="11" data-path="medidas-de-variabilidad.html"><a href="medidas-de-variabilidad.html"><i class="fa fa-check"></i><b>11</b> Medidas de variabilidad </a></li>
<li class="chapter" data-level="12" data-path="medidas-de-posicion.html"><a href="medidas-de-posicion.html"><i class="fa fa-check"></i><b>12</b> Medidas de posición </a></li>
<li class="chapter" data-level="13" data-path="medidas-de-correlacion.html"><a href="medidas-de-correlacion.html"><i class="fa fa-check"></i><b>13</b> Medidas de correlación </a></li>
<li class="chapter" data-level="14" data-path="distribuciones-discretas.html"><a href="distribuciones-discretas.html"><i class="fa fa-check"></i><b>14</b> Distribuciones discretas </a></li>
<li class="chapter" data-level="15" data-path="distribuciones-continuas.html"><a href="distribuciones-continuas.html"><i class="fa fa-check"></i><b>15</b> Distribuciones continuas </a></li>
<li class="chapter" data-level="16" data-path="verosimilitud.html"><a href="verosimilitud.html"><i class="fa fa-check"></i><b>16</b> Verosimilitud </a><ul>
<li class="chapter" data-level="16.1" data-path="verosimilitud.html"><a href="verosimilitud.html#funcion-de-verosimilitud"><i class="fa fa-check"></i><b>16.1</b> Función de verosimilitud</a></li>
<li class="chapter" data-level="16.2" data-path="verosimilitud.html"><a href="verosimilitud.html#funcion-de-log-verosimilitud"><i class="fa fa-check"></i><b>16.2</b> Función de log-verosimilitud</a></li>
<li class="chapter" data-level="16.3" data-path="verosimilitud.html"><a href="verosimilitud.html#metodo-de-maxima-verosimilitud-para-estimar-parametros"><i class="fa fa-check"></i><b>16.3</b> Método de máxima verosimilitud para estimar parámetros</a><ul>
<li class="chapter" data-level="" data-path="verosimilitud.html"><a href="verosimilitud.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="verosimilitud.html"><a href="verosimilitud.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="verosimilitud.html"><a href="verosimilitud.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="verosimilitud.html"><a href="verosimilitud.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="verosimilitud.html"><a href="verosimilitud.html#metodo-de-maxima-verosimilitud-para-estimar-parametros-en-modelos-de-regresion"><i class="fa fa-check"></i><b>16.4</b> Método de máxima verosimilitud para estimar parámetros en modelos de regresión</a><ul>
<li class="chapter" data-level="" data-path="verosimilitud.html"><a href="verosimilitud.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="verosimilitud.html"><a href="verosimilitud.html#ejercicios"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="estudiando-la-normalidad.html"><a href="estudiando-la-normalidad.html"><i class="fa fa-check"></i><b>17</b> Estudiando la normalidad </a></li>
<li class="chapter" data-level="18" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html"><i class="fa fa-check"></i><b>18</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="19" data-path="prueba-de-hipotesis-.html"><a href="prueba-de-hipotesis-.html"><i class="fa fa-check"></i><b>19</b> Prueba de hipótesis. </a></li>
<li class="chapter" data-level="20" data-path="aproximacion-de-integrales.html"><a href="aproximacion-de-integrales.html"><i class="fa fa-check"></i><b>20</b> Aproximación de integrales </a></li>
<li class="chapter" data-level="21" data-path="generate-a-bibtex-database-automatically-for-some-r-packages.html"><a href="generate-a-bibtex-database-automatically-for-some-r-packages.html"><i class="fa fa-check"></i><b>21</b> generate a BibTeX database automatically for some R packages</a></li>
<li class="chapter" data-level="22" data-path="curiosidades.html"><a href="curiosidades.html"><i class="fa fa-check"></i><b>22</b> Curiosidades </a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Manual de R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="verosimilitud" class="section level1">
<h1><span class="header-section-number">Chapter 16</span> Verosimilitud </h1>
<p>En este capítulo se mostrará como usar  para obtener la función de log-verosimilitud y estimadores por el método de máxima verosimilitud.</p>
<div id="funcion-de-verosimilitud" class="section level2">
<h2><span class="header-section-number">16.1</span> Función de verosimilitud</h2>
<p>La función de verosimilitud para un vector de parámetros <span class="math inline">\(\boldsymbol{\Theta}\)</span> dada una muestra aleatoria <span class="math inline">\(\boldsymbol{x}\)</span> con una distribución asumida se define como:</p>
<span class="math display" id="eq:lik">\[\begin{equation}
L(\boldsymbol{\Theta} | \boldsymbol{x}) = \prod_{i=1}^{n}  f(x_i | \boldsymbol{\Theta}),
\tag{16.1}
\end{equation}\]</span>
<p>donde <span class="math inline">\(x_i\)</span> representa uno de los elementos de la muestra aleatoria y <span class="math inline">\(f\)</span> es la función de masa/densidad de la distribución de la cual se obtuvo <span class="math inline">\(\boldsymbol{x}\)</span>.</p>
</div>
<div id="funcion-de-log-verosimilitud" class="section level2">
<h2><span class="header-section-number">16.2</span> Función de log-verosimilitud</h2>
<p>La función de log-verosimilitud <span class="math inline">\(l\)</span> se define como el logaritmo de la función de verosimilitud <span class="math inline">\(L\)</span>, es decir</p>
<span class="math display" id="eq:loglik">\[\begin{equation}
l(\boldsymbol{\Theta} | \boldsymbol{x}) = \log L(\boldsymbol{\Theta} | \boldsymbol{x}) = \sum_{i=1}^{n} \log f(x_i | \boldsymbol{\Theta})
\tag{16.2}
\end{equation}\]</span>
</div>
<div id="metodo-de-maxima-verosimilitud-para-estimar-parametros" class="section level2">
<h2><span class="header-section-number">16.3</span> Método de máxima verosimilitud para estimar parámetros</h2>
<p>El método de máxima verosimilitud se usa para estimar los parámetros de una distribución. El objetivo de este método es encontrar los valores de <span class="math inline">\(\boldsymbol{\Theta}\)</span> que maximizan <span class="math inline">\(L\)</span> o <span class="math inline">\(l\)</span> y valores encontrados se representan por <span class="math inline">\(\hat{\boldsymbol{\Theta}}\)</span>.</p>
<div id="ejemplo" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que se tiene el vector <code>rta</code> que corresponde a una muestra aleatoria de una distribución binomial con parámetro <code>size=5</code> conocido.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rta &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>,
         <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>)</code></pre></div>
<ol style="list-style-type: decimal">
<li>Calcular el valor de log-verosimilitud <span class="math inline">\(l\)</span> si asumimos que <span class="math inline">\(p=0.30\)</span> en la distribución binomial.</li>
</ol>
<p>Para obtener el valor de <span class="math inline">\(l\)</span> en el punto <span class="math inline">\(p=0.30\)</span> se aplica la definición dada en la expresión <a href="verosimilitud.html#eq:loglik">(16.2)</a>. Como el problema trata de una binomial se usa entonces la función de masa <code>dbinom</code> evaluada en la muestra <code>rta</code>, el parámetro <code>size</code> como es conocido se reemplaza por el valor de cinco y en el parámetro <code>prob</code> se cambia por 0.3. Como interesa la función de log-verosimilitud se debe incluir <code>log=TRUE</code>. A continuación el código necesario.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dt">x=</span>rta, <span class="dt">size=</span><span class="dv">5</span>, <span class="dt">prob=</span><span class="fl">0.3</span>, <span class="dt">log=</span><span class="ot">TRUE</span>))</code></pre></div>
<pre><code>## [1] -24.55231</code></pre>
<p>Por lo tanto <span class="math inline">\(l(\theta)= -24.55\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Construir una función llamada <code>ll</code> a la cual le ingrese uno o varios valores del parámetro <span class="math inline">\(p\)</span> de la binomial, la función debe entregar el valor de log-verosimilitud en cada uno de los <span class="math inline">\(p\)</span> ingresados.</li>
</ol>
<p>La función solicitada tiene un cuerpo igual al usado en el numeral anterior. Para asegurar que la función construída pueda recibir un vector de valores de <span class="math inline">\(p\)</span> se vectoriza la función con <code>Vectorize</code>, abajo el código usado.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ll &lt;-<span class="st"> </span>function(prob) <span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dt">x=</span>rta, <span class="dt">size=</span><span class="dv">5</span>, <span class="dt">prob=</span>prob, <span class="dt">log=</span>T))
ll &lt;-<span class="st"> </span><span class="kw">Vectorize</span>(ll)  <span class="co"># Para vectorizar la función</span></code></pre></div>
<p>Vamos a probar la función en <span class="math inline">\(p=0.15\)</span> y <span class="math inline">\(p=0.80\)</span> para saber si la función <code>ll</code> está vectorizada.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ll</span>(<span class="dt">prob=</span><span class="fl">0.15</span>)  <span class="co"># Individual para p=0.15</span></code></pre></div>
<pre><code>## [1] -25.54468</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ll</span>(<span class="dt">prob=</span><span class="fl">0.80</span>)  <span class="co"># Individual para p=0.80</span></code></pre></div>
<pre><code>## [1] -98.45598</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ll</span>(<span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.15</span>, <span class="fl">0.80</span>))  <span class="co"># Evaluada en un vector </span></code></pre></div>
<pre><code>## [1] -25.54468 -98.45598</code></pre>

<div class="rmdwarning">
La mayoría de las funciones en  creadas por los usuarios quedan vectorizadas otras no. La función <code>ll</code> no estaba vectorizada y por esa razón se necesitó usa <code>Vectorize</code>. No abuse de la función <code>Vectorize</code>, sólo úsela cuando sea necesario.
</div>
<p></p>
<ol start="3" style="list-style-type: decimal">
<li>Dibujar la curva log-verosimilitud <span class="math inline">\(l\)</span>.</li>
</ol>
<p>En la Figura <a href="verosimilitud.html#fig:loglik1">16.1</a> se presenta la curva solicitada, para su construcción se usa el siguiente código.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">curve</span>(ll, <span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">col=</span><span class="st">&#39;dodgerblue3&#39;</span>,
      <span class="dt">xlab=</span><span class="st">&#39;Probabilidad de éxito&#39;</span>,
      <span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&quot;l(&quot;</span>, theta, <span class="st">&quot;)&quot;</span>)))</code></pre></div>
<div class="figure"><span id="fig:loglik1"></span>
<img src="Manual_de_R_files/figure-html/loglik1-1.png" alt="Función de log-verosimilitud para el ejemplo sobre binomial." width="384" />
<p class="caption">
FIGURE 16.1: Función de log-verosimilitud para el ejemplo sobre binomial.
</p>
</div>
<ol start="4" style="list-style-type: decimal">
<li>Observando la Figura <a href="verosimilitud.html#fig:loglik1">16.1</a>, ¿cuál esl el valor de <span class="math inline">\(p\)</span> que maximiza la función de log-verosimilitud?</li>
</ol>
<p>Al observar la Figura <a href="verosimilitud.html#fig:loglik1">16.1</a> se nota que el valor de <span class="math inline">\(p\)</span> que maximiza la función log-verosimilitud está muy cerca de 0.2.</p>
<ol start="5" style="list-style-type: decimal">
<li>¿Cuál es el valor exacto de <span class="math inline">\(p\)</span> que maximiza la función log-verosimilitud?</li>
</ol>
<p>En  existe la función <code>optimize</code> que sirve para encontrar el valor que <strong>minimiza</strong> una función uniparamétrica en un intervalo dado, sin embargo, aquí interesa es maximimizar la función de log-verosimilitud, por esa razón se construye la función <code>minusll</code> que es el negativo de la función <code>ll</code> para así poder usar <code>optimize</code>. A continuación el código usado. </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minusll &lt;-<span class="st"> </span>function(x) -<span class="kw">ll</span>(x)

<span class="kw">optimize</span>(<span class="dt">f=</span>minusll, <span class="dt">interval=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</code></pre></div>
<pre><code>## $minimum
## [1] 0.229993
## 
## $objective
## [1] 23.3246</code></pre>
<p>Del resultado anterior se observa que cuando <span class="math inline">\(p=0.23\)</span> el valor máximo de log-verosimilitud es 23.32.</p>
</div>
<div id="ejemplo-1" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que la estatura de una población se puede asumir como una normal <span class="math inline">\(N(170, 25)\)</span>. Suponga también que se genera una muestra aleatoria de 50 observaciones de la población con el objetivo de recuperar los valores de la media y varianza poblacionales a partir de la muestra aleatoria.</p>
<p>La muestra se va a generar con la función <code>rnorm</code> pero antes se fijará una semilla con la intención de que el lector pueda replicar el ejemplo y obtener la misma muestra aleatoria aquí generada, el código para hacerlo es el siguiente.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1235</span>)  <span class="co"># La semilla es 1235</span>
y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n=</span><span class="dv">50</span>, <span class="dt">mean=</span><span class="dv">170</span>, <span class="dt">sd=</span><span class="dv">5</span>)</code></pre></div>
<ol style="list-style-type: decimal">
<li>construya la función de log-verosimilitud para los parámetros de la normal dada la muestra aleatoria <code>y</code>.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ll &lt;-<span class="st"> </span>function(param) {
  media &lt;-<span class="st"> </span>param[<span class="dv">1</span>]  <span class="co"># param es el vector de parámetros</span>
  desvi &lt;-<span class="st"> </span>param[<span class="dv">2</span>] 
  <span class="kw">sum</span>(<span class="kw">dnorm</span>(<span class="dt">x=</span>y, <span class="dt">mean=</span>media, <span class="dt">sd=</span>desvi, <span class="dt">log=</span><span class="ot">TRUE</span>))
}</code></pre></div>

<div class="rmdwarning">
Siempre que el interés sea encontrar los valores que maximizan una función de log-verosimilitud, los parámetros de la distribución <strong>deben</strong> ingresar a la función <code>ll</code> como un vector. Esto se debe hacer para poder usar las funciones de búsqueda <code>optim</code> y <code>nlminb</code>.
</div>
<p></p>
<ol start="2" style="list-style-type: decimal">
<li>Dibuje la función de log-verosimilitud.</li>
</ol>
<p>En la Figura <a href="verosimilitud.html#fig:loglik2">16.2</a> se muestra el gráfico de niveles para la superficie de log-verosimilitud. De esta figura se nota claramente que los valores que maximizan la superficie están alrededor de <span class="math inline">\(\mu=170\)</span> y <span class="math inline">\(\sigma=5\)</span>. Para ver el código usado en la creación de la Figura <a href="verosimilitud.html#fig:loglik2">16.2</a> se recomienda consultar la sección sobre <code>contour</code> en <span class="citation">Hernández (<a href="#ref-hernandez_correa">2018</a>)</span>.</p>
<div class="figure"><span id="fig:loglik2"></span>
<img src="Manual_de_R_files/figure-html/loglik2-1.png" alt="Gráfico de niveles para la función de log-verosimilitud para el ejemplo sobre normal." width="864" />
<p class="caption">
FIGURE 16.2: Gráfico de niveles para la función de log-verosimilitud para el ejemplo sobre normal.
</p>
</div>
<ol start="3" style="list-style-type: decimal">
<li>Obtenga los valores de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> que maximizan la función de log-verosimilitud.</li>
</ol>
<p>Para obtener los valores solicitados vamos a usar la función <code>nlminb</code> que es un optimizador. A la función <code>nlminb</code> se le debe indicar por medio del parámetro <code>objective</code> la función que queremos optimizar (minimizar); el parámetro <code>start</code> es un vector con los valores iniciales para comenzar la búsqueda de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>; los parámetros <code>lower</code> y <code>upper</code> sirven para delimitar el espacio de búsqueda. A continuación se muestra el código usado para obtener los valores que minimizan a <code>minusll</code>, es decir, los valores que maximizan la función de log-verosimilitud. </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minusll &lt;-<span class="st"> </span>function(x) -<span class="kw">ll</span>(x)
<span class="kw">nlminb</span>(<span class="dt">objective=</span>minusll, <span class="dt">start=</span><span class="kw">c</span>(<span class="dv">163</span>, <span class="fl">3.4</span>),
       <span class="dt">lower=</span><span class="kw">c</span>(<span class="dv">160</span>, <span class="dv">3</span>), <span class="dt">upper=</span><span class="kw">c</span>(<span class="dv">180</span>, <span class="dv">7</span>))</code></pre></div>
<pre><code>## $par
## [1] 170.338374   5.423529
## 
## $objective
## [1] 155.4842
## 
## $convergence
## [1] 0
## 
## $iterations
## [1] 13
## 
## $evaluations
## function gradient 
##       16       35 
## 
## $message
## [1] &quot;relative convergence (4)&quot;</code></pre>
<p>De la salida anterior podemos observar que los valores óptimos de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> son 170.338 y 5.424 respectivamente, esto coincide con lo observado en la <a href="verosimilitud.html#fig:loglik2">16.2</a> y con los valores reales de simulación de la muestra. Esto indica que el procedimiento de estimación de parámetros por máxima verosimilitud entrega valores insesgados de los parámetros a estimar.</p>
<p>Un resultado interesante de la salida anterior es que se reporta el valor mínimo que alcanza la función <code>minusll</code>, este valor fue de 155.5, por lo tanto, se puede afirmar que el valor máximo de log-verosimilitud es -155.5.</p>
<p>Otros resultados importantes de la salida anterior son el valor de <code>convergence=0</code> que indica que la búsqueda fue exitosa; <code>iterations=13</code> indica que se realizaron 13 pasos desde el punto inicial <code>start</code> hasta las coordenadas de optimización.</p>

<div class="rmdnote">
En  se tienen dos funciones básicas para optimizar funciones, es decir, para encontrar los valores que minimizan una función dada. Esas dos funciones son <code>nliminb</code> y <code>optim</code>. Para optimizar en una sola dimensión se usa la función <code>optimize</code>.
</div>
<p></p>
<ol start="4" style="list-style-type: decimal">
<li>¿Hay alguna función para obtener directamente el valor que maximiza la función log-verosimilitud?</li>
</ol>
<p>La respuesta es si. Si la distribución estudiada es una de las distribuciones básicas se puede usar la función <code>fitdistr</code> del paquete básico <strong>MASS</strong>. La función <code>fitdistr</code> requiere de los datos que se ingresan por medio del parámetro <code>x</code>, y de la distribución de los datos que se ingrea por medio del parámetro <code>densfun</code>. La función <code>fitdistr</code> admite 15 distribuciones diferentes para hacer la búsqueda de los parámetros que caracterizan una distribución, se sugiere consultar la ayuda de la función <code>fitdistr</code> escribiendo en la consola <code>help(fitdistr)</code>. A continuación el código usado. </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(MASS) <span class="co"># El paquete ya está instalado, solo se debe cargar</span>
res &lt;-<span class="st"> </span><span class="kw">fitdistr</span>(<span class="dt">x=</span>y, <span class="dt">densfun=</span><span class="st">&#39;normal&#39;</span>)
res</code></pre></div>
<pre><code>##       mean           sd     
##   170.3383794     5.4235271 
##  (  0.7670026) (  0.5423527)</code></pre>
<p>El objeto <code>res</code> contiene los resultados de usar <code>fitdistr</code>. En la primer línea están los valores de los parámetros que maximizan la función de log-verosimilitud, en la parte de abajo, dentro de paréntesis, están los errores estándar o desviaciones de éstos estimadores.</p>
<p>Al objeto <code>res</code> es de la clase <em>fitdistr</em> y por lo tanto se le puede aplicar la función genérica <code>logLik</code> para obtener el valor de la log-verosimilitud. Se sugiere consultar la ayuda de la función <code>logLik</code> escribiendo en la consola <code>help(logLik)</code>. A continuación el código para usar <code>logLik</code> sobre el objeto <code>res</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">logLik</span>(res)</code></pre></div>
<pre><code>## &#39;log Lik.&#39; -155.4842 (df=2)</code></pre>
<p>De esta última salida se observa que el valor coincide con el obtenido cuando se usó <code>nlminb</code>.</p>
</div>
<div id="ejemplo-2" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Generar <span class="math inline">\(n=100\)</span> observaciones de una gamma con parámetro de forma igual a 2 y parámetro de tasa igual a 0.5 y luego responder las preguntas.</p>
<p>Para generar la muestra aleatoria <code>ma</code> solicitada se fijó la semilla con el objetivo de que el lector pueda obtener los mismos resultados de este ejemplo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">100</span>
<span class="kw">set.seed</span>(<span class="dv">12345</span>)
ma &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dt">n=</span>n, <span class="dt">shape=</span><span class="dv">2</span>, <span class="dt">rate=</span><span class="fl">0.5</span>)</code></pre></div>
<ol style="list-style-type: decimal">
<li>Asumiendo que la muestra aleatoria proviene de una normal (lo cual es incorrecto) estime los parámetros de la distribución</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit1 &lt;-<span class="st"> </span><span class="kw">fitdistr</span>(<span class="dt">x=</span>ma, <span class="dt">densfun=</span><span class="st">&#39;normal&#39;</span>)
fit1</code></pre></div>
<pre><code>##      mean         sd    
##   4.3082767   2.8084910 
##  (0.2808491) (0.1985903)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Asumiendo que la muestra aleatoria proviene de una gamma estime los parámetros de la distribución.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit2 &lt;-<span class="st"> </span><span class="kw">fitdistr</span>(<span class="dt">x=</span>ma, <span class="dt">densfun=</span><span class="st">&#39;gamma&#39;</span>)
fit2</code></pre></div>
<pre><code>##      shape         rate   
##   2.23978235   0.51987909 
##  (0.29620136) (0.07702892)</code></pre>
<p>En la salida anterior están los valores estimados de los parámetros de la distribución por el método de máxima verosimilitud, observe la cercanía de éstos con los verdaderos valores de 2 y 0.5 para forma y tasa respectivamente.</p>
<ol start="3" style="list-style-type: decimal">
<li>Dibuje dos qqplot, uno asumiendo distribución gamma y el otro distribución gamma. ¿Cuál distribución se ajusta mejor a los datos simulados?</li>
</ol>
<p>Para dibujar el qqplot se usa la función genérica <code>qqplot</code>, recomendamos consultar <span class="citation">Hernández (<a href="#ref-hernandez_correa">2018</a>)</span> para los detalles de cómo usar esta función. Al usar <code>qqplot</code> para obtener el qqplot normal y gamma es necesario indicar los valores <span class="math inline">\(\hat{\boldsymbol{\Theta}}\)</span> obtenidos en el numeral anterior, por eso es que en el código mostrado a continuación aparece <code>mean=4.3083, sd=2.8085</code> en el qqplot normal y <code>shape=2.23978, rate=0.51988</code> en el qqplot gamma.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))

<span class="kw">qqplot</span>(<span class="dt">y=</span>ma, <span class="dt">pch=</span><span class="dv">19</span>,
       <span class="dt">x=</span><span class="kw">qnorm</span>(<span class="kw">ppoints</span>(n), <span class="dt">mean=</span><span class="fl">4.3083</span>, <span class="dt">sd=</span><span class="fl">2.8085</span>),
       <span class="dt">main=</span><span class="st">&#39;Normal Q-Q Plot&#39;</span>,
       <span class="dt">xlab=</span><span class="st">&#39;Theoretical Quantiles&#39;</span>,
       <span class="dt">ylab=</span><span class="st">&#39;Sample Quantiles&#39;</span>)

<span class="kw">qqplot</span>(<span class="dt">y=</span>ma, <span class="dt">pch=</span><span class="dv">19</span>,
       <span class="dt">x=</span><span class="kw">qgamma</span>(<span class="kw">ppoints</span>(n), <span class="dt">shape=</span><span class="fl">2.23978</span>, <span class="dt">rate=</span><span class="fl">0.51988</span>),
       <span class="dt">main=</span><span class="st">&#39;Gamma Q-Q Plot&#39;</span>,
       <span class="dt">xlab=</span><span class="st">&#39;Theoretical Quantiles&#39;</span>,
       <span class="dt">ylab=</span><span class="st">&#39;Sample Quantiles&#39;</span>)</code></pre></div>
<div class="figure"><span id="fig:normgamma"></span>
<img src="Manual_de_R_files/figure-html/normgamma-1.png" alt="Gráfico cuantil cuantil normal y gamma para la muestra simulada." width="864" />
<p class="caption">
FIGURE 16.3: Gráfico cuantil cuantil normal y gamma para la muestra simulada.
</p>
</div>
<p>En la Figura <a href="verosimilitud.html#fig:normgamma">16.3</a> se muestran los qqplot solicitados. Se observa claramente que al asumir normalidad (lo cual es incorrecto), los puntos del qqplot no están alineados, mientras que al asumir distribución gamma (lo cual es correcto), los puntos si están alineados. De esta figura se concluye que la muestra <code>ma</code> puede provenir de una <span class="math inline">\(Gamma(2.23978, 0.51988)\)</span>.</p>

<div class="rmdtip">
Para obtener el gráfico cuantil cuantil bajo normalidad se puede usar directamente la función <code>qqnorm</code>, consultar <span class="citation">Hernández (<a href="#ref-hernandez_correa">2018</a>)</span> para mayores detalles.
</div>
<p></p>

<div class="rmdwarning">
En este ejemplo se eligió la mejor distribución entre dos candidatas usando una herramienta gráfica, lo que se recomienda usar algún método menos subjetivo (cuantitativo) para tomar decisiones.
</div>
<p></p>
<ol start="4" style="list-style-type: decimal">
<li>Para comparar modelos se puede utilizar el <em>Akaike information criterion</em> (<span class="math inline">\(AIC\)</span>) propuesto por <span class="citation">Akaike (<a href="#ref-Akaike74">1974</a>)</span> que sirve para medir la calidad relativa de los modelos estadísticos, la expresión para calcular el indicador es <span class="math inline">\(AIC=-2 \, \hat{l}+2 \, df\)</span>, donde <span class="math inline">\(\hat{l}\)</span> corresponde al valor de <span class="math inline">\(\log\)</span>-verosimilitud y <span class="math inline">\(df\)</span> corresponde al número de parámetros estimados del modelo. Siempre el modelo elegido es aquel modelo con el menor valor de <span class="math inline">\(AIC\)</span>. Calcular el <span class="math inline">\(AIC\)</span> para los modelos asumidos normal y gamma.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">-<span class="dv">2</span> *<span class="st"> </span><span class="kw">logLik</span>(fit1) +<span class="st"> </span><span class="dv">2</span> *<span class="st"> </span><span class="dv">2</span>  <span class="co"># AIC para modelo normal</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; 494.3172 (df=2)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">-<span class="dv">2</span> *<span class="st"> </span><span class="kw">logLik</span>(fit2) +<span class="st"> </span><span class="dv">2</span> *<span class="st"> </span><span class="dv">2</span>  <span class="co"># AIC para modelo gamma</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; 466.0479 (df=2)</code></pre>
<p>De los resultados anteriores se concluye que entre los dos modelos, el mejor es el gamma porque su <span class="math inline">\(AIC=466\)</span> es el menor de toos los <span class="math inline">\(AIC\)</span>.</p>

<div class="rmdnote">
Modelos anidados pueden ser comparados por medio del <em>global deviance</em> (<span class="math inline">\(GD\)</span>) dado por <span class="math inline">\(GD=-2 \, \hat{l}\)</span> y modelos no anidados por medio del <em>Generalized Akaike information criterion</em> (<span class="math inline">\(GAIC\)</span>) propuesto por <span class="citation">Akaike (<a href="#ref-Akaike83">1983</a>)</span> y dado por <span class="math inline">\(GAIC=-2 \, \hat{l} + \# \, df\)</span> siendo <span class="math inline">\(\#\)</span> el valor de penalidad por cada parámetro adicional en el modelo; cuando <span class="math inline">\(\# = 2\)</span>, el <span class="math inline">\(GAIC\)</span> coincide con el <span class="math inline">\(AIC\)</span> y el <em>Schwarz Bayesian criterion</em> (<span class="math inline">\(SBC\)</span>) propuesto por <span class="citation">Schwarz (<a href="#ref-Schwarz">1978</a>)</span> se dá cuando el valor de penalidad es <span class="math inline">\(\# = \log(n)\)</span> donde <span class="math inline">\(n\)</span> es el número de observaciones del modelo; siempre el modelo elegido es aquel modelo con el menor valor de cualquiera de los criterios de información anteriores.
</div>
<p></p>
</div>
<div id="ejemplo-3" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>¿Será posible explorar entre muchas distribuciones estadísticas aquella que mejor explica una variable de interés?</p>
<p>La respuesta es si, se puede usar la función <code>fitDist</code> del paquete <strong>gamlss</strong> . Esta función tiene la siguiente estructura:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fitDist</span>(y, <span class="dt">k =</span> <span class="dv">2</span>, 
      <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;realAll&quot;</span>, <span class="st">&quot;realline&quot;</span>, <span class="st">&quot;realplus&quot;</span>,
               <span class="st">&quot;real0to1&quot;</span>, <span class="st">&quot;counts&quot;</span>, <span class="st">&quot;binom&quot;</span>))</code></pre></div>
<p>El parámetro <code>y</code> sirve para ingresar el vector con la información; <code>k=2</code> es la penalización por cada parámetro estimado para calcular el <span class="math inline">\(GAIC\)</span>, por defecto es 2; y el parámetro <code>type</code> sirve para indicar el tipo de distribución, los posibles valores son:</p>
<ul>
<li><code>realAll</code>: para hacer la búsqueda en todas las distribuciones disponibles en <strong>gamlss</strong>.</li>
<li><code>realline</code>: para variables en <span class="math inline">\(\Re\)</span>.</li>
<li><code>realplus</code>: para variables en <span class="math inline">\(\Re^+\)</span>.</li>
<li><code>real0to1</code>: para variables en el intervalo <span class="math inline">\((0, 1)\)</span>.</li>
<li><code>counts</code>: para variables de conteo.</li>
<li><code>binom</code>: para variables de tipo binomial.</li>
</ul>
<ol style="list-style-type: decimal">
<li>Usar la función <code>fitDist</code> para elegir la distribución que mejor se ajusta a los datos simulados en el ejemplo anterior, usar una penalizacion de <span class="math inline">\(k=2\)</span> para calcular el <span class="math inline">\(AIC\)</span>.</li>
</ol>
<p>Se usa la función <code>fitDist</code> con <code>type='realplus'</code> porque se sabe que la muestra aleatoria tiene valores sólo en <span class="math inline">\(\Re^+\)</span>, los resultados de almacenan en el objeto <code>modelos</code>. Para obtener la lista de los mejores modelos con su respectivo <span class="math inline">\(BAIC\)</span> se escribe en la consola <code>modelos$fits</code>. Abajo el código usado.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(gamlss)
modelos &lt;-<span class="st"> </span><span class="kw">fitDist</span>(<span class="dt">y=</span>ma, <span class="dt">type=</span><span class="st">&#39;realplus&#39;</span>, <span class="dt">k=</span><span class="dv">2</span>)
modelos$fits</code></pre></div>
<pre><code>##       GA     WEI3       GG      GIG    BCCGo    BCPEo     BCTo   exGAUS 
## 466.0479 466.7706 467.9592 468.0346 468.3529 469.4485 470.3529 471.2275 
##    LOGNO       IG      EXP  PARETO2   IGAMMA 
## 474.5855 483.9227 494.1076 496.1078 504.1710</code></pre>
<p>De la lista anterior se observa que la función gamma está en el primer lugar con un <span class="math inline">\(BAIC=466\)</span>, valor que coincide con el <span class="math inline">\(AIC\)</span> obtenido en el ejercicio anterior. Esto significa que como la gamma tiene el menor <span class="math inline">\(BAIC\)</span>, es la distribución que mejor se ajusta a los datos de la muestra, esto coincide con la realidad, ya que la muestra fue generada de una distribución gamma.</p>
<p>¿Por queé <span class="math inline">\(AIC\)</span> y <span class="math inline">\(BAIC\)</span> coinciden en este ejemplo?</p>
<ol start="2" style="list-style-type: decimal">
<li>¿Cuáles son los valores estimados de los parámetros para la distribución gamma identificada en el paso anterior?</li>
</ol>
<p>En <strong>gamlss</strong> los parámetros de las distribuciones se nombran de una forma especial, el parámetro de posición se denomina <span class="math inline">\(\mu\)</span>, el de dispersión se denomina <span class="math inline">\(\sigma\)</span> y los de simetría y curtosis con <span class="math inline">\(\nu\)</span> y <span class="math inline">\(\tau\)</span>. La distribución gamma sólo tiene 2 parámetros y para obtener sus valores estimados se usa el siguiente código.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelos$mu</code></pre></div>
<pre><code>## [1] 4.30828</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelos$sigma</code></pre></div>
<pre><code>## [1] 0.668186</code></pre>
<p>Si comparamos los anteriores resultados, <span class="math inline">\(\hat{\mu}= 4.308\)</span> y <span class="math inline">\(\hat{\sigma}=0.6682\)</span>, con los encontrados al usar la función <code>fitdist</code>, <span class="math inline">\(\widehat{shape}=2.23978\)</span> y <span class="math inline">\(\widehat{rate}=0.51988\)</span>, vemos que no coinciden, esto se debe a que la parametrización de la gamma usada por <strong>gamlss</strong> es diferente a la parametrización usada por la base de . Lo anterior no es motivo de preocupación, lo que se recomienda es que el usuario elija una de las parametrizaciones y trabaje con ella, no debe mezclarlas.</p>
<ol start="3" style="list-style-type: decimal">
<li>Dibujar el histograma para la muestra aleatoria y agregar la densidad de la distribución gamma identificada como la distribución que mejor explica el comportamiento de la variable.</li>
</ol>
<p>Para hacer lo solicitado se usa la función <code>histDist</code> del paquete <strong>gamlss</strong>, sólo es necesario ingresar los datos y la familia o distribución de la densidad requerida. Abajo el código usado.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">histDist</span>(<span class="dt">y=</span>ma, <span class="dt">family=</span>GA, <span class="dt">main=</span><span class="st">&#39;&#39;</span>, <span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Densidad&#39;</span>,
         <span class="dt">line.col=</span><span class="st">&#39;blue&#39;</span>, <span class="dt">line.wd=</span><span class="dv">4</span>)</code></pre></div>
<div class="figure"><span id="fig:histDist1"></span>
<img src="Manual_de_R_files/figure-html/histDist1-1.png" alt="Histograma para la muestra simulada con la densidad de una Gamma(mu=4.308, sigma=0.6682)." width="864" />
<p class="caption">
FIGURE 16.4: Histograma para la muestra simulada con la densidad de una Gamma(mu=4.308, sigma=0.6682).
</p>
</div>
<pre><code>## 
## Family:  c(&quot;GA&quot;, &quot;Gamma&quot;) 
## Fitting method: &quot;nlminb&quot; 
## 
## Call:  gamlssML(formula = ma, family = &quot;GA&quot;, data = sys.parent()) 
## 
## Mu Coefficients:
## [1]  1.461
## Sigma Coefficients:
## [1]  -0.4032
## 
##  Degrees of Freedom for the fit: 2 Residual Deg. of Freedom   98 
## Global Deviance:     462.048 
##             AIC:     466.048 
##             SBC:     471.258</code></pre>
<p>En la Figura <a href="verosimilitud.html#fig:histDist1">16.4</a> se presenta el histograma para muestra aleatoria y la densidad de la gamma que mejor explica estos datos. Se observa claramente que la curva de densidad azul acompaña el patrón de los datos.</p>
</div>
</div>
<div id="metodo-de-maxima-verosimilitud-para-estimar-parametros-en-modelos-de-regresion" class="section level2">
<h2><span class="header-section-number">16.4</span> Método de máxima verosimilitud para estimar parámetros en modelos de regresión</h2>
<p>En la sección anterior se estudió cómo estimar los parámetros de una distribución, en este capítulo se aprenderá a estimar los parámetros de un modelo de regresión general.</p>
<div id="ejemplo-4" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Considere el siguiente modelo de regresión:</p>
<span class="math display">\[\begin{align*}
y_i &amp;\sim N(\mu_i, \sigma^2), \\
\mu_i &amp;= -2 + 3 x_1, \\
\sigma &amp;= 5, \\
x_1 &amp;\sim U(-5, 6).
\end{align*}\]</span>
</div>
</div>
<div id="ejercicios" class="section level2 unnumbered">
<h2>EJERCICIOS</h2>
<ol style="list-style-type: decimal">
<li>Al inicio del Capítulo <a href="#central"><strong>??</strong></a> se presentó la base de datos sobre medidas del cuerpo, consulte la explicación sobre la base de datos y responda lo siguiente.</li>
</ol>
<ul>
<li>Si se asume que la <code>edad</code> tiene distribución normal, ¿cuáles son los estimadores de máxima verosimilitud para <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>?</li>
<li>Como el histograma para la edad muestra un sesgo a la derecha se podría pensar que la distribución gamma sería una buena candidata para explicar las edades observadas. Asumiendo una distribución gamma, ¿cuáles son los estimadores de máxima verosimilitud para los parámetros?</li>
<li>¿Cuál de los dos modelos es más apropiado para explicar la variable de interés? Calcule el <span class="math inline">\(AIC\)</span> para decidir.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>En la sección <a href="#crabs"><strong>??</strong></a> se presentó la base de datos sobre cangrejos hembra, consulte la explicación sobre la base de datos y responda lo siguiente.</li>
</ol>
<ul>
<li>Suponga que el número de satélites sobre cada hembra es una variable que se distribuye Poisson. Construya en  la función de log-verosimilitud <span class="math inline">\(l\)</span>, dibuje la función <span class="math inline">\(l\)</span> y encuentre el estimador de máxima verosimilitud de <span class="math inline">\(\lambda\)</span>.</li>
<li>Repita el ejercicio anterior asumiendo que el número de satélites se distribuye binomial negativo.</li>
<li>¿Cuál de los dos modelos es más apropiado para explicar la variable de interés? Calcule el <span class="math inline">\(AIC\)</span> para decidir.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Al inicio del Capítulo <a href="#varia"><strong>??</strong></a> se presentó la base de datos sobre apartamentos usados en Medellín, consulte la explicación sobre la base de datos y responda lo siguiente.</li>
</ol>
<ul>
<li>Dibuje una densidad para la variable área del apartamento.</li>
<li>Describa lo encontrado en esa densidad.</li>
<li>¿Qué distribuciones de 2 parámetros podrían explicar el comportamiento del área de los apartamentos? Mencione al menos 3.</li>
<li>Para cada una de las distribuciones anteriores dibuje un gráfico de contornos o calor para la función de log-verosimilitud y estime los parámetros de la distribución elegida.</li>
<li>¿Cuál de los dos modelos es más apropiado para explicar la variable de interés? Calcule el <span class="math inline">\(AIC\)</span> para decidir.</li>
</ul>

</div>
</div>
<h3> Curiosidades </h3>
<div id="refs" class="references">
<div id="ref-hernandez_correa">
<p>Hernández, J., F. &amp; Correa. 2018. <em>Gráficos Con R</em>. Primera. Medellín, Colombia: Universidad Nacional de Colombia. <a href="http://yihui.name/knitr/" class="uri">http://yihui.name/knitr/</a>.</p>
</div>
<div id="ref-Akaike74">
<p>Akaike, H. 1974. “A new look at the statistical model identification.” <em>IEEE Transactions on Automatic Control</em> 19 (6): 716–23.</p>
</div>
<div id="ref-Akaike83">
<p>Akaike, H. 1983. “Information measures and model selection.” <em>Bulletin of the International Statistical Institute</em> 50: 277–90.</p>
</div>
<div id="ref-Schwarz">
<p>Schwarz, G. 1978. “Estimating the dimension of a model.” <em>Annals of Statistics</em> 6 (2): 461–64.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="distribuciones-continuas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estudiando-la-normalidad.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/23_loglik.Rmd",
"text": "Edit"
},
"download": ["Manual_de_R.pdf", "Manual_de_R.epub"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
