<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>14 Estadística descriptiva con dplyr | Manual de R</title>
  <meta name="description" content="14 Estadística descriptiva con dplyr | Manual de R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="14 Estadística descriptiva con dplyr | Manual de R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/portada.png" />
  <meta property="og:description" content="14 Estadística descriptiva con dplyr | Manual de R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="github-repo" content="fhernanb/Manual-de-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="14 Estadística descriptiva con dplyr | Manual de R" />
  
  <meta name="twitter:description" content="14 Estadística descriptiva con dplyr | Manual de R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="twitter:image" content="/images/portada.png" />

<meta name="author" content="Freddy Hernández" />
<meta name="author" content="Olga Usuga" />


<meta name="date" content="2023-10-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correl.html"/>
<link rel="next" href="variables-aleatorias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Manual de R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#información-del-software-y-convenciones"><i class="fa fa-check"></i>Información del software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#agradecimientos"><i class="fa fa-check"></i>Agradecimientos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-los-autores.html"><a href="sobre-los-autores.html"><i class="fa fa-check"></i>Sobre los autores</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#orígenes"><i class="fa fa-check"></i><b>1.1</b> Orígenes</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#instalación"><i class="fa fa-check"></i><b>1.2</b> Instalación</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#apariencia-del-programa"><i class="fa fa-check"></i><b>1.3</b> Apariencia del programa</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="objetos.html"><a href="objetos.html"><i class="fa fa-check"></i><b>2</b> Tipos de objetos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="objetos.html"><a href="objetos.html#variables"><i class="fa fa-check"></i><b>2.1</b> Variables</a></li>
<li class="chapter" data-level="2.2" data-path="objetos.html"><a href="objetos.html#vectores"><i class="fa fa-check"></i><b>2.2</b> Vectores </a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-un-vector"><i class="fa fa-check"></i><b>2.2.1</b> ¿Cómo extraer elementos de un vector?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="objetos.html"><a href="objetos.html#matrices"><i class="fa fa-check"></i><b>2.3</b> Matrices</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-una-matriz"><i class="fa fa-check"></i><b>2.3.1</b> ¿Cómo extraer elementos de una matriz?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="objetos.html"><a href="objetos.html#arreglos"><i class="fa fa-check"></i><b>2.4</b> Arreglos </a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-un-arreglo"><i class="fa fa-check"></i><b>2.4.1</b> ¿Cómo extraer elementos de un arreglo?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="objetos.html"><a href="objetos.html#marco-de-datos"><i class="fa fa-check"></i><b>2.5</b> Marco de datos </a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-un-marco-de-datos"><i class="fa fa-check"></i><b>2.5.1</b> ¿Cómo extraer elementos de un marco de datos?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="2.5.2" data-path="objetos.html"><a href="objetos.html#cómo-extraer-subconjuntos-de-un-marco-de-datos"><i class="fa fa-check"></i><b>2.5.2</b> ¿Cómo extraer subconjuntos de un marco de datos? </a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplos"><i class="fa fa-check"></i>Ejemplos</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="objetos.html"><a href="objetos.html#listas"><i class="fa fa-check"></i><b>2.6</b> Listas </a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-una-lista"><i class="fa fa-check"></i><b>2.6.1</b> ¿Cómo extraer elementos de una lista?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplos-1"><i class="fa fa-check"></i>Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejercicios"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estilo.html"><a href="estilo.html"><i class="fa fa-check"></i><b>3</b> Guía de estilo</a>
<ul>
<li class="chapter" data-level="3.1" data-path="estilo.html"><a href="estilo.html#nombres-de-los-archivos"><i class="fa fa-check"></i><b>3.1</b> Nombres de los archivos</a></li>
<li class="chapter" data-level="3.2" data-path="estilo.html"><a href="estilo.html#nombres-de-los-objetos"><i class="fa fa-check"></i><b>3.2</b> Nombres de los objetos</a></li>
<li class="chapter" data-level="3.3" data-path="estilo.html"><a href="estilo.html#longitud-de-una-línea-de-código"><i class="fa fa-check"></i><b>3.3</b> Longitud de una línea de código</a></li>
<li class="chapter" data-level="3.4" data-path="estilo.html"><a href="estilo.html#espacios"><i class="fa fa-check"></i><b>3.4</b> Espacios</a></li>
<li class="chapter" data-level="3.5" data-path="estilo.html"><a href="estilo.html#asignación"><i class="fa fa-check"></i><b>3.5</b> Asignación</a></li>
<li class="chapter" data-level="3.6" data-path="estilo.html"><a href="estilo.html#punto-y-coma"><i class="fa fa-check"></i><b>3.6</b> Punto y coma</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html"><i class="fa fa-check"></i><b>4</b> Ingresando datos a R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html#usando-la-consola"><i class="fa fa-check"></i><b>4.1</b> Usando la consola</a></li>
<li class="chapter" data-level="4.2" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html#usando-ventana-emergente-con-svdialogs"><i class="fa fa-check"></i><b>4.2</b> Usando ventana emergente con <strong>svDialogs</strong></a></li>
<li class="chapter" data-level="4.3" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html#botones-para-responder"><i class="fa fa-check"></i><b>4.3</b> Botones para responder</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="funbas.html"><a href="funbas.html"><i class="fa fa-check"></i><b>5</b> Funciones básicas de R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="funbas.html"><a href="funbas.html#qué-es-una-función-de-r"><i class="fa fa-check"></i><b>5.1</b> ¿Qué es una función de R?</a></li>
<li class="chapter" data-level="5.2" data-path="funbas.html"><a href="funbas.html#asignación-en-r"><i class="fa fa-check"></i><b>5.2</b> Asignación en R</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="funbas.html"><a href="funbas.html#operadores"><i class="fa fa-check"></i><b>5.3</b> Operadores</a></li>
<li class="chapter" data-level="5.4" data-path="funbas.html"><a href="funbas.html#pruebas-lógicas"><i class="fa fa-check"></i><b>5.4</b> Pruebas lógicas</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="funbas.html"><a href="funbas.html#operadores-lógicos"><i class="fa fa-check"></i><b>5.5</b> Operadores lógicos</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="funbas.html"><a href="funbas.html#funciones-sobre-vectores"><i class="fa fa-check"></i><b>5.6</b> Funciones sobre vectores</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="funbas.html"><a href="funbas.html#funciones-matemáticas"><i class="fa fa-check"></i><b>5.7</b> Funciones matemáticas</a></li>
<li class="chapter" data-level="5.8" data-path="funbas.html"><a href="funbas.html#función-seq"><i class="fa fa-check"></i><b>5.8</b> Función <code>seq</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="funbas.html"><a href="funbas.html#función-rep"><i class="fa fa-check"></i><b>5.9</b> Función <code>rep</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="funbas.html"><a href="funbas.html#funciones-round-ceiling-floor-y-trunc"><i class="fa fa-check"></i><b>5.10</b> Funciones <code>round</code>, <code>ceiling</code>, <code>floor</code> y <code>trunc</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="funbas.html"><a href="funbas.html#funciones-sort-y-rank"><i class="fa fa-check"></i><b>5.11</b> Funciones <code>sort</code> y <code>rank</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-14"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejercicios-1"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bucles.html"><a href="bucles.html"><i class="fa fa-check"></i><b>6</b> Instrucciones de control</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bucles.html"><a href="bucles.html#instrucción-if"><i class="fa fa-check"></i><b>6.1</b> Instrucción <code>if</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-15"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bucles.html"><a href="bucles.html#instrucción-if-else"><i class="fa fa-check"></i><b>6.2</b> Instrucción <code>if</code> <code>else</code></a></li>
<li class="chapter" data-level="6.3" data-path="bucles.html"><a href="bucles.html#instrucción-ifelse"><i class="fa fa-check"></i><b>6.3</b> Instrucción <code>ifelse</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-16"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="bucles.html"><a href="bucles.html#instrucción-for"><i class="fa fa-check"></i><b>6.4</b> Instrucción <code>for</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-17"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="bucles.html"><a href="bucles.html#instrucción-while"><i class="fa fa-check"></i><b>6.5</b> Instrucción <code>while</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-18"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="bucles.html"><a href="bucles.html#instrucción-repeat"><i class="fa fa-check"></i><b>6.6</b> Instrucción <code>repeat</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-19"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="creafun.html"><a href="creafun.html"><i class="fa fa-check"></i><b>7</b> Creación de funciones en R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="creafun.html"><a href="creafun.html#qué-es-una-función-en-r"><i class="fa fa-check"></i><b>7.1</b> ¿Qué es una función en R?</a></li>
<li class="chapter" data-level="7.2" data-path="creafun.html"><a href="creafun.html#partes-de-una-función-en-r"><i class="fa fa-check"></i><b>7.2</b> Partes de una función en R</a>
<ul>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-20"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-21"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-22"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-23"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejercicios-2"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>8</b> Lectura de bases de datos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="read.html"><a href="read.html#qué-es-una-base-de-datos"><i class="fa fa-check"></i><b>8.1</b> ¿Qué es una base de datos?</a></li>
<li class="chapter" data-level="8.2" data-path="read.html"><a href="read.html#en-qué-formato-almacenar-una-base-de-datos"><i class="fa fa-check"></i><b>8.2</b> ¿En qué formato almacenar una base de datos?</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="read.html"><a href="read.html#almacenamiento-de-información-en-excel"><i class="fa fa-check"></i><b>8.2.1</b> Almacenamiento de información en Excel</a></li>
<li class="chapter" data-level="8.2.2" data-path="read.html"><a href="read.html#almacenamiento-de-información-en-bloc-de-notas"><i class="fa fa-check"></i><b>8.2.2</b> Almacenamiento de información en bloc de notas</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="read.html"><a href="read.html#función-read.table"><i class="fa fa-check"></i><b>8.3</b> Función <code>read.table</code></a>
<ul>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-24"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-25"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="read.html"><a href="read.html#lectura-de-bases-de-datos-en-excel"><i class="fa fa-check"></i><b>8.4</b> Lectura de bases de datos en Excel</a>
<ul>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-26"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejercicios-3"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tablas.html"><a href="tablas.html"><i class="fa fa-check"></i><b>9</b> Tablas de frecuencia</a>
<ul>
<li class="chapter" data-level="9.1" data-path="tablas.html"><a href="tablas.html#tabla-de-contingencia-con-table"><i class="fa fa-check"></i><b>9.1</b> Tabla de contingencia con <code>table</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-de-una-vía"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia de una vía</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-de-dos-vías"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia de dos vías</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="tablas.html"><a href="tablas.html#función-prop.table"><i class="fa fa-check"></i><b>9.2</b> Función <code>prop.table</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-relativa-de-una-vía"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia relativa de una vía</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-relativa-de-dos-vías"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia relativa de dos vías</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="tablas.html"><a href="tablas.html#función-addmargins"><i class="fa fa-check"></i><b>9.3</b> Función <code>addmargins</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-27"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="tablas.html"><a href="tablas.html#función-hist"><i class="fa fa-check"></i><b>9.4</b> Función <code>hist</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-28"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-29"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejercicios-4"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="central.html"><a href="central.html"><i class="fa fa-check"></i><b>10</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="10.1" data-path="central.html"><a href="central.html#media"><i class="fa fa-check"></i><b>10.1</b> Media </a>
<ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-30"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-31"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-32"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="central.html"><a href="central.html#mediana"><i class="fa fa-check"></i><b>10.2</b> Mediana </a>
<ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-33"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="central.html"><a href="central.html#moda"><i class="fa fa-check"></i><b>10.3</b> Moda </a>
<ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-34"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="varia.html"><a href="varia.html"><i class="fa fa-check"></i><b>11</b> Medidas de variabilidad</a>
<ul>
<li class="chapter" data-level="11.1" data-path="varia.html"><a href="varia.html#rango"><i class="fa fa-check"></i><b>11.1</b> Rango </a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-35"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-36"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="varia.html"><a href="varia.html#varianza"><i class="fa fa-check"></i><b>11.2</b> Varianza</a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-37"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-38"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="varia.html"><a href="varia.html#desviación-estándar"><i class="fa fa-check"></i><b>11.3</b> Desviación estándar</a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-39"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-40"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="varia.html"><a href="varia.html#coeficiente-de-variación-cv"><i class="fa fa-check"></i><b>11.4</b> Coeficiente de variación (<span class="math inline">\(CV\)</span>) </a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-41"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="posi.html"><a href="posi.html"><i class="fa fa-check"></i><b>12</b> Medidas de posición</a>
<ul>
<li class="chapter" data-level="12.1" data-path="posi.html"><a href="posi.html#cuantiles"><i class="fa fa-check"></i><b>12.1</b> Cuantiles </a>
<ul>
<li class="chapter" data-level="" data-path="posi.html"><a href="posi.html#ejemplo-42"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>13</b> Medidas de correlación</a>
<ul>
<li class="chapter" data-level="13.1" data-path="correl.html"><a href="correl.html#función-cor"><i class="fa fa-check"></i><b>13.1</b> Función <code>cor</code> </a>
<ul>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-43"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-44"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-45"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-46"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejercicios-5"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html"><i class="fa fa-check"></i><b>14</b> Estadística descriptiva con dplyr</a>
<ul>
<li class="chapter" data-level="14.1" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#medidas-de-tendencia-central-variabilidad-posición-y-correlación"><i class="fa fa-check"></i><b>14.1</b> Medidas de tendencia central, variabilidad, posición y correlación</a></li>
<li class="chapter" data-level="14.2" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#paquete-dplyr"><i class="fa fa-check"></i><b>14.2</b> Paquete dplyr</a></li>
<li class="chapter" data-level="14.3" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#pipes-en-r"><i class="fa fa-check"></i><b>14.3</b> Pipes en R</a></li>
<li class="chapter" data-level="14.4" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#estadística-descriptiva-con-dplyr-1"><i class="fa fa-check"></i><b>14.4</b> Estadística descriptiva con dplyr</a></li>
<li class="chapter" data-level="14.5" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#creando-nuevas-variables"><i class="fa fa-check"></i><b>14.5</b> Creando nuevas variables</a></li>
<li class="chapter" data-level="14.6" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#tablas-de-frecuencia"><i class="fa fa-check"></i><b>14.6</b> Tablas de frecuencia</a></li>
<li class="chapter" data-level="14.7" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#gráficos"><i class="fa fa-check"></i><b>14.7</b> Gráficos</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html"><i class="fa fa-check"></i><b>15</b> Variables aleatorias</a>
<ul>
<li class="chapter" data-level="15.1" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#variable-aleatoria-discreta"><i class="fa fa-check"></i><b>15.1</b> Variable aleatoria discreta</a>
<ul>
<li class="chapter" data-level="" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#ejemplo-47"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#variable-aleatoria-continua"><i class="fa fa-check"></i><b>15.2</b> Variable aleatoria continua</a>
<ul>
<li class="chapter" data-level="" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#ejemplo-48"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="discretas.html"><a href="discretas.html"><i class="fa fa-check"></i><b>16</b> Distribuciones discretas</a>
<ul>
<li class="chapter" data-level="16.1" data-path="discretas.html"><a href="discretas.html#funciones-disponibles-para-distribuciones-discretas"><i class="fa fa-check"></i><b>16.1</b> Funciones disponibles para distribuciones discretas</a>
<ul>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-binomial"><i class="fa fa-check"></i>Ejemplo binomial</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-geométrica"><i class="fa fa-check"></i>Ejemplo geométrica</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-binomial-negativa"><i class="fa fa-check"></i>Ejemplo binomial negativa</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-hipergeométrica"><i class="fa fa-check"></i>Ejemplo hipergeométrica</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-poisson"><i class="fa fa-check"></i>Ejemplo Poisson</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="discretas.html"><a href="discretas.html#distribuciones-discretas-generales"><i class="fa fa-check"></i><b>16.2</b> Distribuciones discretas generales</a>
<ul>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-49"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="continuas.html"><a href="continuas.html"><i class="fa fa-check"></i><b>17</b> Distribuciones continuas</a>
<ul>
<li class="chapter" data-level="17.1" data-path="continuas.html"><a href="continuas.html#funciones-disponibles-para-distribuciones-continuas"><i class="fa fa-check"></i><b>17.1</b> Funciones disponibles para distribuciones continuas</a>
<ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-beta"><i class="fa fa-check"></i>Ejemplo beta</a></li>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-normal-estándar"><i class="fa fa-check"></i>Ejemplo normal estándar</a></li>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-normal-general"><i class="fa fa-check"></i>Ejemplo normal general</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="continuas.html"><a href="continuas.html#distribuciones-continuas-generales"><i class="fa fa-check"></i><b>17.2</b> Distribuciones continuas generales</a>
<ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-50"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>18</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="18.1" data-path="normal.html"><a href="normal.html#función-de-densidad"><i class="fa fa-check"></i><b>18.1</b> Función de densidad</a></li>
<li class="chapter" data-level="18.2" data-path="normal.html"><a href="normal.html#visualización-de-la-distribución"><i class="fa fa-check"></i><b>18.2</b> Visualización de la distribución</a></li>
<li class="chapter" data-level="18.3" data-path="normal.html"><a href="normal.html#características-de-la-distribución-normal"><i class="fa fa-check"></i><b>18.3</b> Características de la Distribución Normal</a></li>
<li class="chapter" data-level="18.4" data-path="normal.html"><a href="normal.html#funciones-útiles-asociadas-a-la-normal"><i class="fa fa-check"></i><b>18.4</b> Funciones útiles asociadas a la normal</a></li>
<li class="chapter" data-level="18.5" data-path="normal.html"><a href="normal.html#cálculo-de-probabilidades"><i class="fa fa-check"></i><b>18.5</b> Cálculo de Probabilidades</a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-51"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-52"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-53"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="normal.html"><a href="normal.html#cálculo-de-cuantiles"><i class="fa fa-check"></i><b>18.6</b> Cálculo de cuantiles</a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-54"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="normal.html"><a href="normal.html#ejemplo-de-generación-de-datos"><i class="fa fa-check"></i><b>18.7</b> Ejemplo de generación de datos</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="loglik.html"><a href="loglik.html"><i class="fa fa-check"></i><b>19</b> Verosimilitud</a>
<ul>
<li class="chapter" data-level="19.1" data-path="loglik.html"><a href="loglik.html#función-de-verosimilitud"><i class="fa fa-check"></i><b>19.1</b> Función de verosimilitud</a></li>
<li class="chapter" data-level="19.2" data-path="loglik.html"><a href="loglik.html#función-de-log-verosimilitud"><i class="fa fa-check"></i><b>19.2</b> Función de log-verosimilitud</a></li>
<li class="chapter" data-level="19.3" data-path="loglik.html"><a href="loglik.html#método-de-máxima-verosimilitud-para-estimar-parámetros"><i class="fa fa-check"></i><b>19.3</b> Método de máxima verosimilitud para estimar parámetros</a>
<ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-55"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-56"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-57"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="loglik.html"><a href="loglik.html#score-e-información-de-fisher"><i class="fa fa-check"></i><b>19.4</b> Score e Información de Fisher</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="loglik.html"><a href="loglik.html#score-e-información-de-fisher-en-el-caso-univariado."><i class="fa fa-check"></i><b>19.4.1</b> Score e Información de Fisher en el caso univariado.</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-58"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="loglik.html"><a href="loglik.html#método-de-máxima-verosimilitud-para-estimar-parámetros-en-modelos-de-regresión"><i class="fa fa-check"></i><b>19.5</b> Método de máxima verosimilitud para estimar parámetros en modelos de regresión</a>
<ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-59"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="loglik.html"><a href="loglik.html#paquete-maxlik"><i class="fa fa-check"></i><b>19.6</b> Paquete maxLik</a>
<ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-60"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejercicios-6"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="select_dist.html"><a href="select_dist.html"><i class="fa fa-check"></i><b>20</b> Selección de la distribución</a>
<ul>
<li class="chapter" data-level="20.1" data-path="select_dist.html"><a href="select_dist.html#función-fitdists"><i class="fa fa-check"></i><b>20.1</b> Función <code>fitDists</code></a>
<ul>
<li class="chapter" data-level="" data-path="select_dist.html"><a href="select_dist.html#ejemplo-61"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="select_dist.html"><a href="select_dist.html#qué-tipo-de-preguntas-se-podrían-responder-luego"><i class="fa fa-check"></i><b>20.2</b> ¿Qué tipo de preguntas se podrían responder luego?</a>
<ul>
<li class="chapter" data-level="" data-path="select_dist.html"><a href="select_dist.html#ejemplo-62"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="select_dist.html"><a href="select_dist.html#ejercicios-7"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="normalidad.html"><a href="normalidad.html"><i class="fa fa-check"></i><b>21</b> Estudiando la normalidad</a>
<ul>
<li class="chapter" data-level="21.1" data-path="normalidad.html"><a href="normalidad.html#consideraciones-iniciales"><i class="fa fa-check"></i><b>21.1</b> Consideraciones iniciales</a></li>
<li class="chapter" data-level="21.2" data-path="normalidad.html"><a href="normalidad.html#histograma-y-densidad"><i class="fa fa-check"></i><b>21.2</b> Histograma y densidad</a>
<ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-densidad-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo densidad con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-densidad-del-peso-corporal"><i class="fa fa-check"></i>Ejemplo densidad del peso corporal</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="normalidad.html"><a href="normalidad.html#gráficos-cuantil-cuantil"><i class="fa fa-check"></i><b>21.3</b> Gráficos cuantil cuantil </a>
<ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-1-qqplot-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo 1 QQplot con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-2-qqplot-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo 2 QQplot con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-qqplot-para-peso-corporal"><i class="fa fa-check"></i>Ejemplo QQplot para peso corporal</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-qqplot-con-bandas"><i class="fa fa-check"></i>Ejemplo QQplot con bandas</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="normalidad.html"><a href="normalidad.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>21.4</b> Pruebas de normalidad</a>
<ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-normalidad-para-peso-corporal"><i class="fa fa-check"></i>Ejemplo normalidad para peso corporal</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejercicios-8"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="ic.html"><a href="ic.html"><i class="fa fa-check"></i><b>22</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="22.1" data-path="ic.html"><a href="ic.html#función-t.test"><i class="fa fa-check"></i><b>22.1</b> Función <code>t.test</code></a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-media-mu"><i class="fa fa-check"></i><b>22.1.1</b> Intervalo de confianza bilateral para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-63"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="22.1.2" data-path="ic.html"><a href="ic.html#ICDifMed"><i class="fa fa-check"></i><b>22.1.2</b> Intervalo de confianza bilateral para la diferencia de medias (<span class="math inline">\(\mu_1-\mu_2\)</span>) de muestras independientes</a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-64"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="22.1.3" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-medias-mu_1-mu_2-de-muestras-dependientes-o-pareadas"><i class="fa fa-check"></i><b>22.1.3</b> Intervalo de confianza bilateral para la diferencia de medias (<span class="math inline">\(\mu_1-\mu_2\)</span>) de muestras dependientes o pareadas</a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-65"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="22.1.4" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-unilateral-para-la-media-mu"><i class="fa fa-check"></i><b>22.1.4</b> Intervalo de confianza unilateral para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-66"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="ic.html"><a href="ic.html#función-var.test"><i class="fa fa-check"></i><b>22.2</b> Función <code>var.test</code></a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-varianza-sigma2"><i class="fa fa-check"></i><b>22.2.1</b> Intervalo de confianza bilateral para la varianza <span class="math inline">\(\sigma^2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-67"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="22.2.2" data-path="ic.html"><a href="ic.html#ICCocVar"><i class="fa fa-check"></i><b>22.2.2</b> Intervalo de confianza bilateral para la razón de varianzas <span class="math inline">\(\sigma_1^2 / \sigma_2^2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-68"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="ic.html"><a href="ic.html#función-prop.test"><i class="fa fa-check"></i><b>22.3</b> Función <code>prop.test</code></a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-proporción-p"><i class="fa fa-check"></i><b>22.3.1</b> Intervalo de confianza bilateral para la proporción <span class="math inline">\(p\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-69"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="22.3.2" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-proporciones-p_1---p_2"><i class="fa fa-check"></i><b>22.3.2</b> Intervalo de confianza bilateral para la diferencia de proporciones <span class="math inline">\(p_1 - p_2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-70"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>23</b> Prueba de hipótesis</a>
<ul>
<li class="chapter" data-level="23.1" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-mu-de-una-población-normal"><i class="fa fa-check"></i><b>23.1</b> Prueba de hipótesis para <span class="math inline">\(\mu\)</span> de una población normal</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-71"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-mu-con-muestras-grandes"><i class="fa fa-check"></i><b>23.2</b> Prueba de hipótesis para <span class="math inline">\(\mu\)</span> con muestras grandes</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-72"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-proporción-p"><i class="fa fa-check"></i><b>23.3</b> Prueba de hipótesis para la proporción <span class="math inline">\(p\)</span></a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="ph.html"><a href="ph.html#prueba-de-wald"><i class="fa fa-check"></i><b>23.3.1</b> Prueba de Wald</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-73"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.3.2" data-path="ph.html"><a href="ph.html#prueba-chi2-de-pearson"><i class="fa fa-check"></i><b>23.3.2</b> Prueba <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-74"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.3.3" data-path="ph.html"><a href="ph.html#prueba-binomial-exacta"><i class="fa fa-check"></i><b>23.3.3</b> Prueba binomial exacta</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-75"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-varianza-sigma2-de-una-población-normal"><i class="fa fa-check"></i><b>23.4</b> Prueba de hipótesis para la varianza <span class="math inline">\(\sigma^2\)</span> de una población normal</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-76"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.5" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-el-cociente-de-varianzas-sigma_12-sigma_22"><i class="fa fa-check"></i><b>23.5</b> Prueba de hipótesis para el cociente de varianzas <span class="math inline">\(\sigma_1^2 / \sigma_2^2\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-77"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-78"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.6" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-iguales"><i class="fa fa-check"></i><b>23.6</b> Prueba de hipótesis para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> con varianzas iguales</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-79"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.7" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-diferentes"><i class="fa fa-check"></i><b>23.7</b> Prueba de hipótesis para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> con varianzas diferentes</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-80"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.8" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-proporciones-p_1---p_2"><i class="fa fa-check"></i><b>23.8</b> Prueba de hipótesis para la diferencia de proporciones <span class="math inline">\(p_1 - p_2\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-81"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.9" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-medias-pareadas"><i class="fa fa-check"></i><b>23.9</b> Prueba de hipótesis para la diferencia de medias pareadas</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-82"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="24" data-path="aproxint.html"><a href="aproxint.html"><i class="fa fa-check"></i><b>24</b> Aproximación de integrales</a>
<ul>
<li class="chapter" data-level="24.1" data-path="aproxint.html"><a href="aproxint.html#aproximación-de-laplace-unidimensional"><i class="fa fa-check"></i><b>24.1</b> Aproximación de Laplace unidimensional</a>
<ul>
<li class="chapter" data-level="" data-path="aproxint.html"><a href="aproxint.html#ejemplo-83"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="empiricaldists.html"><a href="empiricaldists.html"><i class="fa fa-check"></i><b>25</b> Distribuciones empíricas</a>
<ul>
<li class="chapter" data-level="25.1" data-path="empiricaldists.html"><a href="empiricaldists.html#una-variable"><i class="fa fa-check"></i><b>25.1</b> Una variable</a>
<ul>
<li class="chapter" data-level="" data-path="empiricaldists.html"><a href="empiricaldists.html#ejemplo-84"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="normalmulti.html"><a href="normalmulti.html"><i class="fa fa-check"></i><b>26</b> Distribución normal multivariada</a>
<ul>
<li class="chapter" data-level="26.1" data-path="normalmulti.html"><a href="normalmulti.html#función-de-densidad-1"><i class="fa fa-check"></i><b>26.1</b> Función de densidad</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-85"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-86"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-87"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="normalmulti.html"><a href="normalmulti.html#simulando-de-una-normal-multivariada"><i class="fa fa-check"></i><b>26.2</b> Simulando de una normal multivariada</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-88"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-89"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-90"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="26.3" data-path="normalmulti.html"><a href="normalmulti.html#calculando-probabilidades"><i class="fa fa-check"></i><b>26.3</b> Calculando probabilidades</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-91"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="26.4" data-path="normalmulti.html"><a href="normalmulti.html#distancia-de-mahalanobis"><i class="fa fa-check"></i><b>26.4</b> Distancia de Mahalanobis</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-92"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="26.5" data-path="normalmulti.html"><a href="normalmulti.html#ellipse-o-contornos-de-confianza"><i class="fa fa-check"></i><b>26.5</b> Ellipse o contornos de confianza</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-93"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-94"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="26.6" data-path="normalmulti.html"><a href="normalmulti.html#estimando-los-parámetros-boldsymbolmu-y-boldsymbolsigma"><i class="fa fa-check"></i><b>26.6</b> Estimando los parámetros <span class="math inline">\(\boldsymbol{\mu}\)</span> y <span class="math inline">\(\boldsymbol{\Sigma}\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-95"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-96"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="26.7" data-path="normalmulti.html"><a href="normalmulti.html#distribución-wishart"><i class="fa fa-check"></i><b>26.7</b> Distribución Wishart</a></li>
<li class="chapter" data-level="26.8" data-path="normalmulti.html"><a href="normalmulti.html#mezcla-de-dos-normales-multivariadas"><i class="fa fa-check"></i><b>26.8</b> Mezcla de dos normales multivariadas</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejercicios-9"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="curio.html"><a href="curio.html"><i class="fa fa-check"></i><b>27</b> Curiosidades</a>
<ul>
<li class="chapter" data-level="27.1" data-path="curio.html"><a href="curio.html#cómo-verificar-si-un-paquete-no-está-instalado-para-instalarlo-de-forma-automática"><i class="fa fa-check"></i><b>27.1</b> ¿Cómo verificar si un paquete no está instalado para instalarlo de forma automática?</a>
<ul>
<li class="chapter" data-level="" data-path="curio.html"><a href="curio.html#ejemplo-97"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Manual de R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-descriptiva-con-dplyr" class="section level1 hasAnchor" number="14">
<h1><span class="header-section-number">14</span> Estadística descriptiva con dplyr<a href="estadística-descriptiva-con-dplyr.html#estadística-descriptiva-con-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se mostrará como usar el paquete dplyr de R para hacer un análisis descriptivo usando una base de datos real.</p>
<p align="center">
<img src="images/babies.png" width="300">
</p>
<p>Las variables de la base de datos que vamos a utilizar en el ejemplo de este capítulo se muestran a continuación.</p>
<ul>
<li>bwt: Peso del bebé al nacer, redondeado a la <strong>onza</strong> más cercana.</li>
<li>gestación: Duración del embarazo en <strong>días</strong>, calculado a partir del primer día del último período menstrual normal.</li>
<li>paridad: Indicador de si el bebé es el primogénito o desconocido.</li>
<li>edad: edad de la madre en el momento de la concepción, en <strong>años</strong>.</li>
<li>altura: Altura de la madre, en <strong>pulgadas</strong>.</li>
<li>peso: peso de la madre antes del embarazo, en <strong>libras</strong>.</li>
<li>fumar: estado de tabaquismo Indicador de si la madre fuma o no.</li>
</ul>
<p>Las unidades de algunas de las variables están en sistema inglés, más adelante mostraremos cómo convertir esas variables.</p>
<p>Para leer la base de datos usamos el siguiente código.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="estadística-descriptiva-con-dplyr.html#cb409-1" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&#39;https://raw.githubusercontent.com/fhernanb/datos/master/babies.txt&#39;</span></span>
<span id="cb409-2"><a href="estadística-descriptiva-con-dplyr.html#cb409-2" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">read.table</span>(url, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">&#39;</span><span class="sc">\t</span><span class="st">&#39;</span>)</span></code></pre></div>
<p>Par ver el encabezado de la base de datos.</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="estadística-descriptiva-con-dplyr.html#cb410-1" tabindex="-1"></a><span class="fu">head</span>(dt, <span class="at">n=</span><span class="dv">8</span>)</span></code></pre></div>
<pre><code>##   bwt gestation     parity age height weight smoke
## 1 120       284 First born  27     62    100   Not
## 2 113       282 First born  33     64    135   Not
## 3 128       279 First born  28     64    115   Yes
## 4 123        NA First born  36     69    190   Not
## 5 108       282 First born  23     67    125   Yes
## 6 136       286 First born  25     62     93   Not
## 7 138       244 First born  33     62    178   Not
## 8 132       245 First born  23     65    140   Not</code></pre>
<p>Ahora vamos a explorar la base de datos por medio de la función <code>summary</code>.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="estadística-descriptiva-con-dplyr.html#cb412-1" tabindex="-1"></a><span class="fu">summary</span>(dt)</span></code></pre></div>
<pre><code>##       bwt          gestation        parity               age       
##  Min.   : 55.0   Min.   :148.0   Length:1236        Min.   :15.00  
##  1st Qu.:108.8   1st Qu.:272.0   Class :character   1st Qu.:23.00  
##  Median :120.0   Median :280.0   Mode  :character   Median :26.00  
##  Mean   :119.6   Mean   :279.3                      Mean   :27.26  
##  3rd Qu.:131.0   3rd Qu.:288.0                      3rd Qu.:31.00  
##  Max.   :176.0   Max.   :353.0                      Max.   :45.00  
##                  NA&#39;s   :13                         NA&#39;s   :2      
##      height          weight         smoke          
##  Min.   :53.00   Min.   : 87.0   Length:1236       
##  1st Qu.:62.00   1st Qu.:114.8   Class :character  
##  Median :64.00   Median :125.0   Mode  :character  
##  Mean   :64.05   Mean   :128.6                     
##  3rd Qu.:66.00   3rd Qu.:139.0                     
##  Max.   :72.00   Max.   :250.0                     
##  NA&#39;s   :22      NA&#39;s   :36</code></pre>
<p>Otra tabla de resumen se puede obtener con la función <code>str</code>.</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="estadística-descriptiva-con-dplyr.html#cb414-1" tabindex="-1"></a><span class="fu">str</span>(dt)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1236 obs. of  7 variables:
##  $ bwt      : int  120 113 128 123 108 136 138 132 120 143 ...
##  $ gestation: int  284 282 279 NA 282 286 244 245 289 299 ...
##  $ parity   : chr  &quot;First born&quot; &quot;First born&quot; &quot;First born&quot; &quot;First born&quot; ...
##  $ age      : int  27 33 28 36 23 25 33 23 25 30 ...
##  $ height   : int  62 64 64 69 67 62 62 65 62 66 ...
##  $ weight   : int  100 135 115 190 125 93 178 140 125 136 ...
##  $ smoke    : chr  &quot;Not&quot; &quot;Not&quot; &quot;Yes&quot; &quot;Not&quot; ...</code></pre>
<p>Para conocer la imension de la base de datos usamos la función <code>dim</code>.</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="estadística-descriptiva-con-dplyr.html#cb416-1" tabindex="-1"></a><span class="fu">dim</span>(dt)</span></code></pre></div>
<pre><code>## [1] 1236    7</code></pre>
<p>Para ver el peso de las madres.</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="estadística-descriptiva-con-dplyr.html#cb418-1" tabindex="-1"></a>dt<span class="sc">$</span>weight</span></code></pre></div>
<pre><code>##    [1] 100 135 115 190 125  93 178 140 125 136 120 124 128  99 154 130 125 125
##   [19] 170 142  93 175 145 182 122 112 106 175 125 132 105 146 123 105 120 130
##   [37] 115  92 101  NA 160 177  NA 119 130 110 150  90 147 119 130 148 110 126
##   [55] 132 130 145 140 116 110  96 118 125 130 125 115 150 137 170 170 130 118
##   [73] 125 120 149 110 107 130 126 103 116 104 135 148 145  NA 117 143 196 113
##   [91] 117 112 104 130 103 100 100 162 110 137 121 120  NA 117 108 140 143 150
##  [109] 125 154  NA 125 136  NA 145 114 109 215 145 170 103 133 130 155 150 150
##  [127] 110 120 154 148 103 110 125 100 147 120 135 145 104 165 107 123 110 127
##  [145] 115 155 125 175 140 250 148 128  NA 132  NA 152 135 104  NA 121 111 138
##  [163] 190 123 125 160 123 105 123 110 109 118 115 105 131 155 170 123 125 120
##  [181] 175 192 116 220 150  NA 117  93  97 135 136 110 124  NA 155 150 168 147
##  [199] 117 110 140 132  97 112  NA 105 110 150 125 150 138 150  99 115 125 130
##  [217] 145 130 125 130 135 121 180 145 136 142 128 120 106 106  NA 117 116 127
##  [235] 135 135 160 120 155 110 190 140 105 125 117 125 128 124 169 125 110 105
##  [253] 110 125 185 142 118 139 160 128 135 148 105 122 140 104 125 132 102 140
##  [271] 103 119 165 115 156 150 120 135 160 140 142 140 118 103 146 126 135 189
##  [289] 157 108 135 122 148 152 140 100 105 105 110 122 125 125 102 125 135 130
##  [307] 130 112 145 117 176  NA 130 112 100 110 135 120 135 123 129 130 136 145
##  [325] 120 120 120 106 135 130 132 110 110 135 127 130 107  NA 103 157 144 130
##  [343] 112 130 130 130 103 110 117 122 110 113  NA 128 132 104 159 115 115 112
##  [361] 135 110 130  NA 145 147 130 112 170 122 125 122 136 143 135 130 121 108
##  [379] 128 105 125 109 100 145 137 150 115 155 112 130 145 124 145 118 100 140
##  [397] 125 134 115  NA 133 105 104 105 117 135 129 120 140 139 116 180 124 143
##  [415] 137 104 132 147 107 110 130 130 135 155 132 114 210 142 138 102 145 102
##  [433] 115 150 110 140 130 120 148  NA 135 108 111  NA 138 130 120 140 127 140
##  [451] 130 115 135 127 124 118 125 165 137 118 140 150 149 127 138  93 125 123
##  [469] 111 133 147  99 125 154 141 115 135  NA  NA 135 155  NA 135 110 130 144
##  [487] 135 135 123 155 130 128 122 118 123 125 120 125 122 162 103 110 111 130
##  [505] 117  95 129 126  NA 175 147 140 180 102 116 110 150 115 120 147 145 110
##  [523] 200 140 130  NA 117 125 180 135 120 109 113 132 110 124 160 160 103 130
##  [541] 128  96 127 120 106 122  89 108 138 125  95 145 140 107 125 135 155 105
##  [559] 102 114 124 137 170 197 171 145 130 165 146 135 134 135 132 105 110 133
##  [577] 132 112 159 135 150 125 105 125 113  98 130 135 119 130 150 127 120 140
##  [595] 129 110 114 130 115 107 155 118 126 115 110 137 115 139 215 140 100 160
##  [613] 107 108 132 116 165 109  98 110 110 115 202 135 112 108 108 118 125 126
##  [631] 112 130 180 145 130  90 100 118 120 145 118 135 129 112 128 155 124 125
##  [649]  NA 165 132 124 135  NA 112 101 117 115 115 135 133 134 119 125 115 110
##  [667] 108  98 105 145 120 140 130 110 107 132 115 118 124  95 116  94 145 125
##  [685] 115 110 102 140 120  94 160 105 120 117 126 175 174 112  NA 144 125 169
##  [703] 135 120 128 135 116 125 140 140 138 128 118 113 105 150 145 153 115 122
##  [721] 127 160 130 198 118 125 110 165 157 120 140 148 126 190 130 100 114 136
##  [739] 117 120 118 100 137 126 120  96 110 182 122 105 130 140 125  NA  98 135
##  [757] 105 125 127 125 120 130  NA 142 105 118 147 106 127 110 104 130 118 111
##  [775] 105 134 140 121 111 120 110 110 160 124 113 145 120  96 130 119 150 124
##  [793] 130 127 100 164 135 155 149 139 130 134 127 110 140 108 124 127 112 120
##  [811] 155 129 132 132 145 124 130 110 108 112 118 135 162 162 130 112 118  91
##  [829] 103 107 100 112 125 134 115 141 118 123 148 125 120 122 126 118 110 108
##  [847] 107 126 120 215 138 170 110 120 150 130 117 107 191 185 150 112 127 110
##  [865] 140 210 111 124 130 133 160 125 143 125  NA 150 100 129 150 110 135 109
##  [883]  NA 125 118 110 132 125 181 123 117 135 130 110 110 140 120 155 114 159
##  [901] 112 116 110 128 136 137 153 130  99 115 125 175 156 107 160 128 130 135
##  [919] 137 125 175 108 137 155 217 126 130 135 156 115 109 105 137 143 123 178
##  [937] 120 134 121 102 115 116 170 160 109 112 120 133 110 130 122 122 121 125
##  [955] 105 112 130 145 145 124 113 120 135 118 118 133 122 125 126 112 137 135
##  [973] 115 135 131 111 110 160 140 149 110 134 155 150 129 122 112 130 128 120
##  [991] 108  98 127 130 145 130 113 156 110 132 140 159 164 114 130 140 127 115
## [1009] 185 124 114 116 112  NA 133 115 115 145 140 127 120 185 130 135 145 130
## [1027] 150 109 110 142 125 132 110 110 120 130 116  90 130 125 112 127 132 128
## [1045]  NA 115 116 145 119 135 117 125 117 120 130 120 125 129 144 100 145 104
## [1063] 110 145 132 125 108 119 118 130 128  97 115 135 142 131 165 122 114 137
## [1081] 107 113 145 110 126 135 111 135 105 113 110 120 121 130 122 127 122 115
## [1099] 104 163 146 113 120 142 124 127 135 122 127 125 135 150 155 120 115 136
## [1117] 115 108 118 115 125 120 140 123  98 118 105 154 118 122 117 150 100 115
## [1135] 118 118 102 127 104  99 107 124 136 142 132 125 106 120 200 113 112 114
## [1153] 117  99 177 145 124 125 134 123 140 130 110 119 104 103 135 180 110 145
## [1171] 150 128 115  95 145 130 103  NA 126 101 113 130 137 112 127 140 110 145
## [1189] 140  89  NA 135 228 160 158 145 127 135 150 170 107 145 130 115 120 113
## [1207] 135 125 156 140 130 103 120 151 103 119 109 145 150 180  95 120 116 136
## [1225] 135 145 102  87 116 121 126 100 120 150 110 129</code></pre>
<p>Otra forma de ver el peso almacenado en columna 6.</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="estadística-descriptiva-con-dplyr.html#cb420-1" tabindex="-1"></a>dt[, <span class="dv">6</span>]</span></code></pre></div>
<pre><code>##    [1] 100 135 115 190 125  93 178 140 125 136 120 124 128  99 154 130 125 125
##   [19] 170 142  93 175 145 182 122 112 106 175 125 132 105 146 123 105 120 130
##   [37] 115  92 101  NA 160 177  NA 119 130 110 150  90 147 119 130 148 110 126
##   [55] 132 130 145 140 116 110  96 118 125 130 125 115 150 137 170 170 130 118
##   [73] 125 120 149 110 107 130 126 103 116 104 135 148 145  NA 117 143 196 113
##   [91] 117 112 104 130 103 100 100 162 110 137 121 120  NA 117 108 140 143 150
##  [109] 125 154  NA 125 136  NA 145 114 109 215 145 170 103 133 130 155 150 150
##  [127] 110 120 154 148 103 110 125 100 147 120 135 145 104 165 107 123 110 127
##  [145] 115 155 125 175 140 250 148 128  NA 132  NA 152 135 104  NA 121 111 138
##  [163] 190 123 125 160 123 105 123 110 109 118 115 105 131 155 170 123 125 120
##  [181] 175 192 116 220 150  NA 117  93  97 135 136 110 124  NA 155 150 168 147
##  [199] 117 110 140 132  97 112  NA 105 110 150 125 150 138 150  99 115 125 130
##  [217] 145 130 125 130 135 121 180 145 136 142 128 120 106 106  NA 117 116 127
##  [235] 135 135 160 120 155 110 190 140 105 125 117 125 128 124 169 125 110 105
##  [253] 110 125 185 142 118 139 160 128 135 148 105 122 140 104 125 132 102 140
##  [271] 103 119 165 115 156 150 120 135 160 140 142 140 118 103 146 126 135 189
##  [289] 157 108 135 122 148 152 140 100 105 105 110 122 125 125 102 125 135 130
##  [307] 130 112 145 117 176  NA 130 112 100 110 135 120 135 123 129 130 136 145
##  [325] 120 120 120 106 135 130 132 110 110 135 127 130 107  NA 103 157 144 130
##  [343] 112 130 130 130 103 110 117 122 110 113  NA 128 132 104 159 115 115 112
##  [361] 135 110 130  NA 145 147 130 112 170 122 125 122 136 143 135 130 121 108
##  [379] 128 105 125 109 100 145 137 150 115 155 112 130 145 124 145 118 100 140
##  [397] 125 134 115  NA 133 105 104 105 117 135 129 120 140 139 116 180 124 143
##  [415] 137 104 132 147 107 110 130 130 135 155 132 114 210 142 138 102 145 102
##  [433] 115 150 110 140 130 120 148  NA 135 108 111  NA 138 130 120 140 127 140
##  [451] 130 115 135 127 124 118 125 165 137 118 140 150 149 127 138  93 125 123
##  [469] 111 133 147  99 125 154 141 115 135  NA  NA 135 155  NA 135 110 130 144
##  [487] 135 135 123 155 130 128 122 118 123 125 120 125 122 162 103 110 111 130
##  [505] 117  95 129 126  NA 175 147 140 180 102 116 110 150 115 120 147 145 110
##  [523] 200 140 130  NA 117 125 180 135 120 109 113 132 110 124 160 160 103 130
##  [541] 128  96 127 120 106 122  89 108 138 125  95 145 140 107 125 135 155 105
##  [559] 102 114 124 137 170 197 171 145 130 165 146 135 134 135 132 105 110 133
##  [577] 132 112 159 135 150 125 105 125 113  98 130 135 119 130 150 127 120 140
##  [595] 129 110 114 130 115 107 155 118 126 115 110 137 115 139 215 140 100 160
##  [613] 107 108 132 116 165 109  98 110 110 115 202 135 112 108 108 118 125 126
##  [631] 112 130 180 145 130  90 100 118 120 145 118 135 129 112 128 155 124 125
##  [649]  NA 165 132 124 135  NA 112 101 117 115 115 135 133 134 119 125 115 110
##  [667] 108  98 105 145 120 140 130 110 107 132 115 118 124  95 116  94 145 125
##  [685] 115 110 102 140 120  94 160 105 120 117 126 175 174 112  NA 144 125 169
##  [703] 135 120 128 135 116 125 140 140 138 128 118 113 105 150 145 153 115 122
##  [721] 127 160 130 198 118 125 110 165 157 120 140 148 126 190 130 100 114 136
##  [739] 117 120 118 100 137 126 120  96 110 182 122 105 130 140 125  NA  98 135
##  [757] 105 125 127 125 120 130  NA 142 105 118 147 106 127 110 104 130 118 111
##  [775] 105 134 140 121 111 120 110 110 160 124 113 145 120  96 130 119 150 124
##  [793] 130 127 100 164 135 155 149 139 130 134 127 110 140 108 124 127 112 120
##  [811] 155 129 132 132 145 124 130 110 108 112 118 135 162 162 130 112 118  91
##  [829] 103 107 100 112 125 134 115 141 118 123 148 125 120 122 126 118 110 108
##  [847] 107 126 120 215 138 170 110 120 150 130 117 107 191 185 150 112 127 110
##  [865] 140 210 111 124 130 133 160 125 143 125  NA 150 100 129 150 110 135 109
##  [883]  NA 125 118 110 132 125 181 123 117 135 130 110 110 140 120 155 114 159
##  [901] 112 116 110 128 136 137 153 130  99 115 125 175 156 107 160 128 130 135
##  [919] 137 125 175 108 137 155 217 126 130 135 156 115 109 105 137 143 123 178
##  [937] 120 134 121 102 115 116 170 160 109 112 120 133 110 130 122 122 121 125
##  [955] 105 112 130 145 145 124 113 120 135 118 118 133 122 125 126 112 137 135
##  [973] 115 135 131 111 110 160 140 149 110 134 155 150 129 122 112 130 128 120
##  [991] 108  98 127 130 145 130 113 156 110 132 140 159 164 114 130 140 127 115
## [1009] 185 124 114 116 112  NA 133 115 115 145 140 127 120 185 130 135 145 130
## [1027] 150 109 110 142 125 132 110 110 120 130 116  90 130 125 112 127 132 128
## [1045]  NA 115 116 145 119 135 117 125 117 120 130 120 125 129 144 100 145 104
## [1063] 110 145 132 125 108 119 118 130 128  97 115 135 142 131 165 122 114 137
## [1081] 107 113 145 110 126 135 111 135 105 113 110 120 121 130 122 127 122 115
## [1099] 104 163 146 113 120 142 124 127 135 122 127 125 135 150 155 120 115 136
## [1117] 115 108 118 115 125 120 140 123  98 118 105 154 118 122 117 150 100 115
## [1135] 118 118 102 127 104  99 107 124 136 142 132 125 106 120 200 113 112 114
## [1153] 117  99 177 145 124 125 134 123 140 130 110 119 104 103 135 180 110 145
## [1171] 150 128 115  95 145 130 103  NA 126 101 113 130 137 112 127 140 110 145
## [1189] 140  89  NA 135 228 160 158 145 127 135 150 170 107 145 130 115 120 113
## [1207] 135 125 156 140 130 103 120 151 103 119 109 145 150 180  95 120 116 136
## [1225] 135 145 102  87 116 121 126 100 120 150 110 129</code></pre>
<p>Para ver la información de las madres 2, 125, 569 y 830 podemos usar el siguiente código:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="estadística-descriptiva-con-dplyr.html#cb422-1" tabindex="-1"></a>dt[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">125</span>, <span class="dv">569</span>, <span class="dv">830</span>), ]</span></code></pre></div>
<pre><code>##     bwt gestation     parity age height weight smoke
## 2   113       282 First born  33     64    135   Not
## 125 117       276 First born  31     69    150   Not
## 569 127       254 First born  27     67    146   Yes
## 830  62       228 First born  24     61    107   Not</code></pre>
<p>Para ver la edad y smoke de las mujeres 40, 58, 69 y 256 podemos usar el siguiente código:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="estadística-descriptiva-con-dplyr.html#cb424-1" tabindex="-1"></a>dt[<span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">58</span>, <span class="dv">69</span>, <span class="dv">256</span>), <span class="fu">c</span>(<span class="st">&#39;age&#39;</span>, <span class="st">&#39;smoke&#39;</span>)]</span></code></pre></div>
<pre><code>##     age smoke
## 40   31   Not
## 58   33   Not
## 69   31   Yes
## 256  31  &lt;NA&gt;</code></pre>
<div id="medidas-de-tendencia-central-variabilidad-posición-y-correlación" class="section level2 hasAnchor" number="14.1">
<h2><span class="header-section-number">14.1</span> Medidas de tendencia central, variabilidad, posición y correlación<a href="estadística-descriptiva-con-dplyr.html#medidas-de-tendencia-central-variabilidad-posición-y-correlación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección vamos a mostrar como se pueden obtener algunas medidas de resumen para los datos usando funciones básicas de R como son:</p>
<ul>
<li><code>mean(x, trim=0, na.rm=FALSE)</code>: para calcular el promedio.</li>
<li><code>var(x, na.rm=FALSE)</code>: para calcular la varianza <strong>muestral</strong>.</li>
<li><code>sd(x, na.rm=FALSE)</code>: para calcular la desviación estándar <strong>muestral</strong>.</li>
<li><code>quantile(x, probs, na.rm=FALSE)</code>: para calcular cuantiles.</li>
<li><code>min(x, na.rm=FALSE)</code>: para calcular el mínimo.</li>
<li><code>max(x, na.rm=FALSE)</code>: para calcular el máximo.</li>
</ul>
<p>¿Cuál es el peso promedio de las madres?</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="estadística-descriptiva-con-dplyr.html#cb426-1" tabindex="-1"></a><span class="fu">mean</span>(dt<span class="sc">$</span>weight)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>El resultado de <code>NA</code> se debe a los NA’s presentes en la base de datos. Para remover los NA’s podemos proceder de la siguiente manera:</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="estadística-descriptiva-con-dplyr.html#cb428-1" tabindex="-1"></a><span class="fu">mean</span>(dt<span class="sc">$</span>weight, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 128.6258</code></pre>
<p>Vamos ahora a averiguar características de resumen para el peso de los bebés.</p>
<p align="center">
<img src="images/pesando_bebe.jpg" width="300">
</p>
<p>¿Cual es el peso promedio de los bebés?</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="estadística-descriptiva-con-dplyr.html#cb430-1" tabindex="-1"></a><span class="fu">mean</span>(dt<span class="sc">$</span>bwt)</span></code></pre></div>
<pre><code>## [1] 119.5769</code></pre>
<p>¿Cual es la varianza del peso de los bebés?</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="estadística-descriptiva-con-dplyr.html#cb432-1" tabindex="-1"></a><span class="fu">var</span>(dt<span class="sc">$</span>bwt)</span></code></pre></div>
<pre><code>## [1] 332.5682</code></pre>
<p>¿Cual es la desviación del peso de los bebés?</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="estadística-descriptiva-con-dplyr.html#cb434-1" tabindex="-1"></a><span class="fu">sd</span>(dt<span class="sc">$</span>bwt)</span></code></pre></div>
<pre><code>## [1] 18.23645</code></pre>
<p>¿Cuales son Q1, D4 y P90 para el peso de los bebés?</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="estadística-descriptiva-con-dplyr.html#cb436-1" tabindex="-1"></a><span class="fu">quantile</span>(dt<span class="sc">$</span>bwt, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.40</span>, <span class="fl">0.90</span>))</span></code></pre></div>
<pre><code>##    25%    40%    90% 
## 108.75 116.00 142.00</code></pre>
</div>
<div id="paquete-dplyr" class="section level2 hasAnchor" number="14.2">
<h2><span class="header-section-number">14.2</span> Paquete dplyr<a href="estadística-descriptiva-con-dplyr.html#paquete-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El paquete <strong>dplyr</strong> es un paquete que se usa para manejar bases de datos. <a href="https://cran.r-project.org/web/packages/dplyr/index.html">En este enlace</a> puede consultar la ayuda del paquete y ver la viñetas con ejemplos de las funciones del paquete.</p>
<p>El paquete <strong>dplyr</strong> hace parte de un ecosistema llamado <strong>tidyverse</strong>, el cual es un conjunto de paquetes complementarios utilizados para hacer análisis de datos.</p>
<p>A continuación una figura con algunos de los paquetes de <strong>tidyverse</strong>.</p>
<p align="center">
<img src="images/tidyverse_logo.png" width="200">
</p>
<p>A continuación se muestra el hexalogo del paquete <strong>dplyr</strong> que vamos a utilizar en esta publicación.</p>
<p align="center">
<img src="images/dplyr_logo.jpeg" width="200">
</p>
<p>Para usar el paquete <strong>dplyr</strong> podemos cargar a <strong>tidyverse</strong> o directamente a <strong>dplyr</strong> así:</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="estadística-descriptiva-con-dplyr.html#cb438-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<p>En el mensaje anterior se aclara que hay unas funciones de <strong>dplyr</strong> que enmarcaran otras funciones de los paquetes <strong>stats</strong> y <strong>base</strong>.</p>
</div>
<div id="pipes-en-r" class="section level2 hasAnchor" number="14.3">
<h2><span class="header-section-number">14.3</span> Pipes en R<a href="estadística-descriptiva-con-dplyr.html#pipes-en-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En R se tienen dos tipos de operadores pipe:</p>
<ul>
<li><code>%&gt;%</code> del paquete <strong>magrittr</strong>.</li>
<li><code>|&gt;</code> nativo y pertenece a la base de R.</li>
</ul>
<p>Los operadores pipe sirve para escribir instrucciones de manera secuencial. A continuación vamos a mostrar dos ejemplos de la misma operación usando ambos pipe.</p>
<p>El objetivo es tomar la base de datos <code>dt</code>, extraer la variable <code>bwt</code> y al vector o variable resultante calcularle la media con <code>mean</code>.</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="estadística-descriptiva-con-dplyr.html#cb439-1" tabindex="-1"></a>dt <span class="sc">%&gt;%</span> <span class="fu">pull</span>(bwt) <span class="sc">%&gt;%</span> mean  <span class="co"># Usando pipe de magrittr</span></span></code></pre></div>
<pre><code>## [1] 119.5769</code></pre>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="estadística-descriptiva-con-dplyr.html#cb441-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(bwt) <span class="sc">|&gt;</span> <span class="fu">mean</span>()  <span class="co"># Usando pipe nativo</span></span></code></pre></div>
<pre><code>## [1] 119.5769</code></pre>
<p>De la salida anterior vemos que los resultados son idénticos.</p>
<p>Para ver una comparación de los dos pipe se recomienda ver el siguiente video.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/TmSwDAvPX2Q?si=wwqJ-0nPdwLJUyPB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
</iframe>
</div>
<div id="estadística-descriptiva-con-dplyr-1" class="section level2 hasAnchor" number="14.4">
<h2><span class="header-section-number">14.4</span> Estadística descriptiva con dplyr<a href="estadística-descriptiva-con-dplyr.html#estadística-descriptiva-con-dplyr-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La función <code>glimpse</code> del paquete <strong>dplyr</strong> nos da un resumen de las variables de la base de datos.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="estadística-descriptiva-con-dplyr.html#cb443-1" tabindex="-1"></a><span class="fu">glimpse</span>(dt)</span></code></pre></div>
<pre><code>## Rows: 1,236
## Columns: 7
## $ bwt       &lt;int&gt; 120, 113, 128, 123, 108, 136, 138, 132, 120, 143, 140, 144, …
## $ gestation &lt;int&gt; 284, 282, 279, NA, 282, 286, 244, 245, 289, 299, 351, 282, 2…
## $ parity    &lt;chr&gt; &quot;First born&quot;, &quot;First born&quot;, &quot;First born&quot;, &quot;First born&quot;, &quot;Fir…
## $ age       &lt;int&gt; 27, 33, 28, 36, 23, 25, 33, 23, 25, 30, 27, 32, 23, 36, 30, …
## $ height    &lt;int&gt; 62, 64, 64, 69, 67, 62, 62, 65, 62, 66, 68, 64, 63, 61, 63, …
## $ weight    &lt;int&gt; 100, 135, 115, 190, 125, 93, 178, 140, 125, 136, 120, 124, 1…
## $ smoke     &lt;chr&gt; &quot;Not&quot;, &quot;Not&quot;, &quot;Yes&quot;, &quot;Not&quot;, &quot;Yes&quot;, &quot;Not&quot;, &quot;Not&quot;, &quot;Not&quot;, &quot;Not…</code></pre>
<p>Vamos a extraer una sola variable con <code>pull</code> y luego a calcular la media, varianza y desviación estándar del peso de los bebés.</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="estadística-descriptiva-con-dplyr.html#cb445-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(bwt) <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span></code></pre></div>
<pre><code>## [1] 119.5769</code></pre>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="estadística-descriptiva-con-dplyr.html#cb447-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(bwt) <span class="sc">|&gt;</span> <span class="fu">var</span>()</span></code></pre></div>
<pre><code>## [1] 332.5682</code></pre>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="estadística-descriptiva-con-dplyr.html#cb449-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(bwt) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span></code></pre></div>
<pre><code>## [1] 18.23645</code></pre>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="estadística-descriptiva-con-dplyr.html#cb451-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(bwt) <span class="sc">|&gt;</span> <span class="fu">quantile</span>(<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.40</span>, <span class="fl">0.90</span>))</span></code></pre></div>
<pre><code>##    25%    40%    90% 
## 108.75 116.00 142.00</code></pre>
<p>Vamos a calcular las mismas medidas de resumen anteriores pero con escritura secuencial usando el operador pipe <code>|&gt;</code> y la función <code>summarise</code>.</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="estadística-descriptiva-con-dplyr.html#cb453-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">media_peso =</span> <span class="fu">mean</span>(bwt),</span>
<span id="cb453-2"><a href="estadística-descriptiva-con-dplyr.html#cb453-2" tabindex="-1"></a>                <span class="at">varianza_peso =</span> <span class="fu">var</span>(bwt),</span>
<span id="cb453-3"><a href="estadística-descriptiva-con-dplyr.html#cb453-3" tabindex="-1"></a>                <span class="at">desvi_peso =</span> <span class="fu">sd</span>(bwt),</span>
<span id="cb453-4"><a href="estadística-descriptiva-con-dplyr.html#cb453-4" tabindex="-1"></a>                <span class="at">Q1 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.25</span>),</span>
<span id="cb453-5"><a href="estadística-descriptiva-con-dplyr.html#cb453-5" tabindex="-1"></a>                <span class="at">D4 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.40</span>),</span>
<span id="cb453-6"><a href="estadística-descriptiva-con-dplyr.html#cb453-6" tabindex="-1"></a>                <span class="at">P90 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.90</span>))</span></code></pre></div>
<pre><code>##   media_peso varianza_peso desvi_peso     Q1  D4 P90
## 1   119.5769      332.5682   18.23645 108.75 116 142</code></pre>
<p>Vamos a ver cómo cambian las medidas anteriores cuando diferenciamos por el tipo de embarazo.</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="estadística-descriptiva-con-dplyr.html#cb455-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">group_by</span>(parity) <span class="sc">|&gt;</span> </span>
<span id="cb455-2"><a href="estadística-descriptiva-con-dplyr.html#cb455-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media_peso =</span> <span class="fu">mean</span>(bwt),</span>
<span id="cb455-3"><a href="estadística-descriptiva-con-dplyr.html#cb455-3" tabindex="-1"></a>            <span class="at">varianza_peso =</span> <span class="fu">var</span>(bwt),</span>
<span id="cb455-4"><a href="estadística-descriptiva-con-dplyr.html#cb455-4" tabindex="-1"></a>            <span class="at">desvi_peso =</span> <span class="fu">sd</span>(bwt),</span>
<span id="cb455-5"><a href="estadística-descriptiva-con-dplyr.html#cb455-5" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.25</span>),</span>
<span id="cb455-6"><a href="estadística-descriptiva-con-dplyr.html#cb455-6" tabindex="-1"></a>            <span class="at">D4 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.40</span>),</span>
<span id="cb455-7"><a href="estadística-descriptiva-con-dplyr.html#cb455-7" tabindex="-1"></a>            <span class="at">P90 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.90</span>),</span>
<span id="cb455-8"><a href="estadística-descriptiva-con-dplyr.html#cb455-8" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 8
##   parity     media_peso varianza_peso desvi_peso    Q1    D4   P90     n
##   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 First born       120.          345.       18.6   109   116   143   921
## 2 Unknown          118.          294.       17.1   107   114   139   315</code></pre>
<p>Vamos a ver como cambiar las medidas anteriores cuando diferenciamos por fumar.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="estadística-descriptiva-con-dplyr.html#cb457-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">group_by</span>(smoke) <span class="sc">|&gt;</span> </span>
<span id="cb457-2"><a href="estadística-descriptiva-con-dplyr.html#cb457-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media_peso =</span> <span class="fu">mean</span>(bwt),</span>
<span id="cb457-3"><a href="estadística-descriptiva-con-dplyr.html#cb457-3" tabindex="-1"></a>            <span class="at">varianza_peso =</span> <span class="fu">var</span>(bwt),</span>
<span id="cb457-4"><a href="estadística-descriptiva-con-dplyr.html#cb457-4" tabindex="-1"></a>            <span class="at">desvi_peso =</span> <span class="fu">sd</span>(bwt),</span>
<span id="cb457-5"><a href="estadística-descriptiva-con-dplyr.html#cb457-5" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.25</span>),</span>
<span id="cb457-6"><a href="estadística-descriptiva-con-dplyr.html#cb457-6" tabindex="-1"></a>            <span class="at">D4 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.40</span>),</span>
<span id="cb457-7"><a href="estadística-descriptiva-con-dplyr.html#cb457-7" tabindex="-1"></a>            <span class="at">P90 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.90</span>),</span>
<span id="cb457-8"><a href="estadística-descriptiva-con-dplyr.html#cb457-8" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 3 × 8
##   smoke media_peso varianza_peso desvi_peso    Q1    D4   P90     n
##   &lt;chr&gt;      &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 Not         123.          303.       17.4  113   119   144    742
## 2 Yes         114.          328.       18.1  102   109.  138    484
## 3 &lt;NA&gt;        127.          476.       21.8  110.  122.  152.    10</code></pre>
<p>Vamos a ver como cambiar las medidas anteriores cuando diferenciamos por el tipo de embarazo y fumar.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="estadística-descriptiva-con-dplyr.html#cb459-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">group_by</span>(parity, smoke) <span class="sc">|&gt;</span> </span>
<span id="cb459-2"><a href="estadística-descriptiva-con-dplyr.html#cb459-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media_peso =</span> <span class="fu">mean</span>(bwt),</span>
<span id="cb459-3"><a href="estadística-descriptiva-con-dplyr.html#cb459-3" tabindex="-1"></a>            <span class="at">varianza_peso =</span> <span class="fu">var</span>(bwt),</span>
<span id="cb459-4"><a href="estadística-descriptiva-con-dplyr.html#cb459-4" tabindex="-1"></a>            <span class="at">desvi_peso =</span> <span class="fu">sd</span>(bwt),</span>
<span id="cb459-5"><a href="estadística-descriptiva-con-dplyr.html#cb459-5" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.25</span>),</span>
<span id="cb459-6"><a href="estadística-descriptiva-con-dplyr.html#cb459-6" tabindex="-1"></a>            <span class="at">D4 =</span> <span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.40</span>),</span>
<span id="cb459-7"><a href="estadística-descriptiva-con-dplyr.html#cb459-7" tabindex="-1"></a>            <span class="at">P90 =</span><span class="fu">quantile</span>(bwt, <span class="at">probs=</span><span class="fl">0.90</span>),</span>
<span id="cb459-8"><a href="estadística-descriptiva-con-dplyr.html#cb459-8" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;parity&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre><code>## # A tibble: 5 × 9
## # Groups:   parity [2]
##   parity     smoke media_peso varianza_peso desvi_peso    Q1    D4   P90     n
##   &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 First born Not         124.          308.       17.6  113   120   145    548
## 2 First born Yes         114.          345.       18.6  101   110   139.   363
## 3 First born &lt;NA&gt;        127.          476.       21.8  110.  122.  152.    10
## 4 Unknown    Not         121.          284.       16.8  112   117   140    194
## 5 Unknown    Yes         113.          275.       16.6  102   109   131    121</code></pre>
<p>Calculando la correlación entre peso bebe y peso madre.</p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="estadística-descriptiva-con-dplyr.html#cb462-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">select</span>(bwt, weight) <span class="sc">|&gt;</span> <span class="fu">cor</span>()</span></code></pre></div>
<pre><code>##        bwt weight
## bwt      1     NA
## weight  NA      1</code></pre>
<p>Como hay NA en alguna de las variables vamos a agregar <code>use='complete.obs'</code> para obtener la correlación.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="estadística-descriptiva-con-dplyr.html#cb464-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">select</span>(bwt, weight) <span class="sc">|&gt;</span> <span class="fu">cor</span>(<span class="at">use=</span><span class="st">&#39;complete.obs&#39;</span>)</span></code></pre></div>
<pre><code>##              bwt    weight
## bwt    1.0000000 0.1540382
## weight 0.1540382 1.0000000</code></pre>
<p>De la salida anterior vemos que la correlación lineal de Pearson entre ambas variables es 0.1541.</p>
</div>
<div id="creando-nuevas-variables" class="section level2 hasAnchor" number="14.5">
<h2><span class="header-section-number">14.5</span> Creando nuevas variables<a href="estadística-descriptiva-con-dplyr.html#creando-nuevas-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección vamos a mostrar cómo crear nuevas variables a partir de variables ya existentes en la base de datos.</p>
<p>Vamos a transformar la altura y el peso de la madre al <a href="https://es.wikipedia.org/wiki/Sistema_Internacional_de_Unidades">sistema internacional de unidades</a>.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="estadística-descriptiva-con-dplyr.html#cb466-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">height_mt =</span> height <span class="sc">*</span> <span class="fl">0.0254</span>,</span>
<span id="cb466-2"><a href="estadística-descriptiva-con-dplyr.html#cb466-2" tabindex="-1"></a>             <span class="at">weight_kg =</span> weight <span class="sc">*</span> <span class="fl">0.453592</span>) <span class="ot">-&gt;</span> dt</span>
<span id="cb466-3"><a href="estadística-descriptiva-con-dplyr.html#cb466-3" tabindex="-1"></a></span>
<span id="cb466-4"><a href="estadística-descriptiva-con-dplyr.html#cb466-4" tabindex="-1"></a><span class="fu">head</span>(dt, <span class="at">n=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>##   bwt gestation     parity age height weight smoke height_mt weight_kg
## 1 120       284 First born  27     62    100   Not    1.5748  45.35920
## 2 113       282 First born  33     64    135   Not    1.6256  61.23492
## 3 128       279 First born  28     64    115   Yes    1.6256  52.16308
## 4 123        NA First born  36     69    190   Not    1.7526  86.18248</code></pre>
<p>Ahora vamos a calcular el IMC con las nuevas variables así:</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="estadística-descriptiva-con-dplyr.html#cb468-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">imc =</span> weight_kg <span class="sc">/</span> height_mt<span class="sc">^</span><span class="dv">2</span>) <span class="ot">-&gt;</span> dt</span>
<span id="cb468-2"><a href="estadística-descriptiva-con-dplyr.html#cb468-2" tabindex="-1"></a></span>
<span id="cb468-3"><a href="estadística-descriptiva-con-dplyr.html#cb468-3" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="at">n=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>##   bwt gestation     parity age height weight smoke height_mt weight_kg      imc
## 1 120       284 First born  27     62    100   Not    1.5748  45.35920 18.29004
## 2 113       282 First born  33     64    135   Not    1.6256  61.23492 23.17244
## 3 128       279 First born  28     64    115   Yes    1.6256  52.16308 19.73949
## 4 123        NA First born  36     69    190   Not    1.7526  86.18248 28.05778</code></pre>
<p>De la salida anterior vemos la nueva base de datos con las tres nuevas variables creadas con <code>mutate</code>.</p>
</div>
<div id="tablas-de-frecuencia" class="section level2 hasAnchor" number="14.6">
<h2><span class="header-section-number">14.6</span> Tablas de frecuencia<a href="estadística-descriptiva-con-dplyr.html#tablas-de-frecuencia" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vamos a una la variable de clasificación según peso. Recien nacidos con pesos inferiores a 100 onzas son considerados livianos, aquellos con pesos entre 100 (inclusive) y 140 son aceptables y con pesos de 140 o más se consideran sanos.</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="estadística-descriptiva-con-dplyr.html#cb470-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">clasi =</span> <span class="fu">cut</span>(bwt, </span>
<span id="cb470-2"><a href="estadística-descriptiva-con-dplyr.html#cb470-2" tabindex="-1"></a>                         <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">100</span>, <span class="dv">140</span>, <span class="cn">Inf</span>),</span>
<span id="cb470-3"><a href="estadística-descriptiva-con-dplyr.html#cb470-3" tabindex="-1"></a>                         <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Liviano&quot;</span>,<span class="st">&quot;Aceptable&quot;</span>,<span class="st">&quot;Sano&quot;</span>),</span>
<span id="cb470-4"><a href="estadística-descriptiva-con-dplyr.html#cb470-4" tabindex="-1"></a>                         <span class="at">include.lowest =</span> <span class="cn">TRUE</span>)) <span class="ot">-&gt;</span> dt</span></code></pre></div>
<p>Tabla de frecuencia absoluta para clasificación.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="estadística-descriptiva-con-dplyr.html#cb471-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(clasi) <span class="sc">|&gt;</span> </span>
<span id="cb471-2"><a href="estadística-descriptiva-con-dplyr.html#cb471-2" tabindex="-1"></a>  <span class="fu">table</span>()</span></code></pre></div>
<pre><code>## 
##   Liviano Aceptable      Sano 
##       174       917       145</code></pre>
<p>Tabla de frecuencia relativa para clasificación.</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="estadística-descriptiva-con-dplyr.html#cb473-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">pull</span>(clasi) <span class="sc">|&gt;</span> </span>
<span id="cb473-2"><a href="estadística-descriptiva-con-dplyr.html#cb473-2" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span> </span>
<span id="cb473-3"><a href="estadística-descriptiva-con-dplyr.html#cb473-3" tabindex="-1"></a>  <span class="fu">prop.table</span>() <span class="sc">|&gt;</span> </span>
<span id="cb473-4"><a href="estadística-descriptiva-con-dplyr.html#cb473-4" tabindex="-1"></a>  <span class="fu">round</span>(<span class="at">digits=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## 
##   Liviano Aceptable      Sano 
##    0.1408    0.7419    0.1173</code></pre>
<p>Tabla de frecuencia absoluta para fumar y clasificación.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="estadística-descriptiva-con-dplyr.html#cb475-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">select</span>(smoke, clasi) <span class="sc">|&gt;</span> </span>
<span id="cb475-2"><a href="estadística-descriptiva-con-dplyr.html#cb475-2" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span> </span>
<span id="cb475-3"><a href="estadística-descriptiva-con-dplyr.html#cb475-3" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span></code></pre></div>
<pre><code>##      clasi
## smoke Liviano Aceptable Sano  Sum
##   Not      62       581   99  742
##   Yes     111       331   42  484
##   Sum     173       912  141 1226</code></pre>
<p>Tabla de frecuencia relativa para fumar y clasificación.</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="estadística-descriptiva-con-dplyr.html#cb477-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">select</span>(smoke, clasi) <span class="sc">|&gt;</span> </span>
<span id="cb477-2"><a href="estadística-descriptiva-con-dplyr.html#cb477-2" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span> </span>
<span id="cb477-3"><a href="estadística-descriptiva-con-dplyr.html#cb477-3" tabindex="-1"></a>  <span class="fu">prop.table</span>()</span></code></pre></div>
<pre><code>##      clasi
## smoke    Liviano  Aceptable       Sano
##   Not 0.05057096 0.47389886 0.08075041
##   Yes 0.09053834 0.26998369 0.03425775</code></pre>
<p>Tabla de frecuencia relativa por <strong>columnas</strong> para fumar y clasificación.</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="estadística-descriptiva-con-dplyr.html#cb479-1" tabindex="-1"></a>dt <span class="sc">|&gt;</span> <span class="fu">select</span>(smoke, clasi) <span class="sc">|&gt;</span> </span>
<span id="cb479-2"><a href="estadística-descriptiva-con-dplyr.html#cb479-2" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span> </span>
<span id="cb479-3"><a href="estadística-descriptiva-con-dplyr.html#cb479-3" tabindex="-1"></a>  <span class="fu">prop.table</span>(<span class="at">margin=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##      clasi
## smoke   Liviano Aceptable      Sano
##   Not 0.3583815 0.6370614 0.7021277
##   Yes 0.6416185 0.3629386 0.2978723</code></pre>
</div>
<div id="gráficos" class="section level2 hasAnchor" number="14.7">
<h2><span class="header-section-number">14.7</span> Gráficos<a href="estadística-descriptiva-con-dplyr.html#gráficos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección se mostrará como crear algunos gráficos básicos. Para más detalles de como construir otros gráficos se recomienda consultar el libro <a href="https://fhernanb.github.io/Graficos-con-R/">Gráficos con R</a>.</p>
<p>Boxplot para el peso de los bebés.</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="estadística-descriptiva-con-dplyr.html#cb481-1" tabindex="-1"></a><span class="fu">boxplot</span>(dt<span class="sc">$</span>bwt, <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&quot;darkorchid1&quot;</span>, </span>
<span id="cb481-2"><a href="estadística-descriptiva-con-dplyr.html#cb481-2" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Peso del bebe (onzas)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip01"></span>
<img src="Manual_de_R_files/figure-html/analDescrip01-1.png" alt="Boxplot para el peso de los bebés." width="960" />
<p class="caption">
Figure 14.1: Boxplot para el peso de los bebés.
</p>
</div>
<p>Boxplot horizontal para el peso de los bebés.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="estadística-descriptiva-con-dplyr.html#cb482-1" tabindex="-1"></a><span class="fu">boxplot</span>(dt<span class="sc">$</span>bwt, <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&quot;darkseagreen2&quot;</span>,</span>
<span id="cb482-2"><a href="estadística-descriptiva-con-dplyr.html#cb482-2" tabindex="-1"></a>        <span class="at">horizontal=</span><span class="cn">TRUE</span>,</span>
<span id="cb482-3"><a href="estadística-descriptiva-con-dplyr.html#cb482-3" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;Peso del bebe (onzas)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip02"></span>
<img src="Manual_de_R_files/figure-html/analDescrip02-1.png" alt="Boxplot horizontal para el peso de los bebés." width="960" />
<p class="caption">
Figure 14.2: Boxplot horizontal para el peso de los bebés.
</p>
</div>
<p>Boxplot para el peso de los bebés diferenciando por la variable smoke.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="estadística-descriptiva-con-dplyr.html#cb483-1" tabindex="-1"></a><span class="fu">boxplot</span>(dt<span class="sc">$</span>bwt <span class="sc">~</span> dt<span class="sc">$</span>smoke, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip03"></span>
<img src="Manual_de_R_files/figure-html/analDescrip03-1.png" alt="Boxplot para el peso diferenciando por fumar." width="960" />
<p class="caption">
Figure 14.3: Boxplot para el peso diferenciando por fumar.
</p>
</div>
<p>Editando el boxplot para obtener una mejor apariencia.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="estadística-descriptiva-con-dplyr.html#cb484-1" tabindex="-1"></a><span class="fu">boxplot</span>(dt<span class="sc">$</span>bwt <span class="sc">~</span> dt<span class="sc">$</span>smoke, <span class="at">las=</span><span class="dv">1</span>, </span>
<span id="cb484-2"><a href="estadística-descriptiva-con-dplyr.html#cb484-2" tabindex="-1"></a>        <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;dodgerblue&quot;</span>, <span class="st">&quot;hotpink2&quot;</span>),</span>
<span id="cb484-3"><a href="estadística-descriptiva-con-dplyr.html#cb484-3" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&#39;Babies weight given smoke status&#39;</span>,</span>
<span id="cb484-4"><a href="estadística-descriptiva-con-dplyr.html#cb484-4" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&#39;Does the mother smoke?&#39;</span>,</span>
<span id="cb484-5"><a href="estadística-descriptiva-con-dplyr.html#cb484-5" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&#39;Weight (ounces)&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip04"></span>
<img src="Manual_de_R_files/figure-html/analDescrip04-1.png" alt="Boxplot mejorado para el peso diferenciando por fumar." width="960" />
<p class="caption">
Figure 14.4: Boxplot mejorado para el peso diferenciando por fumar.
</p>
</div>
<p>¿Como cambiar Not y Yes de smoke para colocar el gráfico en español?</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="estadística-descriptiva-con-dplyr.html#cb485-1" tabindex="-1"></a>dt<span class="sc">$</span>fuma <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="st">&#39;Not&#39;</span>, <span class="st">&#39;No&#39;</span>, <span class="st">&#39;Si&#39;</span>)</span></code></pre></div>
<p>Boxplot en español</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="estadística-descriptiva-con-dplyr.html#cb486-1" tabindex="-1"></a><span class="fu">boxplot</span>(dt<span class="sc">$</span>bwt <span class="sc">~</span> dt<span class="sc">$</span>fuma, <span class="at">las=</span><span class="dv">1</span>,</span>
<span id="cb486-2"><a href="estadística-descriptiva-con-dplyr.html#cb486-2" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&#39;¿Fuma la madre?&#39;</span>,</span>
<span id="cb486-3"><a href="estadística-descriptiva-con-dplyr.html#cb486-3" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&#39;Peso del bebe (onzas)&#39;</span>, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Warning in (function (z, notch = FALSE, width = NULL, varwidth = FALSE, :
## Duplicated argument las = 1 is disregarded</code></pre>
<div class="figure"><span style="display:block;" id="fig:analDescrip05"></span>
<img src="Manual_de_R_files/figure-html/analDescrip05-1.png" alt="Boxplot para el peso de los bebés en español." width="960" />
<p class="caption">
Figure 14.5: Boxplot para el peso de los bebés en español.
</p>
</div>
<p>¿Cual es la relación entre peso del bebe y de la madre?</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="estadística-descriptiva-con-dplyr.html#cb488-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>dt<span class="sc">$</span>weight, <span class="at">y=</span>dt<span class="sc">$</span>bwt,</span>
<span id="cb488-2"><a href="estadística-descriptiva-con-dplyr.html#cb488-2" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Peso de la madre (libras)&#39;</span>,</span>
<span id="cb488-3"><a href="estadística-descriptiva-con-dplyr.html#cb488-3" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;Peso del bebe (onzas)&#39;</span>, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip06"></span>
<img src="Manual_de_R_files/figure-html/analDescrip06-1.png" alt="Diagrama de dispersión para peso del bebé versus peso de la madre." width="960" />
<p class="caption">
Figure 14.6: Diagrama de dispersión para peso del bebé versus peso de la madre.
</p>
</div>
<p>Diagrama de dispersión entre pesos diferenciando por fumar</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="estadística-descriptiva-con-dplyr.html#cb489-1" tabindex="-1"></a>dt2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(dt)</span>
<span id="cb489-2"><a href="estadística-descriptiva-con-dplyr.html#cb489-2" tabindex="-1"></a></span>
<span id="cb489-3"><a href="estadística-descriptiva-con-dplyr.html#cb489-3" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>dt2<span class="sc">$</span>weight, <span class="at">y=</span>dt2<span class="sc">$</span>bwt, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">las=</span><span class="dv">1</span>,</span>
<span id="cb489-4"><a href="estadística-descriptiva-con-dplyr.html#cb489-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;Peso de la madre (libras)&#39;</span>,</span>
<span id="cb489-5"><a href="estadística-descriptiva-con-dplyr.html#cb489-5" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;Peso del bebe (onzas)&#39;</span>,</span>
<span id="cb489-6"><a href="estadística-descriptiva-con-dplyr.html#cb489-6" tabindex="-1"></a>     <span class="at">col=</span><span class="fu">as.factor</span>(dt2<span class="sc">$</span>smoke))</span>
<span id="cb489-7"><a href="estadística-descriptiva-con-dplyr.html#cb489-7" tabindex="-1"></a></span>
<span id="cb489-8"><a href="estadística-descriptiva-con-dplyr.html#cb489-8" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&#39;bottomright&#39;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&#39;No&#39;</span>, <span class="st">&#39;Si&#39;</span>),</span>
<span id="cb489-9"><a href="estadística-descriptiva-con-dplyr.html#cb489-9" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">20</span>, <span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip07"></span>
<img src="Manual_de_R_files/figure-html/analDescrip07-1.png" alt="Diagrama de dispersión para peso del bebé versus peso de la madre diferenciando por fumar." width="960" />
<p class="caption">
Figure 14.7: Diagrama de dispersión para peso del bebé versus peso de la madre diferenciando por fumar.
</p>
</div>
<p>Para ver la relación entre el peso de la madre y la edad de la madre.</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="estadística-descriptiva-con-dplyr.html#cb490-1" tabindex="-1"></a><span class="fu">plot</span>(dt<span class="sc">$</span>age, dt<span class="sc">$</span>weight, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">col=</span><span class="st">&quot;tomato&quot;</span>, <span class="at">las=</span><span class="dv">1</span>,</span>
<span id="cb490-2"><a href="estadística-descriptiva-con-dplyr.html#cb490-2" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Edad de la madre&quot;</span>,</span>
<span id="cb490-3"><a href="estadística-descriptiva-con-dplyr.html#cb490-3" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Peso de la madre&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:analDescrip08"></span>
<img src="Manual_de_R_files/figure-html/analDescrip08-1.png" alt="Diagrama de dispersión del peso de la madre versus su edad." width="960" />
<p class="caption">
Figure 14.8: Diagrama de dispersión del peso de la madre versus su edad.
</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correl.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="variables-aleatorias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/Manual-de-R/edit/master/15_est_descrip_dplyr.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Manual_de_R.pdf", "Manual_de_R.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
