<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 15 Verosimilitud | Manual de R</title>
  <meta name="description" content="This is an R manual.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 15 Verosimilitud | Manual de R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/portada.png" />
  <meta property="og:description" content="This is an R manual." />
  <meta name="github-repo" content="fhernanb/Manual-de-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Verosimilitud | Manual de R" />
  
  <meta name="twitter:description" content="This is an R manual." />
  <meta name="twitter:image" content="images/portada.png" />



<meta name="date" content="2019-03-27">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="continuas.html">
<link rel="next" href="normalidad.html">
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="css\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Manual de R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#informacion-del-software-y-convenciones"><i class="fa fa-check"></i>Información del software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#agradecimientos"><i class="fa fa-check"></i>Agradecimientos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-los-autores.html"><a href="sobre-los-autores.html"><i class="fa fa-check"></i>Sobre los autores</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="objetos.html"><a href="objetos.html"><i class="fa fa-check"></i><b>2</b> Tipos de objetos</a><ul>
<li class="chapter" data-level="2.1" data-path="objetos.html"><a href="objetos.html#vectores"><i class="fa fa-check"></i><b>2.1</b> Vectores  </a><ul>
<li class="chapter" data-level="2.1.1" data-path="objetos.html"><a href="objetos.html#como-extraer-elementos-de-un-vector"><i class="fa fa-check"></i><b>2.1.1</b> ¿Cómo extraer elementos de un vector?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="objetos.html"><a href="objetos.html#matrices"><i class="fa fa-check"></i><b>2.2</b> Matrices</a><ul>
<li class="chapter" data-level="2.2.1" data-path="objetos.html"><a href="objetos.html#como-extraer-elementos-de-una-matriz"><i class="fa fa-check"></i><b>2.2.1</b> ¿Cómo extraer elementos de una matriz?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="objetos.html"><a href="objetos.html#arreglos"><i class="fa fa-check"></i><b>2.3</b> Arreglos  </a><ul>
<li class="chapter" data-level="2.3.1" data-path="objetos.html"><a href="objetos.html#como-extraer-elementos-de-un-arreglo"><i class="fa fa-check"></i><b>2.3.1</b> ¿Cómo extraer elementos de un arreglo?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="objetos.html"><a href="objetos.html#marco-de-datos"><i class="fa fa-check"></i><b>2.4</b> Marco de datos  </a><ul>
<li class="chapter" data-level="2.4.1" data-path="objetos.html"><a href="objetos.html#como-extraer-elementos-de-un-marco-de-datos"><i class="fa fa-check"></i><b>2.4.1</b> ¿Cómo extraer elementos de un marco de datos?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="2.4.2" data-path="objetos.html"><a href="objetos.html#como-extraer-subconjuntos-de-un-marco-de-datos"><i class="fa fa-check"></i><b>2.4.2</b> ¿Cómo extraer subconjuntos de un marco de datos? </a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplos"><i class="fa fa-check"></i>Ejemplos</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="objetos.html"><a href="objetos.html#listas"><i class="fa fa-check"></i><b>2.5</b> Listas  </a><ul>
<li class="chapter" data-level="2.5.1" data-path="objetos.html"><a href="objetos.html#como-extraer-elementos-de-una-lista"><i class="fa fa-check"></i><b>2.5.1</b> ¿Cómo extraer elementos de una lista?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplos-1"><i class="fa fa-check"></i>Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejercicios"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estilo.html"><a href="estilo.html"><i class="fa fa-check"></i><b>3</b> Guía de estilo</a><ul>
<li class="chapter" data-level="3.1" data-path="estilo.html"><a href="estilo.html#nombres-de-los-archivos"><i class="fa fa-check"></i><b>3.1</b> Nombres de los archivos</a></li>
<li class="chapter" data-level="3.2" data-path="estilo.html"><a href="estilo.html#nombres-de-los-objetos"><i class="fa fa-check"></i><b>3.2</b> Nombres de los objetos</a></li>
<li class="chapter" data-level="3.3" data-path="estilo.html"><a href="estilo.html#longitud-de-una-linea-de-codigo"><i class="fa fa-check"></i><b>3.3</b> Longitud de una línea de código</a></li>
<li class="chapter" data-level="3.4" data-path="estilo.html"><a href="estilo.html#espacios"><i class="fa fa-check"></i><b>3.4</b> Espacios</a></li>
<li class="chapter" data-level="3.5" data-path="estilo.html"><a href="estilo.html#asignacion"><i class="fa fa-check"></i><b>3.5</b> Asignación</a></li>
<li class="chapter" data-level="3.6" data-path="estilo.html"><a href="estilo.html#punto-y-coma"><i class="fa fa-check"></i><b>3.6</b> Punto y coma</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="funbas.html"><a href="funbas.html"><i class="fa fa-check"></i><b>4</b> Funciones básicas de R</a><ul>
<li class="chapter" data-level="4.1" data-path="funbas.html"><a href="funbas.html#que-es-una-funcion-de-r"><i class="fa fa-check"></i><b>4.1</b> ¿Qué es una función de R?  </a></li>
<li class="chapter" data-level="4.2" data-path="funbas.html"><a href="funbas.html#operadores-de-asignacion"><i class="fa fa-check"></i><b>4.2</b> Operadores de asignación </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="funbas.html"><a href="funbas.html#operaciones-basicas"><i class="fa fa-check"></i><b>4.3</b> Operaciones básicas </a></li>
<li class="chapter" data-level="4.4" data-path="funbas.html"><a href="funbas.html#pruebas-logicas"><i class="fa fa-check"></i><b>4.4</b> Pruebas lógicas </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="funbas.html"><a href="funbas.html#operadores-logicos"><i class="fa fa-check"></i><b>4.5</b> Operadores lógicos </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="funbas.html"><a href="funbas.html#funciones-sobre-vectores"><i class="fa fa-check"></i><b>4.6</b> Funciones sobre vectores</a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="funbas.html"><a href="funbas.html#funciones-matematicas"><i class="fa fa-check"></i><b>4.7</b> Funciones matemáticas</a></li>
<li class="chapter" data-level="4.8" data-path="funbas.html"><a href="funbas.html#funcion-seq"><i class="fa fa-check"></i><b>4.8</b> Función <code>seq</code>  </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="funbas.html"><a href="funbas.html#funcion-rep"><i class="fa fa-check"></i><b>4.9</b> Función <code>rep</code>  </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="funbas.html"><a href="funbas.html#funciones-round-ceiling-floor-y-trunc"><i class="fa fa-check"></i><b>4.10</b> Funciones <code>round</code>, <code>ceiling</code>, <code>floor</code> y <code>trunc</code>    </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="funbas.html"><a href="funbas.html#funciones-sort-y-rank"><i class="fa fa-check"></i><b>4.11</b> Funciones <code>sort</code> y <code>rank</code>    </a><ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-14"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejercicios-1"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bucles.html"><a href="bucles.html"><i class="fa fa-check"></i><b>5</b> Instrucciones de control</a><ul>
<li class="chapter" data-level="5.1" data-path="bucles.html"><a href="bucles.html#instruccion-if"><i class="fa fa-check"></i><b>5.1</b> Instrucción <code>if</code> </a><ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-15"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bucles.html"><a href="bucles.html#instruccion-if-else"><i class="fa fa-check"></i><b>5.2</b> Instrucción <code>if</code> <code>else</code> </a></li>
<li class="chapter" data-level="5.3" data-path="bucles.html"><a href="bucles.html#instruccion-ifelse"><i class="fa fa-check"></i><b>5.3</b> Instrucción <code>ifelse</code> </a><ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-16"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bucles.html"><a href="bucles.html#instruccion-for"><i class="fa fa-check"></i><b>5.4</b> Instrucción <code>for</code> </a><ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-17"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="bucles.html"><a href="bucles.html#instruccion-while"><i class="fa fa-check"></i><b>5.5</b> Instrucción <code>while</code> </a><ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-18"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="bucles.html"><a href="bucles.html#instruccion-repeat"><i class="fa fa-check"></i><b>5.6</b> Instrucción <code>repeat</code> </a><ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-19"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="creafun.html"><a href="creafun.html"><i class="fa fa-check"></i><b>6</b> Creación de funciones en R</a><ul>
<li class="chapter" data-level="6.1" data-path="creafun.html"><a href="creafun.html#funcion-en-r"><i class="fa fa-check"></i><b>6.1</b> Función en R </a></li>
<li class="chapter" data-level="6.2" data-path="creafun.html"><a href="creafun.html#partes-de-una-funcion-en-r"><i class="fa fa-check"></i><b>6.2</b> Partes de una función en R </a><ul>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-20"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-21"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-22"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-23"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejercicios-2"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>7</b> Lectura de bases de datos</a><ul>
<li class="chapter" data-level="7.1" data-path="read.html"><a href="read.html#en-que-formato-almacenar-una-base-de-datos"><i class="fa fa-check"></i><b>7.1</b> ¿En qué formato almacenar una base de datos?  </a><ul>
<li class="chapter" data-level="7.1.1" data-path="read.html"><a href="read.html#almacenamiento-de-informacion-en-excel"><i class="fa fa-check"></i><b>7.1.1</b> Almacenamiento de información en Excel </a></li>
<li class="chapter" data-level="7.1.2" data-path="read.html"><a href="read.html#almacenamiento-de-informacion-en-bloc-de-notas"><i class="fa fa-check"></i><b>7.1.2</b> Almacenamiento de información en bloc de notas </a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="read.html"><a href="read.html#funcion-read.table"><i class="fa fa-check"></i><b>7.2</b> Función <code>read.table</code> </a><ul>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-24"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-25"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="read.html"><a href="read.html#lectura-de-bases-de-datos-en-excel"><i class="fa fa-check"></i><b>7.3</b> Lectura de bases de datos en Excel</a><ul>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-26"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejercicios-3"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tablas.html"><a href="tablas.html"><i class="fa fa-check"></i><b>8</b> Tablas de frecuencia</a><ul>
<li class="chapter" data-level="8.1" data-path="tablas.html"><a href="tablas.html#tabla-de-contingencia-con-table"><i class="fa fa-check"></i><b>8.1</b> Tabla de contingencia con <code>table</code> </a><ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-de-una-via"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia de una vía</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-de-dos-vias"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia de dos vías</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tablas.html"><a href="tablas.html#funcion-prop.table"><i class="fa fa-check"></i><b>8.2</b> Función <code>prop.table</code> </a><ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-relativa-de-una-via"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia relativa de una vía</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-relativa-de-dos-vias"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia relativa de dos vías</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="tablas.html"><a href="tablas.html#funcion-addmargins"><i class="fa fa-check"></i><b>8.3</b> Función <code>addmargins</code> </a><ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-27"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="tablas.html"><a href="tablas.html#funcion-hist"><i class="fa fa-check"></i><b>8.4</b> Función <code>hist</code> </a><ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-28"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-29"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejercicios-4"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="central.html"><a href="central.html"><i class="fa fa-check"></i><b>9</b> Medidas de tendencia central</a><ul>
<li class="chapter" data-level="9.1" data-path="central.html"><a href="central.html#media"><i class="fa fa-check"></i><b>9.1</b> Media  </a><ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-30"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-31"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-32"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="central.html"><a href="central.html#mediana"><i class="fa fa-check"></i><b>9.2</b> Mediana  </a><ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-33"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="central.html"><a href="central.html#moda"><i class="fa fa-check"></i><b>9.3</b> Moda </a><ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-34"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="varia.html"><a href="varia.html"><i class="fa fa-check"></i><b>10</b> Medidas de variabilidad</a><ul>
<li class="chapter" data-level="10.1" data-path="varia.html"><a href="varia.html#rango"><i class="fa fa-check"></i><b>10.1</b> Rango  </a><ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-35"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-36"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="varia.html"><a href="varia.html#desviacion-estandar-muestral-s"><i class="fa fa-check"></i><b>10.2</b> Desviación estándar muestral (<span class="math inline">\(S\)</span>)  </a><ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-37"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-38"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="varia.html"><a href="varia.html#varianza-muestral-s2"><i class="fa fa-check"></i><b>10.3</b> Varianza muestral (<span class="math inline">\(S^2\)</span>)  </a><ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-39"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-40"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="varia.html"><a href="varia.html#coeficiente-de-variacion-cv"><i class="fa fa-check"></i><b>10.4</b> Coeficiente de variación (<span class="math inline">\(CV\)</span>) </a><ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-41"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="posi.html"><a href="posi.html"><i class="fa fa-check"></i><b>11</b> Medidas de posición</a><ul>
<li class="chapter" data-level="11.1" data-path="posi.html"><a href="posi.html#cuantiles"><i class="fa fa-check"></i><b>11.1</b> Cuantiles     </a><ul>
<li class="chapter" data-level="" data-path="posi.html"><a href="posi.html#ejemplo-42"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>12</b> Medidas de correlación</a><ul>
<li class="chapter" data-level="12.1" data-path="correl.html"><a href="correl.html#funcion-cor"><i class="fa fa-check"></i><b>12.1</b> Función <code>cor</code>  </a><ul>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-43"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-44"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-45"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-46"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejercicios-5"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="discretas.html"><a href="discretas.html"><i class="fa fa-check"></i><b>13</b> Distribuciones discretas</a><ul>
<li class="chapter" data-level="13.1" data-path="discretas.html"><a href="discretas.html#funciones-disponibles-para-distribuciones-discretas"><i class="fa fa-check"></i><b>13.1</b> Funciones disponibles para distribuciones discretas </a><ul>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-binomial"><i class="fa fa-check"></i>Ejemplo binomial</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-geometrica"><i class="fa fa-check"></i>Ejemplo geométrica</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-binomial-negativa"><i class="fa fa-check"></i>Ejemplo binomial negativa</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-hipergeometrica"><i class="fa fa-check"></i>Ejemplo hipergeométrica</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-poisson"><i class="fa fa-check"></i>Ejemplo Poisson</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="discretas.html"><a href="discretas.html#distribuciones-discretas-generales"><i class="fa fa-check"></i><b>13.2</b> Distribuciones discretas generales</a><ul>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-47"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="continuas.html"><a href="continuas.html"><i class="fa fa-check"></i><b>14</b> Distribuciones continuas</a><ul>
<li class="chapter" data-level="14.1" data-path="continuas.html"><a href="continuas.html#funciones-disponibles-para-distribuciones-continuas"><i class="fa fa-check"></i><b>14.1</b> Funciones disponibles para distribuciones continuas</a><ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-beta"><i class="fa fa-check"></i>Ejemplo beta</a></li>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-normal-estandar"><i class="fa fa-check"></i>Ejemplo normal estándar</a></li>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-normal-general"><i class="fa fa-check"></i>Ejemplo normal general</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="continuas.html"><a href="continuas.html#distribuciones-continuas-generales"><i class="fa fa-check"></i><b>14.2</b> Distribuciones continuas generales</a><ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-48"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="loglik.html"><a href="loglik.html"><i class="fa fa-check"></i><b>15</b> Verosimilitud</a><ul>
<li class="chapter" data-level="15.1" data-path="loglik.html"><a href="loglik.html#funcion-de-verosimilitud"><i class="fa fa-check"></i><b>15.1</b> Función de verosimilitud</a></li>
<li class="chapter" data-level="15.2" data-path="loglik.html"><a href="loglik.html#funcion-de-log-verosimilitud"><i class="fa fa-check"></i><b>15.2</b> Función de log-verosimilitud</a></li>
<li class="chapter" data-level="15.3" data-path="loglik.html"><a href="loglik.html#metodo-de-maxima-verosimilitud-para-estimar-parametros"><i class="fa fa-check"></i><b>15.3</b> Método de máxima verosimilitud para estimar parámetros</a><ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-49"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-50"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-51"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-52"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="loglik.html"><a href="loglik.html#score-e-informacion-de-fisher"><i class="fa fa-check"></i><b>15.4</b> Score e Información de Fisher</a><ul>
<li class="chapter" data-level="15.4.1" data-path="loglik.html"><a href="loglik.html#score-e-informacion-de-fisher-en-el-caso-univariado."><i class="fa fa-check"></i><b>15.4.1</b> Score e Información de Fisher en el caso univariado.</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-53"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="loglik.html"><a href="loglik.html#metodo-de-maxima-verosimilitud-para-estimar-parametros-en-modelos-de-regresion"><i class="fa fa-check"></i><b>15.5</b> Método de máxima verosimilitud para estimar parámetros en modelos de regresión</a><ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-54"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejercicios-6"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="normalidad.html"><a href="normalidad.html"><i class="fa fa-check"></i><b>16</b> Estudiando la normalidad</a><ul>
<li class="chapter" data-level="16.1" data-path="normalidad.html"><a href="normalidad.html#consideraciones-iniciales"><i class="fa fa-check"></i><b>16.1</b> Consideraciones iniciales</a></li>
<li class="chapter" data-level="16.2" data-path="normalidad.html"><a href="normalidad.html#histograma-y-densidad"><i class="fa fa-check"></i><b>16.2</b> Histograma y densidad</a><ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-densidad-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo densidad con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-densidad-del-peso-corporal"><i class="fa fa-check"></i>Ejemplo densidad del peso corporal</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="normalidad.html"><a href="normalidad.html#graficos-cuantil-cuantil"><i class="fa fa-check"></i><b>16.3</b> Gráficos cuantil cuantil   </a><ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-1-qqplot-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo 1 QQplot con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-2-qqplot-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo 2 QQplot con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-qqplot-para-peso-corporal"><i class="fa fa-check"></i>Ejemplo QQplot para peso corporal</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-qqplot-con-bandas"><i class="fa fa-check"></i>Ejemplo QQplot con bandas</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="normalidad.html"><a href="normalidad.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>16.4</b> Pruebas de normalidad</a><ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-normalidad-para-peso-corporal"><i class="fa fa-check"></i>Ejemplo normalidad para peso corporal</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejercicios-7"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ic.html"><a href="ic.html"><i class="fa fa-check"></i><b>17</b> Intervalos de confianza</a><ul>
<li class="chapter" data-level="17.1" data-path="ic.html"><a href="ic.html#funcion-t.test"><i class="fa fa-check"></i><b>17.1</b> Función <code>t.test</code></a><ul>
<li class="chapter" data-level="17.1.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-media-mu"><i class="fa fa-check"></i><b>17.1.1</b> Intervalo de confianza bilateral para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-55"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="17.1.2" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-medias-mu_1-mu_2-de-muestras-independientes"><i class="fa fa-check"></i><b>17.1.2</b> Intervalo de confianza bilateral para la diferencia de medias (<span class="math inline">\(\mu_1-\mu_2\)</span>) de muestras independientes</a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-56"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="17.1.3" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-medias-mu_1-mu_2-de-muestras-dependientes-o-pareadas"><i class="fa fa-check"></i><b>17.1.3</b> Intervalo de confianza bilateral para la diferencia de medias (<span class="math inline">\(\mu_1-\mu_2\)</span>) de muestras dependientes o pareadas</a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-57"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="17.1.4" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-unilateral-para-la-media-mu"><i class="fa fa-check"></i><b>17.1.4</b> Intervalo de confianza unilateral para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-58"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="ic.html"><a href="ic.html#funcion-var.test"><i class="fa fa-check"></i><b>17.2</b> Función <code>var.test</code></a><ul>
<li class="chapter" data-level="17.2.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-varianza-sigma2"><i class="fa fa-check"></i><b>17.2.1</b> Intervalo de confianza bilateral para la varianza <span class="math inline">\(\sigma^2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-59"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="17.2.2" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-razon-de-varianzas-sigma_12-sigma_22"><i class="fa fa-check"></i><b>17.2.2</b> Intervalo de confianza bilateral para la razón de varianzas <span class="math inline">\(\sigma_1^2 / \sigma_2^2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-60"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="ic.html"><a href="ic.html#funcion-prop.test"><i class="fa fa-check"></i><b>17.3</b> Función <code>prop.test</code></a><ul>
<li class="chapter" data-level="17.3.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-proporcion-p"><i class="fa fa-check"></i><b>17.3.1</b> Intervalo de confianza bilateral para la proporción <span class="math inline">\(p\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-61"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="17.3.2" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-proporciones-p_1---p_2"><i class="fa fa-check"></i><b>17.3.2</b> Intervalo de confianza bilateral para la diferencia de proporciones <span class="math inline">\(p_1 - p_2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-62"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>18</b> Prueba de hipótesis</a><ul>
<li class="chapter" data-level="18.1" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-mu-de-una-poblacion-normal"><i class="fa fa-check"></i><b>18.1</b> Prueba de hipótesis para <span class="math inline">\(\mu\)</span> de una población normal</a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-63"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-mu-con-muestras-grandes"><i class="fa fa-check"></i><b>18.2</b> Prueba de hipótesis para <span class="math inline">\(\mu\)</span> con muestras grandes</a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-64"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-la-proporcion-p"><i class="fa fa-check"></i><b>18.3</b> Prueba de hipótesis para la proporción <span class="math inline">\(p\)</span></a><ul>
<li class="chapter" data-level="18.3.1" data-path="ph.html"><a href="ph.html#prueba-de-wald"><i class="fa fa-check"></i><b>18.3.1</b> Prueba de Wald</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-65"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="18.3.2" data-path="ph.html"><a href="ph.html#prueba-chi2-de-pearson"><i class="fa fa-check"></i><b>18.3.2</b> Prueba <span class="math inline">\(\Chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-66"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="18.3.3" data-path="ph.html"><a href="ph.html#prueba-binomial-exacta"><i class="fa fa-check"></i><b>18.3.3</b> Prueba binomial exacta</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-67"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-la-varianza-sigma2-de-una-poblacion-normal"><i class="fa fa-check"></i><b>18.4</b> Prueba de hipótesis para la varianza <span class="math inline">\(\sigma^2\)</span> de una población normal</a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-68"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-el-cociente-de-varianzas-sigma_12-sigma_22"><i class="fa fa-check"></i><b>18.5</b> Prueba de hipótesis para el cociente de varianzas <span class="math inline">\(\sigma_1^2 / \sigma_2^2\)</span></a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-69"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-70"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-iguales"><i class="fa fa-check"></i><b>18.6</b> Prueba de hipótesis para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> con varianzas iguales</a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-71"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-diferentes"><i class="fa fa-check"></i><b>18.7</b> Prueba de hipótesis para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> con varianzas diferentes</a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-72"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.8" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-la-diferencia-de-proporciones-p_1---p_2"><i class="fa fa-check"></i><b>18.8</b> Prueba de hipótesis para la diferencia de proporciones <span class="math inline">\(p_1 - p_2\)</span></a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-73"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.9" data-path="ph.html"><a href="ph.html#prueba-de-hipotesis-para-la-diferencia-de-medias-pareadas"><i class="fa fa-check"></i><b>18.9</b> Prueba de hipótesis para la diferencia de medias pareadas</a><ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-74"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="aproxint.html"><a href="aproxint.html"><i class="fa fa-check"></i><b>19</b> Aproximación de integrales</a><ul>
<li class="chapter" data-level="19.1" data-path="aproxint.html"><a href="aproxint.html#aproximacion-de-laplace-unidimensional"><i class="fa fa-check"></i><b>19.1</b> Aproximación de Laplace unidimensional</a><ul>
<li class="chapter" data-level="" data-path="aproxint.html"><a href="aproxint.html#ejemplo-75"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="20" data-path="curio.html"><a href="curio.html"><i class="fa fa-check"></i><b>20</b> Curiosidades</a><ul>
<li class="chapter" data-level="20.1" data-path="curio.html"><a href="curio.html#como-verificar-si-un-paquete-no-esta-instalado-para-instalarlo-de-forma-automatica"><i class="fa fa-check"></i><b>20.1</b> ¿Cómo verificar si un paquete no está instalado para instalarlo de forma automática?</a><ul>
<li class="chapter" data-level="" data-path="curio.html"><a href="curio.html#ejemplo-76"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Manual de R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="loglik" class="section level1">
<h1><span class="header-section-number">Chapter 15</span> Verosimilitud</h1>
<p>En este capítulo se mostrará como usar R para obtener la función de log-verosimilitud y estimadores por el método de máxima verosimilitud.</p>
<div id="funcion-de-verosimilitud" class="section level2">
<h2><span class="header-section-number">15.1</span> Función de verosimilitud</h2>
<p>El concepto de verosimilitud fue propuesto por <span class="citation">Fisher (<a href="#ref-Fisher22">1922</a>)</span> en el contexto de estimación de parámetros. En la Figura <a href="loglik.html#fig:fisher">15.1</a> se muestra una fotografía de Ronald Aylmer Fisher.</p>
<div class="figure" style="text-align: center"><span id="fig:fisher"></span>
<img src="images/Fisher.png" alt="Fotografía de Ronald Aylmer Fisher (1890-1962)." width="40%" />
<p class="caption">
FIGURE 15.1: Fotografía de Ronald Aylmer Fisher (1890-1962).
</p>
</div>

<div class="rmdnote">
Asumiendo un modelo estadístico parametrizado por una cantidad fija y desconocida <span class="math inline">\(\theta\)</span>, la verosimilitud <span class="math inline">\(L(\theta)\)</span> es la probabilidad de los datos observados <span class="math inline">\(x\)</span> como una función de <span class="math inline">\(\theta\)</span> <span class="citation">(Pawitan <a href="#ref-pawitan_2013">2013</a>)</span>. Si la variable de interés es discreta se usa la probabilidad y si es continua se usa la densidad para obtener la verosimilitud.
</div>

<p>La función de verosimilitud para un vector de parámetros <span class="math inline">\(\boldsymbol{\Theta}\)</span> dada una muestra aleatoria <span class="math inline">\(\boldsymbol{x}\)</span> con una distribución asumida se define usualmente como:</p>
<span class="math display" id="eq:lik">\[\begin{equation}
L(\boldsymbol{\Theta} | \boldsymbol{x}) = \prod_{i=1}^{n}  f(x_i | \boldsymbol{\Theta}),
\tag{15.1}
\end{equation}\]</span>
<p>donde <span class="math inline">\(x_i\)</span> representa uno de los elementos de la muestra aleatoria y <span class="math inline">\(f\)</span> es la función de masa/densidad de la distribución de la cual se obtuvo <span class="math inline">\(\boldsymbol{x}\)</span>.</p>
</div>
<div id="funcion-de-log-verosimilitud" class="section level2">
<h2><span class="header-section-number">15.2</span> Función de log-verosimilitud</h2>
<p>La función de log-verosimilitud <span class="math inline">\(l\)</span> se define como el logaritmo de la función de verosimilitud <span class="math inline">\(L\)</span>, es decir</p>
<span class="math display" id="eq:loglik">\[\begin{equation}
l(\boldsymbol{\Theta} | \boldsymbol{x}) = \log L(\boldsymbol{\Theta} | \boldsymbol{x}) = \sum_{i=1}^{n} \log f(x_i | \boldsymbol{\Theta})
\tag{15.2}
\end{equation}\]</span>
</div>
<div id="metodo-de-maxima-verosimilitud-para-estimar-parametros" class="section level2">
<h2><span class="header-section-number">15.3</span> Método de máxima verosimilitud para estimar parámetros</h2>
<p>El método de máxima verosimilitud se usa para estimar los parámetros de una distribución. El objetivo de este método es encontrar los valores de <span class="math inline">\(\boldsymbol{\Theta}\)</span> que maximizan <span class="math inline">\(L\)</span> o <span class="math inline">\(l\)</span> y valores encontrados se representan por <span class="math inline">\(\hat{\boldsymbol{\Theta}}\)</span>.</p>
<div id="ejemplo-49" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>En este ejemplo vamos a considerar la distribución binomial cuya función de masa de probabilidad está dada por:</p>
<p><span class="math display">\[f(x)=P(X=x)=\binom{n}{x} p^x (1-p)^{n-x}, \quad 0&lt;p&lt;1, \quad n \leq 1, 2, \ldots, \quad 0 \leq x \leq n\]</span></p>
<p>Suponga que se tiene el vector <code>rta</code> que corresponde a una muestra aleatoria de una distribución binomial con parámetro <span class="math inline">\(n=5\)</span> conocido.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rta &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>,
         <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>)</code></pre></div>
<ol style="list-style-type: decimal">
<li>Calcular el valor de log-verosimilitud <span class="math inline">\(l\)</span> si asumiendo que <span class="math inline">\(p=0.30\)</span> en la distribución binomial.</li>
</ol>
<p>Para obtener el valor de <span class="math inline">\(l\)</span> en el punto <span class="math inline">\(p=0.30\)</span> se aplica la definición dada en la expresión <a href="loglik.html#eq:loglik">(15.2)</a>. Como el problema trata de una binomial se usa entonces la función de masa <code>dbinom</code> evaluada en la muestra <code>rta</code>, el parámetro <code>size</code> como es conocido se reemplaza por el valor de cinco y en el parámetro <code>prob</code> se cambia por 0.3. Como interesa la función de log-verosimilitud se debe incluir <code>log=TRUE</code>. A continuación el código necesario.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dt">x=</span>rta, <span class="dt">size=</span><span class="dv">5</span>, <span class="dt">prob=</span><span class="fl">0.3</span>, <span class="dt">log=</span><span class="ot">TRUE</span>))</code></pre></div>
<pre><code>## [1] -24.55</code></pre>
<p>Por lo tanto <span class="math inline">\(l(\theta)= -24.55\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Construir una función llamada <code>ll</code> a la cual le ingrese valores del parámetro <span class="math inline">\(p\)</span> de la binomial y que la función entregue el valor de log-verosimilitud.</li>
</ol>
<p>La función solicitada tiene un cuerpo igual al usado en el numeral anterior, a continuación el código necesario para crearla.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ll &lt;-<span class="st"> </span><span class="cf">function</span>(prob) <span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dt">x=</span>rta, <span class="dt">size=</span><span class="dv">5</span>, <span class="dt">prob=</span>prob, <span class="dt">log=</span>T))</code></pre></div>
<p>Vamos a probar la función en dos valores arbitrarios <span class="math inline">\(p=0.15\)</span> y <span class="math inline">\(p=0.80\)</span> que pertenezcan al dominio del parámetro <span class="math inline">\(p\)</span> de la distribución binomial.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ll</span>(<span class="dt">prob=</span><span class="fl">0.15</span>)  <span class="co"># Individual para p=0.15</span></code></pre></div>
<pre><code>## [1] -25.54</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ll</span>(<span class="dt">prob=</span><span class="fl">0.80</span>)  <span class="co"># Individual para p=0.80</span></code></pre></div>
<pre><code>## [1] -98.46</code></pre>
<p>El valor de log-verosimilitud para <span class="math inline">\(p=0.15\)</span> fue de -25.54 mientras que para <span class="math inline">\(p=0.80\)</span> fue de -98.46.</p>
<p>Vamos ahora a chequear si la función <code>ll</code> está vectorizada y para esto usamos el código mostrado a continuación y deberíamos obtener un vector con los valores <code>c(-25.54, -98.56)</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ll</span>(<span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.15</span>, <span class="fl">0.80</span>))</code></pre></div>
<pre><code>## [1] -57.32</code></pre>
<p>No obtuvimos el resultado esperado, eso significa que nuestra función no está vectorizada. Ese problema lo podemos solucionar así:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ll &lt;-<span class="st"> </span><span class="kw">Vectorize</span>(ll)
<span class="kw">ll</span>(<span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.15</span>, <span class="fl">0.80</span>))</code></pre></div>
<pre><code>## [1] -25.54 -98.46</code></pre>
<p>Vemos que ahora que cuando se ingresa un vector a la función <code>ll</code> se obtiene un vector.</p>

<div class="rmdnote">
Necesitamos que la función <code>ll</code> esté vectorizada para poder dibujarla y para poder optimizarla.
</div>

<ol start="3" style="list-style-type: decimal">
<li>Dibujar la curva log-verosimilitud <span class="math inline">\(l\)</span>, en el eje X debe estar el parámetro <span class="math inline">\(p\)</span> del cual depende la función de log-verosimilitud.</li>
</ol>
<p>En la Figura <a href="loglik.html#fig:loglik1">15.2</a> se presenta la curva solicitada.</p>
<div class="figure"><span id="fig:loglik1"></span>
<img src="Manual_de_R_files/figure-html/loglik1-1.png" alt="Función de log-verosimilitud para el ejemplo sobre binomial." width="384" />
<p class="caption">
FIGURE 15.2: Función de log-verosimilitud para el ejemplo sobre binomial.
</p>
</div>
<ol start="4" style="list-style-type: decimal">
<li>Observando la Figura <a href="loglik.html#fig:loglik1">15.2</a>, ¿cuál esl el valor de <span class="math inline">\(p\)</span> que maximiza la función de log-verosimilitud?</li>
</ol>
<p>Al observar la Figura <a href="loglik.html#fig:loglik1">15.2</a> se nota que el valor de <span class="math inline">\(p\)</span> que maximiza la función log-verosimilitud está muy cerca de 0.2.</p>
<ol start="5" style="list-style-type: decimal">
<li>¿Cuál es el valor exacto de <span class="math inline">\(p\)</span> que maximiza la función log-verosimilitud?</li>
</ol>
<p>En  existe la función <code>optimize</code> que sirve para encontrar el valor que <strong>minimiza</strong> una función uniparamétrica en un intervalo dado, sin embargo, aquí interesa es maximimizar la función de log-verosimilitud, por esa razón se construye la función <code>minusll</code> que es el negativo de la función <code>ll</code> para así poder usar <code>optimize</code>. A continuación el código usado. </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minusll &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="op">-</span><span class="kw">ll</span>(x)

<span class="kw">optimize</span>(<span class="dt">f=</span>minusll, <span class="dt">interval=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</code></pre></div>
<pre><code>## $minimum
## [1] 0.23
## 
## $objective
## [1] 23.32</code></pre>
<p>Del resultado anterior se observa que cuando <span class="math inline">\(p=0.23\)</span> el valor máximo de log-verosimilitud es 23.32.</p>
</div>
<div id="ejemplo-50" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que la estatura de una población se puede asumir como una normal <span class="math inline">\(N(170, 25)\)</span>. Suponga también que se genera una muestra aleatoria de 50 observaciones de la población con el objetivo de recuperar los valores de la media y varianza poblacionales a partir de la muestra aleatoria.</p>
<p>La muestra se va a generar con la función <code>rnorm</code> pero antes se fijará una semilla con la intención de que el lector pueda replicar el ejemplo y obtener la misma muestra aleatoria aquí generada, el código para hacerlo es el siguiente.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1235</span>)  <span class="co"># La semilla es 1235</span>
y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n=</span><span class="dv">50</span>, <span class="dt">mean=</span><span class="dv">170</span>, <span class="dt">sd=</span><span class="dv">5</span>)
y[<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>]  <span class="co"># Para ver los primeros siete valores generados</span></code></pre></div>
<pre><code>## [1] 166.5 163.6 174.9 170.6 170.6 178.5 170.2</code></pre>
<ol style="list-style-type: decimal">
<li>Construya la función de log-verosimilitud para los parámetros de la normal dada la muestra aleatoria <code>y</code>.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ll &lt;-<span class="st"> </span><span class="cf">function</span>(param) {
  media &lt;-<span class="st"> </span>param[<span class="dv">1</span>]  <span class="co"># param es el vector de parámetros</span>
  desvi &lt;-<span class="st"> </span>param[<span class="dv">2</span>] 
  <span class="kw">sum</span>(<span class="kw">dnorm</span>(<span class="dt">x=</span>y, <span class="dt">mean=</span>media, <span class="dt">sd=</span>desvi, <span class="dt">log=</span><span class="ot">TRUE</span>))
}</code></pre></div>

<div class="rmdwarning">
Siempre que el interés sea encontrar los valores que maximizan una función de log-verosimilitud, los parámetros de la distribución <strong>deben</strong> ingresar a la función <code>ll</code> como un vector. Esto se debe hacer para poder usar las funciones de búsqueda <code>optim</code> y <code>nlminb</code>.
</div>

<ol start="2" style="list-style-type: decimal">
<li>Dibujar la función de log-verosimilitud.</li>
</ol>
<p>En la Figura <a href="loglik.html#fig:loglik2">15.3</a> se muestra el gráfico de niveles para la superficie de log-verosimilitud. De esta figura se nota claramente que los valores que maximizan la superficie están alrededor de <span class="math inline">\(\mu=170\)</span> y <span class="math inline">\(\sigma=5\)</span>. Para ver el código usado en la creación de la Figura <a href="loglik.html#fig:loglik2">15.3</a> se recomienda consultar la sección sobre <code>contour</code> en <span class="citation">Hernández (<a href="#ref-hernandez_correa">2018</a>)</span>.</p>
<div class="figure"><span id="fig:loglik2"></span>
<img src="Manual_de_R_files/figure-html/loglik2-1.png" alt="Gráfico de niveles para la función de log-verosimilitud para el ejemplo sobre normal." width="864" />
<p class="caption">
FIGURE 15.3: Gráfico de niveles para la función de log-verosimilitud para el ejemplo sobre normal.
</p>
</div>
<ol start="3" style="list-style-type: decimal">
<li>Obtenga los valores de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> que maximizan la función de log-verosimilitud.</li>
</ol>
<p>Para obtener los valores solicitados vamos a usar la función <code>nlminb</code> que es un optimizador. A la función <code>nlminb</code> se le debe indicar por medio del parámetro <code>objective</code> la función que queremos optimizar (minimizar); el parámetro <code>start</code> es un vector con los valores iniciales para comenzar la búsqueda de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>; los parámetros <code>lower</code> y <code>upper</code> sirven para delimitar el espacio de búsqueda. A continuación se muestra el código usado para obtener los valores que minimizan a <code>minusll</code>, es decir, los valores que maximizan la función de log-verosimilitud. </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minusll &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="op">-</span><span class="kw">ll</span>(x)
<span class="kw">nlminb</span>(<span class="dt">objective=</span>minusll, <span class="dt">start=</span><span class="kw">c</span>(<span class="dv">163</span>, <span class="fl">3.4</span>),
       <span class="dt">lower=</span><span class="kw">c</span>(<span class="dv">160</span>, <span class="dv">3</span>), <span class="dt">upper=</span><span class="kw">c</span>(<span class="dv">180</span>, <span class="dv">7</span>))</code></pre></div>
<pre><code>## $par
## [1] 170.338   5.424
## 
## $objective
## [1] 155.5
## 
## $convergence
## [1] 0
## 
## $iterations
## [1] 13
## 
## $evaluations
## function gradient 
##       16       35 
## 
## $message
## [1] &quot;relative convergence (4)&quot;</code></pre>
<p>De la salida anterior podemos observar que los valores óptimos de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> son 170.338 y 5.424 respectivamente, resultado que coincide con lo observado en la Figura <a href="loglik.html#fig:loglik2">15.3</a> y con los valores reales de simulación de la muestra. Esto indica que el procedimiento de estimación de parámetros por máxima verosimilitud entrega valores insesgados de los parámetros a estimar.</p>
<p>Un resultado interesante de la salida anterior es que se reporta el valor mínimo que alcanza la función <code>minusll</code>, este valor fue de 155.5, por lo tanto, se puede afirmar que el valor máximo de log-verosimilitud es -155.5.</p>
<p>Otros resultados importantes de la salida anterior son el valor de <code>convergence=0</code> que indica que la búsqueda fue exitosa; <code>iterations=13</code> indica que se realizaron 13 pasos desde el punto inicial <code>start</code> hasta las coordenadas de optimización.</p>

<div class="rmdnote">
En  se tienen dos funciones básicas para optimizar funciones, es decir, para encontrar los valores que minimizan una función dada. Esas dos funciones son <code>nliminb</code> y <code>optim</code>. Para optimizar en una sola dimensión se usa la función <code>optimize</code>.
</div>

<ol start="4" style="list-style-type: decimal">
<li>¿Hay alguna función para obtener directamente el valor que maximiza la función log-verosimilitud?</li>
</ol>
<p>La respuesta es si. Si la distribución estudiada es una de las distribuciones básicas se puede usar la función <code>fitdistr</code> del paquete básico <strong>MASS</strong>. La función <code>fitdistr</code> requiere de los datos que se ingresan por medio del parámetro <code>x</code>, y de la distribución de los datos que se ingresa por medio del parámetro <code>densfun</code>. La función <code>fitdistr</code> admite 15 distribuciones diferentes para hacer la búsqueda de los parámetros que caracterizan una distribución, se sugiere consultar la ayuda de la función <code>fitdistr</code> escribiendo en la consola <code>help(fitdistr)</code>. A continuación el código usado. </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(MASS) <span class="co"># El paquete ya está instalado, solo se debe cargar</span>
res &lt;-<span class="st"> </span><span class="kw">fitdistr</span>(<span class="dt">x=</span>y, <span class="dt">densfun=</span><span class="st">&#39;normal&#39;</span>)
res</code></pre></div>
<pre><code>##      mean        sd   
##   170.3384     5.4235 
##  (  0.7670) (  0.5424)</code></pre>
<p>El objeto <code>res</code> contiene los resultados de usar <code>fitdistr</code>. En la primer línea están los valores de los parámetros que maximizan la función de log-verosimilitud, en la parte de abajo, dentro de paréntesis, están los errores estándar o desviaciones de éstos estimadores.</p>
<p>Al objeto <code>res</code> es de la clase <em>fitdistr</em> y por lo tanto se le puede aplicar la función genérica <code>logLik</code> para obtener el valor de la log-verosimilitud. Se sugiere consultar la ayuda de la función <code>logLik</code> escribiendo en la consola <code>help(logLik)</code>. A continuación el código para usar <code>logLik</code> sobre el objeto <code>res</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">logLik</span>(res)</code></pre></div>
<pre><code>## &#39;log Lik.&#39; -155.5 (df=2)</code></pre>
<p>De esta última salida se observa que el valor coincide con el obtenido cuando se usó <code>nlminb</code>.</p>
</div>
<div id="ejemplo-51" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Generar <span class="math inline">\(n=100\)</span> observaciones de una gamma con parámetro de forma igual a 2 y parámetro de tasa igual a 0.5 y luego responder las preguntas.</p>
<p>Para generar la muestra aleatoria <code>ma</code> solicitada se fijó la semilla con el objetivo de que el lector pueda obtener los mismos resultados de este ejemplo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">100</span>
<span class="kw">set.seed</span>(<span class="dv">12345</span>)
ma &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dt">n=</span>n, <span class="dt">shape=</span><span class="dv">2</span>, <span class="dt">rate=</span><span class="fl">0.5</span>)</code></pre></div>
<ol style="list-style-type: decimal">
<li>Asumiendo que la muestra aleatoria proviene de una normal (lo cual es incorrecto) estime los parámetros de la distribución normal.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit1 &lt;-<span class="st"> </span><span class="kw">fitdistr</span>(<span class="dt">x=</span>ma, <span class="dt">densfun=</span><span class="st">&#39;normal&#39;</span>)
fit1</code></pre></div>
<pre><code>##     mean      sd  
##   4.3083   2.8085 
##  (0.2808) (0.1986)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Asumiendo que la muestra aleatoria proviene de una gamma estime los parámetros de la distribución.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit2 &lt;-<span class="st"> </span><span class="kw">fitdistr</span>(<span class="dt">x=</span>ma, <span class="dt">densfun=</span><span class="st">&#39;gamma&#39;</span>)
fit2</code></pre></div>
<pre><code>##     shape     rate  
##   2.23978   0.51988 
##  (0.29620) (0.07703)</code></pre>
<p>En la salida anterior están los valores estimados de los parámetros de la distribución por el método de máxima verosimilitud, observe la cercanía de éstos con los verdaderos valores de 2 y 0.5 para forma y tasa respectivamente.</p>
<ol start="3" style="list-style-type: decimal">
<li>Dibuje dos qqplot, uno asumiendo distribución normal y el otro distribución gamma. ¿Cuál distribución se ajusta mejor a los datos simulados?</li>
</ol>
<p>Para dibujar el qqplot se usa la función genérica <code>qqplot</code>, recomendamos consultar <span class="citation">Hernández (<a href="#ref-hernandez_correa">2018</a>)</span> para los detalles de cómo usar esta función. Al usar <code>qqplot</code> para obtener el qqplot normal y gamma es necesario indicar los valores <span class="math inline">\(\hat{\boldsymbol{\Theta}}\)</span> obtenidos en el numeral anterior, por eso es que en el código mostrado a continuación aparece <code>mean=4.3083, sd=2.8085</code> en el qqplot normal y <code>shape=2.23978, rate=0.51988</code> en el qqplot gamma.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))

<span class="kw">qqplot</span>(<span class="dt">y=</span>ma, <span class="dt">pch=</span><span class="dv">19</span>,
       <span class="dt">x=</span><span class="kw">qnorm</span>(<span class="kw">ppoints</span>(n), <span class="dt">mean=</span><span class="fl">4.3083</span>, <span class="dt">sd=</span><span class="fl">2.8085</span>),
       <span class="dt">main=</span><span class="st">&#39;Normal Q-Q Plot&#39;</span>,
       <span class="dt">xlab=</span><span class="st">&#39;Theoretical Quantiles&#39;</span>,
       <span class="dt">ylab=</span><span class="st">&#39;Sample Quantiles&#39;</span>)

<span class="kw">qqplot</span>(<span class="dt">y=</span>ma, <span class="dt">pch=</span><span class="dv">19</span>,
       <span class="dt">x=</span><span class="kw">qgamma</span>(<span class="kw">ppoints</span>(n), <span class="dt">shape=</span><span class="fl">2.23978</span>, <span class="dt">rate=</span><span class="fl">0.51988</span>),
       <span class="dt">main=</span><span class="st">&#39;Gamma Q-Q Plot&#39;</span>,
       <span class="dt">xlab=</span><span class="st">&#39;Theoretical Quantiles&#39;</span>,
       <span class="dt">ylab=</span><span class="st">&#39;Sample Quantiles&#39;</span>)</code></pre></div>
<div class="figure"><span id="fig:normgamma"></span>
<img src="Manual_de_R_files/figure-html/normgamma-1.png" alt="Gráfico cuantil cuantil normal y gamma para la muestra simulada." width="864" />
<p class="caption">
FIGURE 15.4: Gráfico cuantil cuantil normal y gamma para la muestra simulada.
</p>
</div>
<p>En la Figura <a href="loglik.html#fig:normgamma">15.4</a> se muestran los qqplot solicitados. Se observa claramente que al asumir normalidad (lo cual es incorrecto), los puntos del qqplot no están alineados, mientras que al asumir distribución gamma (lo cual es correcto), los puntos si están alineados. De esta figura se concluye que la muestra <code>ma</code> puede provenir de una <span class="math inline">\(Gamma(2.23978, 0.51988)\)</span>.</p>

<div class="rmdtip">
Para obtener el gráfico cuantil cuantil bajo normalidad se puede usar directamente la función <code>qqnorm</code>, consultar <span class="citation">Hernández (<a href="#ref-hernandez_correa">2018</a>)</span> para mayores detalles.
</div>


<div class="rmdwarning">
En este ejemplo se eligió la mejor distribución entre dos candidatas usando una herramienta gráfica, lo que se recomienda usar algún método menos subjetivo (cuantitativo) para tomar decisiones.
</div>

<ol start="4" style="list-style-type: decimal">
<li>Para comparar modelos se puede utilizar el <em>Akaike information criterion</em> (<span class="math inline">\(AIC\)</span>) propuesto por <span class="citation">Akaike (<a href="#ref-Akaike74">1974</a>)</span> que sirve para medir la calidad relativa de los modelos estadísticos, la expresión para calcular el indicador es <span class="math inline">\(AIC=-2 \, \hat{l}+2 \, df\)</span>, donde <span class="math inline">\(\hat{l}\)</span> corresponde al valor de <span class="math inline">\(\log\)</span>-verosimilitud y <span class="math inline">\(df\)</span> corresponde al número de parámetros estimados del modelo. Siempre el modelo elegido es aquel modelo con el menor valor de <span class="math inline">\(AIC\)</span>. Calcular el <span class="math inline">\(AIC\)</span> para los modelos asumidos normal y gamma.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">logLik</span>(fit1) <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="dv">2</span>  <span class="co"># AIC para modelo normal</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; 494.3 (df=2)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">logLik</span>(fit2) <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="dv">2</span>  <span class="co"># AIC para modelo gamma</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; 466 (df=2)</code></pre>
<p>De los resultados anteriores se concluye que entre los dos modelos, el mejor es el gamma porque su <span class="math inline">\(AIC=466\)</span> es el menor de toos los <span class="math inline">\(AIC\)</span>.</p>

<div class="rmdnote">
Modelos anidados pueden ser comparados por medio del <em>global deviance</em> (<span class="math inline">\(GD\)</span>) dado por <span class="math inline">\(GD=-2 \, \hat{l}\)</span> y modelos no anidados por medio del <em>Generalized Akaike information criterion</em> (<span class="math inline">\(GAIC\)</span>) propuesto por <span class="citation">Akaike (<a href="#ref-Akaike83">1983</a>)</span> y dado por <span class="math inline">\(GAIC=-2 \, \hat{l} + \sharp \, df\)</span> siendo <span class="math inline">\(\sharp\)</span> el valor de penalidad por cada parámetro adicional en el modelo; cuando <span class="math inline">\(\sharp = 2\)</span>, el <span class="math inline">\(GAIC\)</span> coincide con el <span class="math inline">\(AIC\)</span> y el <em>Schwarz Bayesian criterion</em> (<span class="math inline">\(SBC\)</span>) propuesto por <span class="citation">Schwarz (<a href="#ref-Schwarz">1978</a>)</span> se dá cuando el valor de penalidad es <span class="math inline">\(\sharp = \log(n)\)</span> donde <span class="math inline">\(n\)</span> es el número de observaciones del modelo; siempre el modelo elegido es aquel modelo con el menor valor de cualquiera de los criterios de información anteriores.
</div>

</div>
<div id="ejemplo-52" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>¿Será posible explorar entre muchas distribuciones estadísticas aquella que mejor explica una variable de interés?</p>
<p>La respuesta es si, se puede usar la función <code>fitDist</code> del paquete <strong>gamlss</strong> . Esta función tiene la siguiente estructura:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fitDist</span>(y, <span class="dt">k =</span> <span class="dv">2</span>, 
      <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;realAll&quot;</span>, <span class="st">&quot;realline&quot;</span>, <span class="st">&quot;realplus&quot;</span>,
               <span class="st">&quot;real0to1&quot;</span>, <span class="st">&quot;counts&quot;</span>, <span class="st">&quot;binom&quot;</span>))</code></pre></div>
<p>El parámetro <code>y</code> sirve para ingresar el vector con la información; <code>k=2</code> es la penalización por cada parámetro estimado para calcular el <span class="math inline">\(GAIC\)</span>, por defecto es 2; y el parámetro <code>type</code> sirve para indicar el tipo de distribución, los posibles valores son:</p>
<ul>
<li><code>realAll</code>: para hacer la búsqueda en todas las distribuciones disponibles en <strong>gamlss</strong>.</li>
<li><code>realline</code>: para variables en <span class="math inline">\(\Re\)</span>.</li>
<li><code>realplus</code>: para variables en <span class="math inline">\(\Re^+\)</span>.</li>
<li><code>real0to1</code>: para variables en el intervalo <span class="math inline">\((0, 1)\)</span>.</li>
<li><code>counts</code>: para variables de conteo.</li>
<li><code>binom</code>: para variables de tipo binomial.</li>
</ul>
<ol style="list-style-type: decimal">
<li>Usar la función <code>fitDist</code> para elegir la distribución que mejor se ajusta a los datos simulados en el ejemplo anterior, usar una penalizacion de <span class="math inline">\(k=2\)</span> para calcular el <span class="math inline">\(AIC\)</span>.</li>
</ol>
<p>Se usa la función <code>fitDist</code> con <code>type='realplus'</code> porque se sabe que la muestra aleatoria tiene valores sólo en <span class="math inline">\(\Re^+\)</span>, los resultados de almacenan en el objeto <code>modelos</code>. Para obtener la lista de los mejores modelos con su respectivo <span class="math inline">\(BAIC\)</span> se escribe en la consola <code>modelos$fits</code>. Abajo el código usado.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(gamlss)
modelos &lt;-<span class="st"> </span><span class="kw">fitDist</span>(<span class="dt">y=</span>ma, <span class="dt">type=</span><span class="st">&#39;realplus&#39;</span>, <span class="dt">k=</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## Error in solve.default(oout$hessian) : 
##   Lapack routine dgesv: system is exactly singular: U[4,4] = 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelos<span class="op">$</span>fits</code></pre></div>
<pre><code>##       GA     WEI3     WEI2      WEI       GG      GIG 
##    466.0    466.8    466.8    466.8    468.0    468.0 
##    BCCGo     BCCG     BCPE    BCPEo      GB2     BCTo 
##    468.4    468.4    469.4    469.4    470.0    470.4 
##      BCT   exGAUS   LOGNO2    LOGNO       IG      EXP 
##    470.4    471.2    474.6    474.6    483.9    494.1 
## PARETO2o       GP  PARETO2   IGAMMA 
##    496.1    496.1    496.1    504.2</code></pre>
<p>De la lista anterior se observa que la función gamma está en el primer lugar con un <span class="math inline">\(BAIC=466\)</span>, valor que coincide con el <span class="math inline">\(AIC\)</span> obtenido en el ejercicio anterior. Esto significa que como la gamma tiene el menor <span class="math inline">\(BAIC\)</span>, es la distribución que mejor se ajusta a los datos de la muestra, esto coincide con la realidad, ya que la muestra fue generada de una distribución gamma.</p>
<p>¿Por queé <span class="math inline">\(AIC\)</span> y <span class="math inline">\(BAIC\)</span> coinciden en este ejemplo?</p>
<ol start="2" style="list-style-type: decimal">
<li>¿Cuáles son los valores estimados de los parámetros para la distribución gamma identificada en el paso anterior?</li>
</ol>
<p>En <strong>gamlss</strong> los parámetros de las distribuciones se nombran de una forma especial, el parámetro de posición se denomina <span class="math inline">\(\mu\)</span>, el de dispersión se denomina <span class="math inline">\(\sigma\)</span> y los de simetría y curtosis con <span class="math inline">\(\nu\)</span> y <span class="math inline">\(\tau\)</span>. La distribución gamma sólo tiene 2 parámetros y para obtener sus valores estimados se usa el siguiente código.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelos<span class="op">$</span>mu</code></pre></div>
<pre><code>## [1] 4.308</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelos<span class="op">$</span>sigma</code></pre></div>
<pre><code>## [1] 0.6682</code></pre>
<p>Si comparamos los anteriores resultados, <span class="math inline">\(\hat{\mu}= 4.308\)</span> y <span class="math inline">\(\hat{\sigma}=0.6682\)</span>, con los encontrados al usar la función <code>fitdist</code>, <span class="math inline">\(\widehat{shape}=2.23978\)</span> y <span class="math inline">\(\widehat{rate}=0.51988\)</span>, vemos que no coinciden, esto se debe a que la parametrización de la gamma usada por <strong>gamlss</strong> es diferente a la parametrización usada por la base de . Lo anterior no es motivo de preocupación, lo que se recomienda es que el usuario elija una de las parametrizaciones y trabaje con ella, no debe mezclarlas.</p>
<ol start="3" style="list-style-type: decimal">
<li>Dibujar el histograma para la muestra aleatoria y agregar la densidad de la distribución gamma identificada como la distribución que mejor explica el comportamiento de la variable.</li>
</ol>
<p>Para hacer lo solicitado se usa la función <code>histDist</code> del paquete <strong>gamlss</strong>, sólo es necesario ingresar los datos y la familia o distribución de la densidad requerida. Abajo el código usado.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">histDist</span>(<span class="dt">y=</span>ma, <span class="dt">family=</span>GA, <span class="dt">main=</span><span class="st">&#39;&#39;</span>, <span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Densidad&#39;</span>,
         <span class="dt">line.col=</span><span class="st">&#39;blue&#39;</span>, <span class="dt">line.wd=</span><span class="dv">4</span>)</code></pre></div>
<div class="figure"><span id="fig:histDist1"></span>
<img src="Manual_de_R_files/figure-html/histDist1-1.png" alt="Histograma para la muestra simulada con la densidad de una Gamma(mu=4.308, sigma=0.6682)." width="864" />
<p class="caption">
FIGURE 15.5: Histograma para la muestra simulada con la densidad de una Gamma(mu=4.308, sigma=0.6682).
</p>
</div>
<pre><code>## 
## Family:  c(&quot;GA&quot;, &quot;Gamma&quot;) 
## Fitting method: &quot;nlminb&quot; 
## 
## Call:  
## gamlssML(formula = ma, family = &quot;GA&quot;, data = sys.parent()) 
## 
## 
## Mu Coefficients:
## [1]  1.46
## Sigma Coefficients:
## [1]  -0.403
## 
##  Degrees of Freedom for the fit: 2 Residual Deg. of Freedom   98 
## Global Deviance:     462 
##             AIC:     466 
##             SBC:     471.3</code></pre>
<p>En la Figura <a href="loglik.html#fig:histDist1">15.5</a> se presenta el histograma para muestra aleatoria y la densidad de la gamma que mejor explica estos datos. Se observa claramente que la curva de densidad azul acompaña el patrón de los datos.</p>
</div>
</div>
<div id="score-e-informacion-de-fisher" class="section level2">
<h2><span class="header-section-number">15.4</span> Score e Información de Fisher</h2>
<p>En esta sección se explican los conceptos y utilidad de la función Score y la Información de Fisher.</p>
<div id="score-e-informacion-de-fisher-en-el-caso-univariado." class="section level3">
<h3><span class="header-section-number">15.4.1</span> Score e Información de Fisher en el caso univariado.</h3>
<p>La función Score denotada por <span class="math inline">\(S(\theta)\)</span> se define como la primera derivada de la función de log-verosimilitud así:</p>
<p><span class="math display">\[
S(\theta) \equiv \frac{\partial}{\partial \theta} l(\theta)
\]</span></p>
<p>y el estimador de máxima verosimilitud <span class="math inline">\(\hat{\theta}\)</span> se encuentra solucionando la igualdad</p>
<p><span class="math display">\[
S(\theta) = 0
\]</span></p>
<p>En el valor máximo <span class="math inline">\(\hat{\theta}\)</span> la curva <span class="math inline">\(l(\theta)\)</span> es cóncava hacia abajo y por lo tanto la segunda derivada es negativa, así la curvatura <span class="math inline">\(I(\theta)\)</span> se define como</p>
<p><span class="math display">\[
I(\theta) \equiv - \frac{\partial^2}{\partial \theta^2} l(\theta)
\]</span></p>
<p>Una curvatura grande <span class="math inline">\(I(\hat{\theta})\)</span> está asociada con un gran pico en la función de log-verosimilitud y eso significa una menor incertidumbre sobre el parámetro <span class="math inline">\(\theta\)</span> <span class="citation">(Pawitan <a href="#ref-pawitan_2013">2013</a>)</span>. En particular la varianza del estimador de máxima verosimilitud está dada por</p>
<p><span class="math display">\[Var(\hat{\theta})=I^{-1}(\hat{\theta})\]</span></p>
</div>
<div id="ejemplo-53" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que se desea estudiar una variable que tiene distribución Poisson con parámetro <span class="math inline">\(\lambda\)</span> desconocido. Suponga además que se tienen dos situciones:</p>
<ul>
<li>Un solo valor 5 para estimar <span class="math inline">\(\lambda\)</span>.</li>
<li>Cuatro valores 5, 10, 6 y 15 para estimar <span class="math inline">\(\lambda\)</span>.</li>
</ul>
<p>Dibujar la función <span class="math inline">\(l(\lambda)\)</span> para ambos casos e identificar la curvatura.</p>
<p>A continuación el código para evaluar la función <span class="math inline">\(l(\lambda)\)</span> para cada caso.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Caso 1</span>
w &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>)
ll1 &lt;-<span class="st"> </span><span class="cf">function</span>(lambda) <span class="kw">sum</span>(<span class="kw">dpois</span>(<span class="dt">x=</span>w, <span class="dt">lambda=</span>lambda, <span class="dt">log=</span>T))
ll1 &lt;-<span class="st"> </span><span class="kw">Vectorize</span>(ll1)

<span class="co"># Caso 2</span>
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">6</span>, <span class="dv">15</span>)
ll2 &lt;-<span class="st"> </span><span class="cf">function</span>(lambda) <span class="kw">sum</span>(<span class="kw">dpois</span>(<span class="dt">x=</span>y, <span class="dt">lambda=</span>lambda, <span class="dt">log=</span>T))
ll2 &lt;-<span class="st"> </span><span class="kw">Vectorize</span>(ll2)</code></pre></div>
<p>En la Figura <a href="loglik.html#fig:loglikpoisson">15.6</a> se muestran las dos curvas <span class="math inline">\(l(\lambda)\)</span> para cada uno de los casos. De la figura se observa claramente que cuando se tienen 4 observaciones la curva es más puntiaguda y por lo tanto menor incertibumbre sobre el parámetro <span class="math inline">\(\lambda\)</span> a estimar.</p>
<div class="figure"><span id="fig:loglikpoisson"></span>
<img src="Manual_de_R_files/figure-html/loglikpoisson-1.png" alt="Curvas de log-verosimilitud para los dos casos." width="480" />
<p class="caption">
FIGURE 15.6: Curvas de log-verosimilitud para los dos casos.
</p>
</div>
</div>
</div>
<div id="metodo-de-maxima-verosimilitud-para-estimar-parametros-en-modelos-de-regresion" class="section level2">
<h2><span class="header-section-number">15.5</span> Método de máxima verosimilitud para estimar parámetros en modelos de regresión</h2>
<p>En la sección anterior se estudió cómo estimar los parámetros de una distribución, en este capítulo se aprenderá a estimar los parámetros de un modelo de regresión general.</p>
<div id="ejemplo-54" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Considere el modelo de regresión mostrado abajo. Simule 1000 observaciones del modelo y use la función <code>optim</code> para estimar los parámetros del modelo.</p>
<span class="math display">\[\begin{align*}
y_i &amp;\sim N(\mu_i, \sigma^2), \\
\mu_i &amp;= -2 + 3 x_1, \\
\sigma &amp;= 5, \\
x_1 &amp;\sim U(-5, 6).
\end{align*}\]</span>
<p>El código mostrado a continuación permite simular un conjunto de valores con la estructura anteior.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">1000</span>
x1 &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dt">n=</span>n, <span class="op">-</span><span class="dv">5</span>, <span class="dv">6</span>)
y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n=</span>n, <span class="dt">mean=</span><span class="op">-</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">3</span> <span class="op">*</span><span class="st"> </span>x1, <span class="dt">sd=</span><span class="dv">5</span>)</code></pre></div>
<p>El vector de parámetros del modelo anterior es <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0, \beta_1, \sigma)^\top=(-2, 3, 5)^\top\)</span>, el primer elemento corresponde al intercepto, el segundo a la pendiente y el último a la desviación.</p>
<p>A continuación se define la función de <strong>menos</strong> log-verosimilitud para el modelo anterior. A pesar de que nos interesa maximizar la función de log-verosimilitud hemos creado su negativo, esto porque la mayoría de las funciones de optimización minimizan y no maximizan; maximizar <span class="math inline">\(f(x)\)</span> es equivalente a minimizar <span class="math inline">\(-f(x)\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minusll &lt;-<span class="st"> </span><span class="cf">function</span>(theta, y, x1) {
  media &lt;-<span class="st"> </span>theta[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>theta[<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span>x1  <span class="co"># Se define la media</span>
  desvi &lt;-<span class="st"> </span>theta[<span class="dv">3</span>]                  <span class="co"># Se define la desviación.</span>
  <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(<span class="kw">dnorm</span>(<span class="dt">x=</span>y, <span class="dt">mean=</span>media, <span class="dt">sd=</span>desvi, <span class="dt">log=</span><span class="ot">TRUE</span>))
}</code></pre></div>
<p>Ahora vamos a usar la función <code>optim</code> para encontrar los valores que maximizan la función de log-verosimilitud, el código para hacer eso se muestra a continuación. En el parámetro <code>par</code> se coloca un vector de posibles valores de <span class="math inline">\(\boldsymbol{\Theta}\)</span> para iniciar la búsqueda, en <code>fn</code> se coloca la función de interés, en <code>lower</code> y <code>upper</code> se colocan vectores que indican los límites de búsqueda de cada parámetro, los <span class="math inline">\(\beta_k\)</span> pueden variar entre <span class="math inline">\(-\infty\)</span> y <span class="math inline">\(\infty\)</span> mientras que el parámetro <span class="math inline">\(\sigma\)</span> toma valores en el intervalo <span class="math inline">\((0, \infty)\)</span>. Como la función <code>minusll</code> tiene argumentos adicionales <code>y</code> e <code>x1</code>, estos pasan a la función <code>optim</code> al final como se muestra en el código.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res1 &lt;-<span class="st"> </span><span class="kw">optim</span>(<span class="dt">par=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">fn=</span>minusll,
              <span class="dt">method=</span><span class="st">&#39;L-BFGS-B&#39;</span>,
              <span class="dt">lower=</span><span class="kw">c</span>(<span class="op">-</span><span class="ot">Inf</span>, <span class="op">-</span><span class="ot">Inf</span>, <span class="dv">0</span>),
              <span class="dt">upper=</span><span class="kw">c</span>(<span class="ot">Inf</span>, <span class="ot">Inf</span>, <span class="ot">Inf</span>), <span class="dt">y=</span>y, <span class="dt">x1=</span>x1)</code></pre></div>
<p>En el objeto <code>res1</code> está el resultado de la optimización, para explorar los resultados usamos</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res1</code></pre></div>
<pre><code>## $par
## [1] -1.905  3.080  5.014
## 
## $value
## [1] 3031
## 
## $counts
## function gradient 
##       19       19 
## 
## $convergence
## [1] 0
## 
## $message
## [1] &quot;CONVERGENCE: REL_REDUCTION_OF_F &lt;= FACTR*EPSMCH&quot;</code></pre>
<p>De la salida anterior se observa que el vector de parámetros estimado es -1.9046, 3.0796, 5.0142 y que el valor de la máxima log-verosimilitud fue de 3031.2092. Vemos entonces que el vector estimado está muy cerca del verdadero <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0, \beta_1, \sigma)^\top=(-2, 3, 5)^\top\)</span>.</p>
<p>En algunas ocasiones es mejor hacer la búsqueda de los parámetros en el intervalo <span class="math inline">\((-\infty, \infty)\)</span> que en una región limitada como por ejemplo <span class="math inline">\((0, \infty)\)</span> o <span class="math inline">\((-1, 1)\)</span>, ya que las funciones de búsqueda podrían tener problemas en los límites numéricos. Una estrategia usual en este tipo de casos es aplicar una transformación apropiada al parámetro que tiene el dominio limitado. En el presente ejemplo <span class="math inline">\(\sigma\)</span> sólo puede tomar valores mayores que cero y una transformación de tipo <span class="math inline">\(\log\)</span> podría ser muy útil ya que <span class="math inline">\(\log\)</span> relaciona los reales positivos con todos los reales. La transformación para este problema sería <span class="math inline">\(\log(\sigma)=\beta_3\)</span> o escrita de forma inversa <span class="math inline">\(\sigma=\exp(\beta_3)\)</span>. El nuevo parámetro <span class="math inline">\(\beta_3\)</span> puede variar en <span class="math inline">\((-\infty, \infty)\)</span> pero al ser transformado por la función exponencial este se volvería un valor apropiado para <span class="math inline">\(\sigma\)</span>. Para implementar esta variación lo único que se debe hacer es modificar la línea 3 de la función <code>minusll</code> como se muestra a continuación:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minusll &lt;-<span class="st"> </span><span class="cf">function</span>(theta, y, x1) {
  media &lt;-<span class="st"> </span>theta[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>theta[<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span>x1  
  desvi &lt;-<span class="st"> </span><span class="kw">exp</span>(theta[<span class="dv">3</span>])  <span class="co"># &lt;&lt;&lt;&lt;&lt;---- El cambio fue aquí</span>
  <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(<span class="kw">dnorm</span>(<span class="dt">x=</span>y, <span class="dt">mean=</span>media, <span class="dt">sd=</span>desvi, <span class="dt">log=</span><span class="ot">TRUE</span>))
}</code></pre></div>
<p>Para hacer la búsqueda se procede de forma similar, abajo el código necesario.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res2 &lt;-<span class="st"> </span><span class="kw">optim</span>(<span class="dt">par=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">fn=</span>minusll, <span class="dt">y=</span>y, <span class="dt">x1=</span>x1)</code></pre></div>
<p>Para obtener los valores ajustados y almacenados en el objeto <code>res2</code> usamos el siguiente código.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(res2<span class="op">$</span>par[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="kw">exp</span>(res2<span class="op">$</span>par[<span class="dv">3</span>]))</code></pre></div>
<pre><code>## [1] -1.905  3.079  5.015</code></pre>
<p>De la salida anterior se observa que el vector estimado está muy cerca del verdadero <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0, \beta_1, \sigma)^\top=(-2, 3, 5)^\top\)</span>.</p>
</div>
</div>
<div id="ejercicios-6" class="section level2 unnumbered">
<h2>EJERCICIOS</h2>
<ol style="list-style-type: decimal">
<li>Al inicio del Capítulo <a href="central.html#central">9</a> se presentó la base de datos sobre medidas del cuerpo, consulte la explicación sobre la base de datos y responda lo siguiente.</li>
</ol>
<ul>
<li>Si se asume que la <code>edad</code> tiene distribución normal, ¿cuáles son los estimadores de máxima verosimilitud para <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>?</li>
<li>Como el histograma para la edad muestra un sesgo a la derecha se podría pensar que la distribución gamma sería una buena candidata para explicar las edades observadas. Asumiendo una distribución gamma, ¿cuáles son los estimadores de máxima verosimilitud para los parámetros?</li>
<li>¿Cuál de los dos modelos es más apropiado para explicar la variable de interés? Calcule el <span class="math inline">\(AIC\)</span> para decidir.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>En la sección <a href="#crabs"><strong>??</strong></a> se presentó la base de datos sobre cangrejos hembra, consulte la explicación sobre la base de datos y responda lo siguiente.</li>
</ol>
<ul>
<li>Suponga que el número de satélites sobre cada hembra es una variable que se distribuye Poisson. Construya en  la función de log-verosimilitud <span class="math inline">\(l\)</span>, dibuje la función <span class="math inline">\(l\)</span> y encuentre el estimador de máxima verosimilitud de <span class="math inline">\(\lambda\)</span>.</li>
<li>Repita el ejercicio anterior asumiendo que el número de satélites se distribuye binomial negativo.</li>
<li>¿Cuál de los dos modelos es más apropiado para explicar la variable de interés? Calcule el <span class="math inline">\(AIC\)</span> para decidir.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Al inicio del Capítulo <a href="varia.html#varia">10</a> se presentó la base de datos sobre apartamentos usados en Medellín, consulte la explicación sobre la base de datos y responda lo siguiente.</li>
</ol>
<ul>
<li>Dibuje una densidad para la variable área del apartamento.</li>
<li>Describa lo encontrado en esa densidad.</li>
<li>¿Qué distribuciones de 2 parámetros podrían explicar el comportamiento del área de los apartamentos? Mencione al menos 3.</li>
<li>Para cada una de las distribuciones anteriores dibuje un gráfico de contornos o calor para la función de log-verosimilitud y estime los parámetros de la distribución elegida.</li>
<li>¿Cuál de los dos modelos es más apropiado para explicar la variable de interés? Calcule el <span class="math inline">\(AIC\)</span> para decidir.</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Considere el siguiente modelo de regresión.</li>
</ol>
<span class="math display">\[\begin{align*}
y_i &amp;\sim Gamma(shape_i, scale_i), \\
\log(shape_i) &amp;= 3 - 7 x_1, \\
\log(scale_i) &amp;= 3 - 1 x_2, \\
x_1 &amp;\sim U(0, 1), \\
x_2 &amp;\sim Poisson(\lambda=3)
\end{align*}\]</span>
<ul>
<li>Simule 100 observaciones del modelo anterior.</li>
<li>Escriba el vector de parámetros del problema.</li>
<li>Construya la función <code>minusll</code> para el problema.</li>
<li>Use la función <code>optim</code> para estimar los parámetros del problema.</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Fisher22">
<p>Fisher, R. A. 1922. “On the Mathematical Foundations of Theoretical Statistics.” <em>Philosophical Transactions of the Royal Society of London. Series A, Containing Papers of a Mathematical or Physical Character</em> 222. The Royal Society: 309–68. <a href="http://www.jstor.org/stable/91208" class="uri">http://www.jstor.org/stable/91208</a>.</p>
</div>
<div id="ref-pawitan_2013">
<p>Pawitan, Yudi. 2013. <em>In All Likelihood: Statistical Modelling and Inference Using Likelihood</em>. Oxford University Press.</p>
</div>
<div id="ref-hernandez_correa">
<p>Hernández, J., F. &amp; Correa. 2018. <em>Gráficos Con R</em>. Primera. Medellín, Colombia: Universidad Nacional de Colombia. <a href="http://yihui.name/knitr/" class="uri">http://yihui.name/knitr/</a>.</p>
</div>
<div id="ref-Akaike74">
<p>Akaike, H. 1974. “A new look at the statistical model identification.” <em>IEEE Transactions on Automatic Control</em> 19 (6): 716–23.</p>
</div>
<div id="ref-Akaike83">
<p>Akaike, H. 1983. “Information measures and model selection.” <em>Bulletin of the International Statistical Institute</em> 50: 277–90.</p>
</div>
<div id="ref-Schwarz">
<p>Schwarz, G. 1978. “Estimating the dimension of a model.” <em>Annals of Statistics</em> 6 (2): 461–64.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="continuas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="normalidad.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/23_loglik.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Manual_de_R.pdf", "Manual_de_R.epub"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
