\documentclass[10pt,]{krantz}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{unicode=true,
            pdftitle={Manual de R},
            colorlinks=true,
            linkcolor=Maroon,
            citecolor=Blue,
            urlcolor=Blue,
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{natbib}
\bibliographystyle{apalike}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Manual de R}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Freddy Hernández Barajas\\
Olga Cecilia Usuga Manco}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{2019-05-02}

\usepackage{booktabs}

% -------------------------------------------------------
  % Yo inclui esto para usar espanol
\usepackage[spanish]{babel}
\decimalpoint
\selectlanguage{spanish}
% -------------------------------------------------------
  
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother


% -------------------------------------------------------
\renewenvironment{quote}{\begin{VF}}{\end{VF}}
\let\oldhref\href
\renewcommand{\href}[2]{#2\footnote{\url{#1}}}

\ifxetex
  \usepackage{letltxmacro}
  \setlength{\XeTeXLinkMargin}{1pt}
  \LetLtxMacro\SavedIncludeGraphics\includegraphics
  \def\includegraphics#1#{% #1 catches optional stuff (star/opt. arg.)
    \IncludeGraphicsAux{#1}%
  }%
  \newcommand*{\IncludeGraphicsAux}[2]{%
    \XeTeXLinkBox{%
      \SavedIncludeGraphics#1{#2}%
    }%
  }%
\fi

\makeatletter

\newenvironment{kframe}{%
\medskip{}
\setlength{\fboxsep}{.8em}
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\renewenvironment{Shaded}{\begin{kframe}}{\end{kframe}}

%%%%%

\newenvironment{rmdblock}[1]
  {
  \begin{itemize}
  \renewcommand{\labelitemi}{
    \raisebox{-.7\height}[0pt][0pt]{
      {\setkeys{Gin}{width=3em,keepaspectratio}\includegraphics{images/#1}}
    }
  }
  \setlength{\fboxsep}{1em}
  \begin{kframe}
  \item
  }
  {
  \end{kframe}
  \end{itemize}
  }
\newenvironment{rmdnote}
  {\begin{rmdblock}{note}}
  {\end{rmdblock}}
\newenvironment{rmdcaution}
  {\begin{rmdblock}{caution}}
  {\end{rmdblock}}
\newenvironment{rmdimportant}
  {\begin{rmdblock}{important}}
  {\end{rmdblock}}
\newenvironment{rmdtip}
  {\begin{rmdblock}{tip}}
  {\end{rmdblock}}
\newenvironment{rmdwarning}
  {\begin{rmdblock}{warning}}
  {\end{rmdblock}}
% -------------------------------------------------------

\let\BeginKnitrBlock\begin \let\EndKnitrBlock\end
\begin{document}
\maketitle

{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{2}
\tableofcontents
}
\listoftables
\listoffigures
\section*{Prefacio}\label{prefacio}
\addcontentsline{toc}{section}{Prefacio}

Este libro fue creado con la intención de apoyar el aprendizaje del
lenguaje de programación R en estudiantes de pregrado, especialización,
maestría e investigadores, que necesiten realizar análisis estadísticos.
En este libro se explica de una forma sencilla la utilidad de la
principales funciones para realizar análisis estadístico.

El presente material está en proceso de elaboración, si el lector desea
tener la última versión del libro recomendamos consultar la versión
alojada en el repositorio de GitHub diponible en el siguiente enlace:
\url{https://github.com/fhernanb/Manual-de-R/blob/master/_book/Manual_de_R.pdf}

\subsection*{Estructura del libro}\label{estructura-del-libro}
\addcontentsline{toc}{subsection}{Estructura del libro}

El libro está estructurado de la siguiente manera.

En el capítulo \ref{intro} se presenta una breve introducción sobre el
lenguaje de programación R; en el capítulo \ref{objetos} se explican los
tipos de objetos más comunes en R; en el capítulo \ref{estilo} se
muestran las normas de estilo sugeridas para escribir código en R; el
capítulo \ref{funbas} presenta las funciones básicas que todo usuario
debe conocer para usar con éxito R; el capítulo \ref{creafun} trata
sobre cómo crear funciones; el capítulo \ref{read} muestra como leer
bases de datos desde R; en el capítulo \ref{tablas} se ilustra la forma
para construir tablas de frecuencia; en el capítulo \ref{central} se
muestra como obtener las diversas medidas de tendencial central para
variables cuantitativas, el capítulo \ref{varia} muestra como calcular
las medidas de variabilidad, en el capítulo \ref{posi} se ilustra cómo
usar las funciones para obtener medidas de posición; en el capítulo
\ref{correl} se muestra como obtener medidas de correlación entre pares
de variables; en los capítulos \ref{discretas} y \ref{continuas} se
tratan los temas de distribuciones discretas y continuas; en el capítulo
\ref{loglik} se aborda el tema de verosimilitud; en el capítulo
\ref{aproxint} se muestra el tema de aproximación de integrales.

\subsection*{Información del software y
convenciones}\label{informacion-del-software-y-convenciones}
\addcontentsline{toc}{subsection}{Información del software y
convenciones}

Para realizar este libro se usaron los paquetes de R
\textbf{knitr}\index{knitr} \citep{xie2015} y
\textbf{bookdown}\index{bookdown} \citep{R-bookdown}, estos paquetes
permiten construir todo el libro desde R y sirven para incluir código
que se ejecute de forma automática incluyendo las salidas y gráficos.

En todo el libro se presentarán códigos que el lector puede copiar y
pegar en su consola de R para obtener los mismos resultados aquí
presentados. Los códigos se destacan en una caja de color beis (o beige)
similar a la mostrada a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{6}
\NormalTok{a <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{)}
\DecValTok{5} \OperatorTok{*}\StringTok{ }\NormalTok{a}
\DecValTok{1}\OperatorTok{:}\DecValTok{10}
\end{Highlighting}
\end{Shaded}

Los resultados o salidas obtenidos de cualquier código se destacan con
dos símbolos de númeral (\texttt{\#\#}) al inicio de cada línea o
renglón, esto quiere decir que todo lo que inicie con \texttt{\#\#} son
resultados obtenidos y el usuario \textbf{NO} los debe copiar. Abajo se
muestran los resultados obtenidos luego de correr el código anterior.

\begin{verbatim}
## [1] 10
\end{verbatim}

\begin{verbatim}
## [1]  5 25 30
\end{verbatim}

\begin{verbatim}
##  [1]  1  2  3  4  5  6  7  8  9 10
\end{verbatim}

\subsection*{Bloques informativos}\label{bloques-informativos}
\addcontentsline{toc}{subsection}{Bloques informativos}

En varias partes del libro usaremos bloques informativos para resaltar
algún aspecto importante. Abajo se encuentra un ejemplo de los bloques y
su significado.

\BeginKnitrBlock{rmdnote}
Nota aclaratoria.
\EndKnitrBlock{rmdnote}

\BeginKnitrBlock{rmdtip}
Sugerencia.
\EndKnitrBlock{rmdtip}

\BeginKnitrBlock{rmdwarning}
Advertencia.
\EndKnitrBlock{rmdwarning}

\subsection*{Agradecimientos}\label{agradecimientos}
\addcontentsline{toc}{subsection}{Agradecimientos}

Agradecemos enormemente a todos los estudiantes, profesores e
investigadores que han leído este libro y nos han retroalimentado con
comentarios valiosos para mejorar el documento.

\BeginKnitrBlock{flushright}
Freddy Hernández Barajas

Olga Cecilia Usuga Manco
\EndKnitrBlock{flushright}

\section*{Sobre los autores}\label{sobre-los-autores}
\addcontentsline{toc}{section}{Sobre los autores}

Freddy Hernández Barajas es profesor asistente de la Universidad
Nacional de Colombia adscrito a la Escuela de Estadística de la Facultad
de Ciencias.

Olga Cecilia Usuga Manco es profesora asociada de la Universidad de
Antioquia adscrita al Departamento de Ingeniería Industrial de la
Facultad de Ingeniería.

\mainmatter

\section{Introducción}\label{intro}

\section{Orígenes} \label{sec:origenes}

R es un lenguaje de programación usado para realizar procedimientos
estadísticos y gráficos de alto nivel, este lenguaje fue creado en 1993
por los profesores e investigadores Robert Gentleman y Ross Ihaka.
Inicialmente el lenguaje se usó para apoyar los cursos que tenían a su
cargo los profesores, pero luego de ver la utilidad de la herramienta
desarrollada, decidieron colocar copias de R en StatLib. A partir de
1995 el código fuente de R está disponible bajo licencia GNU GPL para
sistemas operativos Windows, Macintosh y distribuciones Unix/Linux. La
comunidad de usuarios de R en el mundo es muy grande y los usuarios
cuentan con diferentes espacios para interactuar, a continuación una
lista no exhaustiva de los sitios más populares relacionados con R:

\begin{itemize}
\tightlist
\item
  \href{https://www.r-bloggers.com/}{Rbloggers}.
\item
  \href{http://r-es.org/}{Comunidad hispana de R}.
\item
  \href{http://r.789695.n4.nabble.com/}{Nabble}.
\item
  \href{http://r-br.2285057.n4.nabble.com/}{Foro en portugués}.
\item
  \href{http://stackoverflow.com/questions/tagged/r}{Stackoverflow}.
\item
  \href{http://stats.stackexchange.com/questions/tagged/r}{Cross
  Validated}.
\item
  \href{https://stat.ethz.ch/mailman/listinfo/r-help}{R-Help Mailing
  List}.
\item
  \href{http://blog.revolutionanalytics.com/}{Revolutions}.
\item
  \href{https://www.r-statistics.com/}{R-statistics blog}.
\item
  \href{https://rdatamining.wordpress.com/}{RDataMining}.
\end{itemize}

\begin{figure}

{\centering \includegraphics{images/Robert_Roos} 

}

\caption{Robert Gentleman (izquierda) y Ross Ihaka (derecha) creadores de R.}\label{fig:unnamed-chunk-7}
\end{figure}

\section{Descarga e instalación} \label{sec:descarga}

Para realizar la instalación de R usted debe visitar la página del CRAN
(\textit{Comprehensive R Archive Network}) disponible en este
\href{https://cran.r-project.org/}{enlace}. Una vez ingrese a la página
encontrará un cuadro similar al mostrado en la Figura \ref{fig:cran}
donde aparecen los enlaces de la instalación para los sistemas
operativos Linux, Mac y Windows.

\begin{figure}

{\centering \includegraphics{images/cran} 

}

\caption{Página del Cran.}\label{fig:cran}
\end{figure}

Supongamos que se desea instalar R en Windows, para esto se debe dar
clic sobre el hiperenlace
\textcolor{BurntOrange}{Download R for Windows} de la Figura
\ref{fig:cran}. Una vez hecho esto se abrirá una página con el contenido
mostrado en la Figura \ref{fig:inst1}. Una vez ingrese a esa nueva
página usted debe dar clic sobre el hiperenlace
\textcolor{BurntOrange}{install R for the first time} como es señalado
por la flecha roja en la Figura \ref{fig:inst1}.

\begin{figure}

{\centering \includegraphics{images/instalacion1} 

}

\caption{Página de instalación para la primera ocasión.}\label{fig:inst1}
\end{figure}

Luego de esto se abrirá otra página con un encabezado similar al
mostrado en la Figura \ref{fig:inst2}, al momento de capturar la figura
la versión actual de R era 3.2.5 pero seguramente en este momento usted
tendrá disponible una versión actualizada. Una vez allí uste debe dar
clic sobre \textcolor{BurntOrange}{Download R 3.2.5 for Windows} como es
señalado por la flecha verde. Luego de esto se descargará el instalador
R en el computador el cual deberá ser instalado con las opciones que
vienen por defecto.

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{images/instalacion2} 

}

\caption{Página de descarga.}\label{fig:inst2}
\end{figure}

Se recomienda observar el siguiente video didáctico de instalación de R
disponible en este \href{http://tinyurl.com/jd7b9ks}{enlace} para
facilitar la tarea de instalación.

\section{Apariencia del programa} \label{sec:apariencia}

Una vez que esté instalado R en su computador, usted podrá acceder a él
por la lista de programas o por medio del acceso directo que quedó en el
escritorio, en la Figura \ref{fig:rlogo} se muestra la apariencia del
acceso directo para ingresar a R.

\begin{figure}

{\centering \includegraphics[width=0.33\linewidth]{images/rlogo} 

}

\caption{Apariencia del acceso directo para ingresar a R.}\label{fig:rlogo}
\end{figure}

Al abrir R aparecerá en la pantalla de su computador algo similar a lo
que está en la Figura \ref{fig:pantalla}. La ventana izquierda se llama
consola y es donde se ingresan las instrucciones, una vez que se
construye un gráfico se activa otra ventana llamada ventana gráfica.
Cualquier usuario puede modificar la posición y tamaños de estas
ventanas, puede cambiar el tipo y tamaño de las letras en la consola,
para hacer esto se deben explorar las opciones de \textit{editar} en la
barra de herramientas.

\begin{figure}

{\centering \includegraphics{images/Rpantallazo} 

}

\caption{Apariencia de R.}\label{fig:pantalla}
\end{figure}

\section{Tipos de objetos}\label{objetos}

En R existen varios tipos de objectos que permiten que el usuario pueda
almacenar la información para realizar procedimientos estadísticos y
gráficos. Los principales objetos en R son vectores, matrices, arreglos,
marcos de datos y listas. A continuación se presentan las
características de estos objetos y la forma para crearlos.

\subsection{\texorpdfstring{Vectores \index{vector}
\label{vector}}{Vectores  }}\label{vectores}

Los vectores vectores son arreglos ordenados en los cuales se puede
almacenar información de tipo numérico (variable cuantitativa),
alfanumérico (variable cualitativa) o lógico (\texttt{TRUE} o
\texttt{FALSE}), pero no mezclas de éstos. La función de R para crear un
vector es \texttt{c()} y que significa concatenar; dentro de los
paréntesis de esta función se ubica la información a almacenar. Una vez
construído el vector se acostumbra a etiquetarlo con un nombre corto y
representativo de la información que almacena, la asignación se hace por
medio del operador \texttt{\textless{}-} entre el nombre y el vector.

A continuación se presenta un ejemplo de cómo crear tres vectores que
contienen las respuestas de cinco personas a tres preguntas que se les
realizaron.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edad <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{15}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{13}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\DecValTok{20}\NormalTok{)}
\NormalTok{deporte <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OtherTok{TRUE}\NormalTok{, }\OtherTok{TRUE}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\OtherTok{FALSE}\NormalTok{, }\OtherTok{TRUE}\NormalTok{)}
\NormalTok{comic.fav <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\StringTok{'Superman'}\NormalTok{, }\StringTok{'Batman'}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\StringTok{'Batman'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

El vector \texttt{edad} es un vector cuantitativo y contiene las edades
de las 5 personas. En la cuarta posición del vector se colocó el símbolo
\texttt{NA} que significa \textit{Not Available} debido a que no se
registró la edad para esa persona. Al hacer una asignación se acostumbra
a dejar un espacio antes y después del operador \texttt{\textless{}-} de
asignación. El segundo vector es llamado \texttt{deporte} y es un vector
lógico que almacena las respuestas a la pregunta de si la persona
practica deporte, nuevamente aquí hay un \texttt{NA} para la tercera
persona. El último vector \texttt{comic.fav} contiene la información del
cómic favorito de cada persona, como esta variable es cualitativa es
necesario usar las comillas
\texttt{\textquotesingle{}\ \textquotesingle{}} para encerrar las
respuestas.

\BeginKnitrBlock{rmdwarning}
Cuando se usa \texttt{NA} para representar una información
\textit{Not Available} no se deben usar comillas.
\EndKnitrBlock{rmdwarning}

\BeginKnitrBlock{rmdnote}
Es posible usar comillas sencillas
\texttt{\textquotesingle{}foo\textquotesingle{}} o comillas dobles
\texttt{"foo"} para ingresar valores de una variable cualitativa.
\EndKnitrBlock{rmdnote}

Si se desea ver lo que está almacenado en cada uno de estos vectores, se
debe escribir en la consola de R el nombre de uno de los objetos y luego
se presiona la tecla \textit{enter} o \textit{intro}, al realizar esto
lo que se obtiene se muestra a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edad}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15 19 13 NA 20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{deporte}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  TRUE  TRUE    NA FALSE  TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{comic.fav}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA         "Superman" "Batman"   NA        
## [5] "Batman"
\end{verbatim}

\subsubsection{¿Cómo extraer elementos de un
vector?}\label{como-extraer-elementos-de-un-vector}

Para extraer un elemento almacenado dentro un vector se usan los
corchetes \texttt{{[}{]}} y dentro de ellos la posición o posiciones que
interesan.

\subsubsection*{Ejemplo}\label{ejemplo}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Si queremos extraer la edad de la tercera persona escribimos el nombre
del vector y luego \texttt{{[}3{]}} para indicar la tercera posición de
\texttt{edad}, a continuación el código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edad[}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 13
\end{verbatim}

Si queremos conocer el cómic favorito de la segunda y quinta persona,
escribimos el nombre del vector y luego, dentro de los corchetes,
escribimos otro vector con las posiciones 2 y 5 que nos interesan así
\texttt{{[}c(2,\ 5){]}}, a continuación el código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{comic.fav[}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{5}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Superman" "Batman"
\end{verbatim}

Si nos interesan las respuestas de la práctica de deporte, excepto la de
la persona 3, usamos \texttt{{[}-3{]}} luego del nombre del vector para
obtener todo, excepto la tercera posición.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{deporte[}\OperatorTok{-}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  TRUE  TRUE FALSE  TRUE
\end{verbatim}

\BeginKnitrBlock{rmdwarning}
Si desea extraer varios posiciones de un vector NUNCA escriba esto:
\texttt{mivector{[}2,\ 5,\ 7{]}}. Tiene que crear un vector con las
posiciones y luego colocarlo dentro de los corchetes así:
\texttt{mivector{[}c(2,\ 5,\ 7){]}}
\EndKnitrBlock{rmdwarning}

\subsection{Matrices}\label{matrices}

Las matrices \index{matrices} son arreglos rectangulares de filas y
columnas con información numérica, alfanumérica o lógica. Para construir
una matriz se usa la función \texttt{matrix(\ )}. Por ejemplo, para
crear una matriz de 4 filas y 5 columnas (de dimensión \(4 \times 5\))
con los primeros 20 números positivos se escribe el código siguiente en
la consola.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{data=}\DecValTok{1}\OperatorTok{:}\DecValTok{20}\NormalTok{, }\DataTypeTok{nrow=}\DecValTok{4}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{5}\NormalTok{, }\DataTypeTok{byrow=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

El argumento \texttt{data} de la función sirve para indicar los datos
que se van a almacenar en la matriz, los argumentos \texttt{nrow} y
\texttt{ncol} sirven para definir la dimensión de la matriz y por último
el argumento \texttt{byrow} sirve para indicar si la información
contenida en \texttt{data} se debe ingresar por filas o no. Para
observar lo que quedó almacenado en el objeto \texttt{mimatriz} se
escribe en la consola el nombre del objeto seguido de la tecla
\textit{enter} o \textit{intro}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1    5    9   13   17
## [2,]    2    6   10   14   18
## [3,]    3    7   11   15   19
## [4,]    4    8   12   16   20
\end{verbatim}

\subsubsection{¿Cómo extraer elementos de una
matriz?}\label{como-extraer-elementos-de-una-matriz}

Al igual que en el caso de los vectores, para extraer elementos
almacenados dentro de una matriz se usan los corchetes
\texttt{{[}\ ,\ {]}} y dentro, separado por una coma, el número de
fila(s) y el número de columna(s) que nos interesan.

\subsubsection*{Ejemplo}\label{ejemplo-1}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Si queremos extraer el valor almacenado en la fila 3 y columna 4 usamos
el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz[}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15
\end{verbatim}

Si queremos recuperar \textbf{toda} la fila 2 usamos el siguiente
código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz[}\DecValTok{2}\NormalTok{, ]  }\CommentTok{# No se escribe nada luego de la coma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  2  6 10 14 18
\end{verbatim}

Si queremos recuperar \textbf{toda} la columna 5 usamos el siguiente
código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz[, }\DecValTok{5}\NormalTok{]  }\CommentTok{# No se escribe nada antes de la coma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17 18 19 20
\end{verbatim}

Si queremos recuperar la matriz original sin las columnas 2 y 4 usamos
el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz[, }\OperatorTok{-}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{)]  }\CommentTok{# Las columnas como vector}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3]
## [1,]    1    9   17
## [2,]    2   10   18
## [3,]    3   11   19
## [4,]    4   12   20
\end{verbatim}

Si queremos recuperar la matriz original sin la fila 1 ni columna 3
usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimatriz[}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\OperatorTok{-}\DecValTok{3}\NormalTok{]  }\CommentTok{# Signo de menos para eliminar}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    2    6   14   18
## [2,]    3    7   15   19
## [3,]    4    8   16   20
\end{verbatim}

\subsection{\texorpdfstring{Arreglos \index{arreglo}
\index{array}}{Arreglos  }}\label{arreglos}

Un arreglo es una matriz de varias dimensiones con información numérica,
alfanumérica o lógica. Para construir una arreglo se usa la función
\texttt{array(\ )}. Por ejemplo, para crear un arreglo de
\(3 \times 4 \times 2\) con las primeras 24 letras minúsculas del
alfabeto se escribe el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{miarray <-}\StringTok{ }\KeywordTok{array}\NormalTok{(}\DataTypeTok{data=}\NormalTok{letters[}\DecValTok{1}\OperatorTok{:}\DecValTok{24}\NormalTok{], }\DataTypeTok{dim=}\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

El argumento \texttt{data} de la función sirve para indicar los datos
que se van a almacenar en el arreglo y el argumento \texttt{dim} sirve
para indicar las dimensiones del arreglo. Para observar lo que quedó
almacenado en el objeto \texttt{miarray} se escribe en la consola lo
siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{miarray}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## , , 1
## 
##      [,1] [,2] [,3] [,4]
## [1,] "a"  "d"  "g"  "j" 
## [2,] "b"  "e"  "h"  "k" 
## [3,] "c"  "f"  "i"  "l" 
## 
## , , 2
## 
##      [,1] [,2] [,3] [,4]
## [1,] "m"  "p"  "s"  "v" 
## [2,] "n"  "q"  "t"  "w" 
## [3,] "o"  "r"  "u"  "x"
\end{verbatim}

\subsubsection{¿Cómo extraer elementos de un
arreglo?}\label{como-extraer-elementos-de-un-arreglo}

Para recuperar elementos almacenados en un arreglo se usan también
corchetes, y dentro de los corchetes, las coordenadas del objeto de
interés.

\subsubsection*{Ejemplo}\label{ejemplo-2}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Si queremos extraer la letra almacenada en la fila 1 y columna 3 de la
segunda capa de \texttt{miarray} usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{miarray[}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{2}\NormalTok{]  }\CommentTok{# El orden es importante}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "s"
\end{verbatim}

Si queremos extraer la segunda capa completa usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{miarray[,, }\DecValTok{2}\NormalTok{]  }\CommentTok{# No se coloca nada en las primeras posiciones}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,] "m"  "p"  "s"  "v" 
## [2,] "n"  "q"  "t"  "w" 
## [3,] "o"  "r"  "u"  "x"
\end{verbatim}

Si queremos extraer la tercera columna de todas las capas usamos el
siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{miarray[, }\DecValTok{3}\NormalTok{,]  }\CommentTok{# No se coloca nada en las primeras posiciones}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2]
## [1,] "g"  "s" 
## [2,] "h"  "t" 
## [3,] "i"  "u"
\end{verbatim}

\subsection{\texorpdfstring{Marco de datos \index{marco de datos}
\index{data.frame}}{Marco de datos  }}\label{marco-de-datos}

El marco de datos marco de datos o \emph{data frame} es uno de los
objetos más utilizados porque permite agrupar vectores con información
de diferente tipo (numérica, alfanumérica o lógica) en un mismo objeto,
la única restricción es que los vectores deben tener la misma longitud.
Para crear un marco de datos se usa la función \texttt{data.frame(\ )},
como ejemplo vamos a crear un marco de datos con los vectores
\texttt{edad}, \texttt{deporte} y \texttt{comic.fav} definidos
anteriormente.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(edad, deporte, comic.fav)}
\end{Highlighting}
\end{Shaded}

Una vez creado el objeto \texttt{mimarco} podemos ver el objeto
escribiendo su nombre en la consola, a continuación se muestra lo que se
obtiene.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   edad deporte comic.fav
## 1   15    TRUE      <NA>
## 2   19    TRUE  Superman
## 3   13      NA    Batman
## 4   NA   FALSE      <NA>
## 5   20    TRUE    Batman
\end{verbatim}

De la salida anterior vemos que el marco de datos tiene 3 variables
(columnas) cuyos nombres coinciden con los nombres de los vectores
creados anteriormente, los números consecutivos al lado izquierdo son
sólo de referencia y permiten identificar la información para cada
persona en la base de datos.

\subsubsection{¿Cómo extraer elementos de un marco de
datos?}\label{como-extraer-elementos-de-un-marco-de-datos}

Para recuperar las variables (columnas) almacenadas en un marco de datos
se puede usar el operador \texttt{\$}, corchetes simples \texttt{{[}{]}}
o corchetes dobles \texttt{{[}{[}{]}{]}}. A continuación algunos
ejemplos para entender las diferencias entre estas opciones.

\subsubsection*{Ejemplo}\label{ejemplo-3}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Si queremos extraer la variable \texttt{deporte} del marco de datos
\texttt{mimarco} como un vector usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco}\OperatorTok{$}\NormalTok{deporte  }\CommentTok{# Se recomienda si el nombre es corto}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  TRUE  TRUE    NA FALSE  TRUE
\end{verbatim}

Otra forma de recuperar la variable \texttt{deporte} como vector es
indicando el número de la columna donde se encuentra la variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco[, }\DecValTok{2}\NormalTok{]  }\CommentTok{# Se recomienda si recordamos su ubicacion}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  TRUE  TRUE    NA FALSE  TRUE
\end{verbatim}

Otra forma de extraer la variable \texttt{deporte} como vector es usando
\texttt{{[}{[}{]}{]}} y dentro el nombre de la variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco[[}\StringTok{"deporte"}\NormalTok{]]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  TRUE  TRUE    NA FALSE  TRUE
\end{verbatim}

Si usamos \texttt{mimarco{[}"deporte"{]}} el resultado es la variable
\texttt{deporte} pero en forma de marco de datos, no en forma vectorial.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco[}\StringTok{"deporte"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   deporte
## 1    TRUE
## 2    TRUE
## 3      NA
## 4   FALSE
## 5    TRUE
\end{verbatim}

Si queremos extraer un marco de datos sólo con las variables deporte y
edad podemos usar el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco[}\KeywordTok{c}\NormalTok{(}\StringTok{"deporte"}\NormalTok{, }\StringTok{"edad"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   deporte edad
## 1    TRUE   15
## 2    TRUE   19
## 3      NA   13
## 4   FALSE   NA
## 5    TRUE   20
\end{verbatim}

Por otra, si queremos la \texttt{edad} de las personas que están en las
posiciones 2 hasta 4 usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mimarco[}\DecValTok{2}\OperatorTok{:}\DecValTok{4}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19 13 NA
\end{verbatim}

\subsubsection{\texorpdfstring{¿Cómo extraer subconjuntos de un marco de
datos?
\index{subset}}{¿Cómo extraer subconjuntos de un marco de datos? }}\label{como-extraer-subconjuntos-de-un-marco-de-datos}

Para extraer partes de un marco de datos se puede utilizar la función
\texttt{subset(x,\ subset,\ select)}. El parámetro \texttt{x} sirve para
indicar el marco de datos original, el parámetro \texttt{subset} sirve
para colocar la condición y el parámetro \texttt{select} sirve para
quedarnos sólo con algunas de las variables del marco de datos. A
continuación varios ejemplos de la función \texttt{subset} para ver su
utilidad.

\subsubsection*{Ejemplos}\label{ejemplos}
\addcontentsline{toc}{subsubsection}{Ejemplos}

Si queremos el marco de datos \texttt{mimarco} sólo con las personas que
SI practican deporte usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{subset}\NormalTok{(mimarco, }\DataTypeTok{subset=}\NormalTok{deporte }\OperatorTok{==}\StringTok{ }\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   edad deporte comic.fav
## 1   15    TRUE      <NA>
## 2   19    TRUE  Superman
## 5   20    TRUE    Batman
\end{verbatim}

Si queremos el marco de datos \texttt{mimarco} sólo con las personas
mayores o iguales a 17 años usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{subset}\NormalTok{(mimarco, }\DataTypeTok{subset=}\NormalTok{edad }\OperatorTok{>=}\StringTok{ }\DecValTok{17}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   edad deporte comic.fav
## 2   19    TRUE  Superman
## 5   20    TRUE    Batman
\end{verbatim}

Si queremos el submarco con deporte y comic de las personas menores de
20 años usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{subset}\NormalTok{(mimarco, }\DataTypeTok{subset=}\NormalTok{edad }\OperatorTok{<}\StringTok{ }\DecValTok{20}\NormalTok{, }\DataTypeTok{select=}\KeywordTok{c}\NormalTok{(}\StringTok{'deporte'}\NormalTok{, }\StringTok{'comic.fav'}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   deporte comic.fav
## 1    TRUE      <NA>
## 2    TRUE  Superman
## 3      NA    Batman
\end{verbatim}

Si queremos el marco de datos \texttt{mimarco} sólo con las personas
menores de 20 años y que SI practican deporte usamos el siguiente
código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{subset}\NormalTok{(mimarco, }\DataTypeTok{subset=}\NormalTok{edad }\OperatorTok{<}\StringTok{ }\DecValTok{20} \OperatorTok{&}\StringTok{ }\NormalTok{deporte }\OperatorTok{==}\StringTok{ }\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   edad deporte comic.fav
## 1   15    TRUE      <NA>
## 2   19    TRUE  Superman
\end{verbatim}

\subsubsection*{Ejemplo}\label{ejemplo-4}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Leer la base de datos medidas del cuerpo disponible en este enlace
\url{https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo}.
Extraer de esta base de datos una sub-base o subconjunto que contenga
sólo la edad, peso, altura y sexo de aquellos que miden más de 185 cm y
pesan más de 80 kg.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{url <-}\StringTok{ 'https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo'}
\NormalTok{dt1 <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(url, }\DataTypeTok{header=}\NormalTok{T)}
\KeywordTok{dim}\NormalTok{(dt1)  }\CommentTok{# Para conocer la dimensión de la base original}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36  6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dt2 <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(}\DataTypeTok{x=}\NormalTok{dt1, }\DataTypeTok{subset=}\NormalTok{altura }\OperatorTok{>}\StringTok{ }\DecValTok{185} \OperatorTok{&}\StringTok{ }\NormalTok{peso }\OperatorTok{>}\StringTok{ }\DecValTok{80}\NormalTok{,}
              \DataTypeTok{select=}\KeywordTok{c}\NormalTok{(}\StringTok{'sexo'}\NormalTok{, }\StringTok{'edad'}\NormalTok{, }\StringTok{'peso'}\NormalTok{, }\StringTok{'altura'}\NormalTok{))}
\NormalTok{dt2  }\CommentTok{# Para mostrar la base de datos final}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      sexo edad peso altura
## 1  Hombre   43 87.3  188.0
## 6  Hombre   33 85.9  188.0
## 15 Hombre   30 98.2  190.5
\end{verbatim}

Al almacenar la nueva base de datos en el objeto \texttt{dt2} se puede
manipular este nuevo objeto para realizar los análisis de interés.

\subsection{\texorpdfstring{Listas \index{lista}
\index{list}}{Listas  }}\label{listas}

Las listas son otro tipo de objeto muy usado para almacenar objetos de
diferente tipo. La instrucción para crear una lista es
\texttt{list(\ )}. A continuación vamos a crear una lista que contiene
tres objetos: un vector con 5 números aleatorios llamado
\texttt{mivector}, una matriz de dimensión \(6 \times 2\) con los
primeros doce números enteros positivos llamada \texttt{matriz2} y el
tercer objeto será el marco de datos \texttt{mimarco} creado en el
apartado anterior. Las instrucciones para crear la lista requerida se
muestran a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{12345}\NormalTok{)}
\NormalTok{mivector <-}\StringTok{ }\KeywordTok{runif}\NormalTok{(}\DataTypeTok{n=}\DecValTok{5}\NormalTok{)}
\NormalTok{matriz2 <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{data=}\DecValTok{1}\OperatorTok{:}\DecValTok{12}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{6}\NormalTok{)}
\NormalTok{milista <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{E1=}\NormalTok{mivector, }\DataTypeTok{E2=}\NormalTok{matriz2, }\DataTypeTok{E3=}\NormalTok{mimarco)}
\end{Highlighting}
\end{Shaded}

La función \texttt{set.seed} de la línea número 1 sirve para fijar la
semilla de tal manera que los números aleatorios generados en la segunda
línea con la función \texttt{runif} sean siempre los mismos. En la
última línea del código anterior se construye la lista, dentro de la
función \texttt{list} se colocan los tres objetos \texttt{mivector},
\texttt{matriz2} y \texttt{mimarco}. Es posible colocarle un nombre
especial a cada uno de los elementos de la lista, en este ejemplo se
colocaron los nombres \texttt{E1}, \texttt{E2} y \texttt{E3} para cada
uno de los tres elementos. Para observar lo que quedó almacenado en la
lista se escribe \texttt{milista} en la consola y el resultado se
muestra a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{milista}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $E1
## [1] 0.7209 0.8758 0.7610 0.8861 0.4565
## 
## $E2
##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    1    3    5    7    9   11
## [2,]    2    4    6    8   10   12
## 
## $E3
##   edad deporte comic.fav
## 1   15    TRUE      <NA>
## 2   19    TRUE  Superman
## 3   13      NA    Batman
## 4   NA   FALSE      <NA>
## 5   20    TRUE    Batman
\end{verbatim}

\subsubsection{¿Cómo extraer elementos de una
lista?}\label{como-extraer-elementos-de-una-lista}

Para recuperar los elementos almacenadas en una lista se usa el operador
\texttt{\$}, corchetes dobles \texttt{{[}{[}{]}{]}} o corchetes
sencillos \texttt{{[}{]}}. A continuación unos ejemplos para entender
cómo extraer elementos de una lista.

\subsubsection*{Ejemplos}\label{ejemplos-1}
\addcontentsline{toc}{subsubsection}{Ejemplos}

Si queremos la matriz almacenada con el nombre de \texttt{E2} dentro del
objeto \texttt{milista} se puede usar el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{milista}\OperatorTok{$}\NormalTok{E2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    1    3    5    7    9   11
## [2,]    2    4    6    8   10   12
\end{verbatim}

Es posible indicar la posición del objeto en lugar del nombre, para eso
se usan los corchetes dobles.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{milista[[}\DecValTok{2}\NormalTok{]]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    1    3    5    7    9   11
## [2,]    2    4    6    8   10   12
\end{verbatim}

El resultado obtenido con \texttt{milista\$E2} y
\texttt{milista{[}{[}2{]}{]}} es \textbf{exactamente} el mismo. Vamos
ahora a solicitar la posición 2 pero usando corchetes sencillos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{milista[}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $E2
##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    1    3    5    7    9   11
## [2,]    2    4    6    8   10   12
\end{verbatim}

La apariencia de este último resultado es similar, no igual, al
encontrado al usar \texttt{\$} y \texttt{{[}{[}{]}{]}}. Para ver la
diferencia vamos a pedir la clase a la que pertenecen los tres últimos
objetos usando la función \texttt{class}. A continuación el código
usado.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(milista}\OperatorTok{$}\NormalTok{E2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "matrix"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(milista[[}\DecValTok{2}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "matrix"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(milista[}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "list"
\end{verbatim}

De lo anterior se observa claramente que cuando usamos \texttt{\$} o
\texttt{{[}{[}{]}{]}} el resultado es el objeto almacenado, una matriz.
Cuando usamos \texttt{{[}{]}} el resultado es una \textbf{lista} cuyo
contenido es el objeto almacendado.

\BeginKnitrBlock{rmdwarning}
Al manipular listas con \texttt{\$} y \texttt{{[}{[}{]}{]}} se obtienen
los objetos ahí almacenados, al manipular listas con \texttt{{[}{]}} se
obtiene una lista.
\EndKnitrBlock{rmdwarning}

\subsection*{EJERCICIOS}\label{ejercicios}
\addcontentsline{toc}{subsection}{EJERCICIOS}

Use funciones o procedimientos (varias líneas) de R para responder cada
una de las siguientes preguntas.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Construya un vector con la primeras 20 letras MAYÚSCULAS usando la
  función LETTERS.
\item
  Construya una matriz de \(10 \times 10\) con los primeros 100 números
  positivos pares.
\item
  Construya una matriz identidad de dimension \(3 \times 3\). Recuerde
  que una matriz identidad tiene sólo unos en la diagonal principal y
  los demás elementos son cero.
\item
  Construya una lista con los anteriores tres objetos creados.
\item
  Construya un marco de datos o data frame con las respuestas de 3
  personas a las preguntas: (a) ¿Cuál es su edad en años? (b) ¿Tipo de
  música que más le gusta? (c) ¿Tiene usted pareja sentimental estable?
\item
  ¿Cuál es el error al correr el siguiente código? ¿A qué se debe?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edad <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{15}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{13}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\DecValTok{20}\NormalTok{)}
\NormalTok{deporte <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OtherTok{TRUE}\NormalTok{, }\OtherTok{TRUE}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\OtherTok{FALSE}\NormalTok{, }\OtherTok{TRUE}\NormalTok{)}
\NormalTok{comic.fav <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\StringTok{'Superman'}\NormalTok{, }\StringTok{'Batman'}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\StringTok{'Batman'}\NormalTok{)}
\KeywordTok{matrix}\NormalTok{(edad, deporte, comic.fav)}
\end{Highlighting}
\end{Shaded}

\section{Guía de estilo}\label{estilo}

Así como en el español existen reglas ortográficas, la escritura de
códigos en R también tiene unas reglas que se recomienda seguir para
evitar confusiones. Tener una buena guía de estilo
\index{guía de estilo} es importante para que el código creado por usted
sea fácilmente entendido por sus lectores \citep{rpackages}. No existe
una única y mejor guía de estilo para escritura en R, sin embargo aquí
vamos a mostrar unas sugerencias basadas en la guía llamada
\href{https://google.github.io/styleguide/Rguide.xml}{\textit{Google's R style guide}}.

\subsection{Nombres de los archivos}\label{nombres-de-los-archivos}

Se sugiere que el nombre usado para nombrar un archivo tenga sentido y
que termine con extensión .R. A continuación dos ejemplos de como
nombrar mal y bien un archivo.

\begin{itemize}
\tightlist
\item
  Bien: \texttt{hola.R}
\item
  Mal: \texttt{analisis\_icfes.R}
\end{itemize}

\subsection{Nombres de los objetos}\label{nombres-de-los-objetos}

Se recomienda no usar los símbolos \texttt{\_} y \texttt{-} dentro de
los nombres de objetos. Para las variables es preferible usar letras
minúsculas y separar las palabras con puntos (\texttt{peso.maiz}) o
utilizar la notación camello iniciando en minúscula (\texttt{pesoMaiz}).
Para las funciones se recomienda usar la notación camello iniciando
todas la palabras en mayúscula (\texttt{PlotRes}). Para los nombres de
las constantes se recomienda que inicien con la letra k
(\texttt{kPrecioBus}). A continuación ejemplos de buenas y malas
prácticas.

Para variables:

\begin{itemize}
    \item Bien: \verb|avg.clicks|
    \item Aceptable: \verb|avgClicks|
    \item Mal: \verb|avg_Clicks|
\end{itemize}

Para funciones:

\begin{itemize}
    \item Bien: \verb|CalculateAvgClicks| 
    \item Mal: \verb|calculate_avg_clicks| , \verb|calculateAvgClicks|
\end{itemize}

\subsection{Longitud de una línea de
código}\label{longitud-de-una-linea-de-codigo}

Se recomienda que cada línea tenga como máximo 80 caracteres. Si una
línea es muy larga se debe cortar siempre por una coma.

\subsection{Espacios}\label{espacios}

Use espacios alrededor de todos los operadores binarios (=, +, -,
\textless{}-, etc.). Los espacios alrededor del símbolo ``='' son
opcionales cuando se usan para ingresar valores dentro de una función.
Así como en español, nunca coloque espacio antes de una coma, pero
siempre use espacio luego de una coma. A continuación ejemplos de buenas
y malas prácticas.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tab <-}\StringTok{ }\KeywordTok{table}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{days }\OperatorTok{<}\StringTok{ }\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{])  }\CommentTok{# Bien}
\NormalTok{tot <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(x[, }\DecValTok{1}\NormalTok{])                }\CommentTok{# Bien}
\NormalTok{tot <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(x[}\DecValTok{1}\NormalTok{, ])                }\CommentTok{# Bien}
\NormalTok{tab <-}\StringTok{ }\KeywordTok{table}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{days}\OperatorTok{<}\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{])    }\CommentTok{# Faltan espacios alrededor '<' }
\NormalTok{tab <-}\StringTok{ }\KeywordTok{table}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{days }\OperatorTok{<}\StringTok{ }\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{])   }\CommentTok{# Falta espacio luego de coma}
\NormalTok{tab <-}\StringTok{ }\KeywordTok{table}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{days }\OperatorTok{<}\StringTok{ }\DecValTok{0}\NormalTok{ , }\DecValTok{2}\NormalTok{]) }\CommentTok{# Sobra espacio antes de coma}
\NormalTok{tab<-}\StringTok{ }\KeywordTok{table}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{days }\OperatorTok{<}\StringTok{ }\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{])   }\CommentTok{# Falta espacio antes de '<-'}
\NormalTok{tab<-}\KeywordTok{table}\NormalTok{(df[df}\OperatorTok{$}\NormalTok{days }\OperatorTok{<}\StringTok{ }\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{])    }\CommentTok{# Falta espacio alrededor de '<-'}
\NormalTok{tot <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(x[,}\DecValTok{1}\NormalTok{])                 }\CommentTok{# Falta espacio luego de coma}
\NormalTok{tot <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(x[}\DecValTok{1}\NormalTok{,])                 }\CommentTok{# Falta espacio luego de coma}
\end{Highlighting}
\end{Shaded}

Otra buena práctica es colocar espacio antes de un paréntesis excepto
cuando se llama una función.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (debug)    }\CommentTok{# Correcto}
\ControlFlowTok{if}\NormalTok{(debug)     }\CommentTok{# Funciona pero no se recomienda}
\KeywordTok{colMeans}\NormalTok{ (x)  }\CommentTok{# Funciona pero no se recomienda}
\end{Highlighting}
\end{Shaded}

Espacios extras pueden ser usados si con esto se mejora la apariencia
del código, ver el ejemplo siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\DataTypeTok{x    =}\NormalTok{ x.coord,}
     \DataTypeTok{y    =}\NormalTok{ data.mat[, }\KeywordTok{MakeColName}\NormalTok{(metric, ptiles[}\DecValTok{1}\NormalTok{], }\StringTok{"roiOpt"}\NormalTok{)],}
     \DataTypeTok{ylim =}\NormalTok{ ylim,}
     \DataTypeTok{xlab =} \StringTok{"dates"}\NormalTok{,}
     \DataTypeTok{ylab =}\NormalTok{ metric,}
     \DataTypeTok{main =}\NormalTok{ (}\KeywordTok{paste}\NormalTok{(metric, }\StringTok{" for 3 samples "}\NormalTok{, }\DataTypeTok{sep =} \StringTok{""}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

No coloque espacios alrededor del código que esté dentro de paréntesis
\texttt{(\ )} o corchetes \texttt{{[}\ {]}}, la única excepción es luego
de una coma, ver el ejemplo siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (condicion)    }\CommentTok{# Correcto }
\NormalTok{x[}\DecValTok{1}\NormalTok{, ]            }\CommentTok{# Correcto}
\ControlFlowTok{if}\NormalTok{ ( condicion )  }\CommentTok{# Sobran espacios alrededor de condicion}
\NormalTok{x[}\DecValTok{1}\NormalTok{,]             }\CommentTok{# Se necesita espacio luego de coma}
\end{Highlighting}
\end{Shaded}

Los signos de agrupación llaves \texttt{\{\ \}} se utilizan para agrupar
bloques de código y se recomienda que nunca una llave abierta
\texttt{\{} esté sola en una línea; una llave cerrada \texttt{\}} si
debe ir sola en su propia línea. Se pueden omitir las llaves cuando el
bloque de instrucciones esté formado por una sola línea pero esa línea
de código NO debe ir en la misma línea de la condición. A continuación
dos ejemplos de lo que se recomienda.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.null}\NormalTok{(ylim)) \{                     }\CommentTok{# Correcto}
\NormalTok{  ylim <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.06}\NormalTok{)}
\NormalTok{\}}

\ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.null}\NormalTok{(ylim))                       }\CommentTok{# Correcto}
\NormalTok{  ylim <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.06}\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.null}\NormalTok{(ylim)) ylim <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.06}\NormalTok{)    }\CommentTok{# Aceptable}

\ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.null}\NormalTok{(ylim))                       }\CommentTok{# No se recomienda}
\NormalTok{\{        }
\NormalTok{  ylim <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.06}\NormalTok{)}
\NormalTok{\}}
    
\ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.null}\NormalTok{(ylim)) \{ylim <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.06}\NormalTok{)\}}
\CommentTok{# Frente a la llave \{ no debe ir nada}
\CommentTok{# la llave de cierre \} debe ir sola}
\end{Highlighting}
\end{Shaded}

La sentencia else debe ir siempre entre llaves \texttt{\}\ \{}, ver el
siguiente ejemplo.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (condition) \{         }
\NormalTok{  one or more lines}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{                 }\CommentTok{# Correcto}
\NormalTok{  one or more lines}
\NormalTok{\}}


\ControlFlowTok{if}\NormalTok{ (condition) \{         }
\NormalTok{  one or more lines}
\NormalTok{\}}
\ControlFlowTok{else}\NormalTok{ \{                   }\CommentTok{# Incorrecto}
\NormalTok{  one or more lines}
\NormalTok{\}}


\ControlFlowTok{if}\NormalTok{ (condition)           }
\NormalTok{  one line}
\ControlFlowTok{else}                     \CommentTok{# Incorrecto}
\NormalTok{  one line}
\end{Highlighting}
\end{Shaded}

\subsection{Asignación}\label{asignacion}

Para realizar asignaciones se recomienda usar el símbolo
\texttt{\textless{}-}, el símbolo de igualdad \texttt{=} no se
recomienda usarlo para asignaciones.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\DecValTok{5}  \CommentTok{# Correcto}
\NormalTok{x =}\StringTok{ }\DecValTok{5}   \CommentTok{# No recomendado}
\end{Highlighting}
\end{Shaded}

Para una explicación más detallada sobre el símbolo de asignación se
recomienda visitar este
\href{http://www.win-vector.com/blog/2016/12/the-case-for-using-in-r/}{enlace}.

\subsection{Punto y coma}\label{punto-y-coma}

No se recomienda colocar varias instrucciones separadas por \texttt{;}
en la misma línea, aunque funciona dificulta la revisión del código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\DecValTok{100}\NormalTok{; y <-}\StringTok{ }\KeywordTok{rnorm}\NormalTok{(n, }\DataTypeTok{mean=}\DecValTok{5}\NormalTok{); }\KeywordTok{hist}\NormalTok{(y)  }\CommentTok{# No se recomienda}

\NormalTok{n <-}\StringTok{ }\DecValTok{100}                                  \CommentTok{# Correcto}
\NormalTok{y <-}\StringTok{ }\KeywordTok{rnorm}\NormalTok{(n, }\DataTypeTok{mean=}\DecValTok{5}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

A pesar de la anterior advertencia es posible que en este libro usemos
el \texttt{;} en algunas ocasiones, si lo hacemos es para ahorrar
espacio en la presentación del código.

\section{Creación de funciones en R}\label{creafun}

En este capítulo se explica cómo crear funciones en R.

\subsection{\texorpdfstring{Función en R
\index{función}}{Función en R }}\label{funcion-en-r}

Una función es un conjunto de instrucciones que convierten las entradas
(\emph{inputs}) en resultados (\emph{outputs}) deseados. En la Figura
\ref{fig:machine2} se muestra una ilustración de lo que es una función o
máquina general.

\begin{figure}

{\centering \includegraphics{images/function_machine} 

}

\caption{Ilustración de una función, tomada de www.mathinsight.org}\label{fig:machine2}
\end{figure}

\subsection{\texorpdfstring{Partes de una función en R
\index{partes de función}}{Partes de una función en R }}\label{partes-de-una-funcion-en-r}

Las partes de una función son:

\begin{itemize}
\tightlist
\item
  Entradas: o llamadas también \textbf{argumentos}, sirven para ingresar
  información necesaria para realizar el procedimiento de la función.
  Los argumentos pueden estar vacíos y a la espera de que el usuario
  ingrese valores, o pueden tener valores por defecto, esto significa
  que si el usuario no ingresa una valor al función usará el valor por
  defecto. Una función puede tener o no argumentos de entrada, en los
  ejemplos se mostrarán estos casos.
\item
  Cuerpo: el cuerpo de la función está formado por un conjunto de
  instrucciones que transforman las entradas en las salidas deseadas. Si
  el cuerpo de la función está formado por varias instrucciones éstas
  deben ir entre llaves.
\item
  Salidas: son los resultados de la función. Toda función debe tener al
  menos un resultado, si una función no genera un resultado entonces no
  sirve para nada. Si una función entrega varios tipos de objetos se
  acostumbra a organizarlos en una lista que puede manejar los
  diferentes tipos de objetos.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nombre_de_funcion <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(par1, par2, ...) \{}
\NormalTok{  cuerpo}
\NormalTok{  cuerpo}
\NormalTok{  cuerpo}
\NormalTok{  cuerpo}
  \KeywordTok{return}\NormalTok{(resultado)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

A continuación se mostrarán varios ejemplos \textbf{sencillos} para que
el lector aprenda a construir funciones.

\subsubsection*{Ejemplo}\label{ejemplo-5}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Construir una función que reciba dos números y que entregue la suma de
estos números.

Lo primero es elegir un nombre apropiado para la función, aquí se usó el
nombre \texttt{suma} porque así se tiene una idea clara de lo que hace
la función. La función suma recibe dos parámetros, \texttt{x} representa
el primer valor ingresado mientras que \texttt{y} representa el segundo.
El cuerpo de la función está formado por dos líneas, en la primera se
crea el objeto \texttt{resultado} en el cual se almanacena el valor de
la suma, en la segunda línea se le indica a R que queremos que retorne
el valor de la suma almacenada en el objeto \texttt{resultado}. A
continuación se muestra el código para crear la función solicitada.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suma <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, y) \{}
\NormalTok{  resultado <-}\StringTok{ }\NormalTok{x }\OperatorTok{+}\StringTok{ }\NormalTok{y}
  \KeywordTok{return}\NormalTok{(resultado)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Para usar la función creada sólo se debe ejecutar, vamos a obtener la
suma de los valores 4 y 6 usando la función \texttt{suma}, a
continuación el código necesario.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{suma}\NormalTok{(}\DataTypeTok{x=}\DecValTok{4}\NormalTok{, }\DataTypeTok{y=}\DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

Para funciones simples como la anterior es posible escribirlas en forma
más compacta. Es posible reducir el cuerpo de la función de 2 líneas a
sólo una línea solicitándole a R que retorne directamente la suma sin
almacenarla en ningún objeto. A continuación la función \texttt{suma}
modificada.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suma <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, y) \{}
  \KeywordTok{return}\NormalTok{(x }\OperatorTok{+}\StringTok{ }\NormalTok{y)}
\NormalTok{\}}

\KeywordTok{suma}\NormalTok{(}\DataTypeTok{x=}\DecValTok{4}\NormalTok{, }\DataTypeTok{y=}\DecValTok{6}\NormalTok{)  }\CommentTok{# Probando la función}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

Debido a que la función \texttt{suma} tiene un cuerpo muy reducido es
posible escribirla en forma más compacta, en una sola línea. A
continuación se muestra el código para reescribir la función.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suma <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, y) x }\OperatorTok{+}\StringTok{ }\NormalTok{y}

\KeywordTok{suma}\NormalTok{(}\DataTypeTok{x=}\DecValTok{4}\NormalTok{, }\DataTypeTok{y=}\DecValTok{6}\NormalTok{)  }\CommentTok{# Probando la función}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

\subsubsection*{Ejemplo}\label{ejemplo-6}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Construir una función que genere números aleatorios entre cero y uno
hasta que la suma de éstos números supere por primera vez el valor de 3.
La función debe entregar la cantidad de números aleatorios generados
para que se cumpla la condición.

Vamos a llamar la función solicitada con el nombre \texttt{fun1}, esta
función \textbf{NO} necesita ningún parámetro de entrada. El valor de 3
que está en la condición puede ir dentro del cuerpo y por eso no se
necesitan parámetros para esta función. En el cuerpo de la función se
genera un vector con un número aleatorio y luego se chequea si la suma
de sus elementos es menor de 3, si se cumple que la suma es menor que 3
se siguen generando números que se almacenan en el vector \texttt{num}.
Una vez que la suma exceda el valor de 3 NO se ingresa al \texttt{while}
y se pide la longitud del vector o el valor de \texttt{veces}
solicitado. A continuación el código de la función.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fun1 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
\NormalTok{  num <-}\StringTok{ }\KeywordTok{runif}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{  veces <-}\StringTok{ }\DecValTok{1}
  \ControlFlowTok{while}\NormalTok{ (}\KeywordTok{sum}\NormalTok{(num) }\OperatorTok{<}\StringTok{ }\DecValTok{3}\NormalTok{) \{}
\NormalTok{    veces <-}\StringTok{ }\NormalTok{veces }\OperatorTok{+}\StringTok{ }\DecValTok{1}
\NormalTok{    num[veces] <-}\StringTok{ }\KeywordTok{runif}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{  \}}
  \KeywordTok{return}\NormalTok{(veces)}
\NormalTok{\}}

\KeywordTok{fun1}\NormalTok{()  }\CommentTok{# primera prueba}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

\subsubsection*{Ejemplo}\label{ejemplo-7}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Construir una función que, dado un número entero positivo (cota)
ingresado por el usuario, genere números aleatorios entre cero y uno
hasta que la suma de los números generados exceda por primera vez la
cota. La función debe entregar un vector con los números aleatorios, la
suma y la cantidad de números aleatorios. Si el usuario no ingresa el
valor de la cota, se debe asumir igual a 1.

La función aquí solicitada es similar a la construída en el ejemplo
anterior. La función \texttt{fun2} tiene un sólo parámetro con el valor
por defecto, si el usuario no ingresa valor a este parámetro, se asumirá
el valor de uno. El cuerpo de la función es similar al anterior. Como la
función debe entregar un vector y dos números, se construye la lista
\texttt{resultado} que almacena los tres objetos solicitados. A
continuación el código para función solicitada.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fun2 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(}\DataTypeTok{cota=}\DecValTok{1}\NormalTok{) \{}
\NormalTok{  num <-}\StringTok{ }\KeywordTok{runif}\NormalTok{(}\DecValTok{1}\NormalTok{)}
  \ControlFlowTok{while}\NormalTok{ (}\KeywordTok{sum}\NormalTok{(num) }\OperatorTok{<}\StringTok{ }\NormalTok{cota) \{}
\NormalTok{    num <-}\StringTok{ }\KeywordTok{c}\NormalTok{(num, }\KeywordTok{runif}\NormalTok{(}\DecValTok{1}\NormalTok{))}
\NormalTok{  \}}
\NormalTok{  resultado <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{vector=}\NormalTok{num,}
                    \DataTypeTok{suma=}\KeywordTok{sum}\NormalTok{(num),}
                    \DataTypeTok{cantidad=}\KeywordTok{length}\NormalTok{(num))}
  \KeywordTok{return}\NormalTok{(resultado)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Probando la función con cota de uno.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fun2}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $vector
## [1] 0.001137 0.391203 0.462495 0.388144
## 
## $suma
## [1] 1.243
## 
## $cantidad
## [1] 4
\end{verbatim}

Probando la función con cota de tres.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fun2}\NormalTok{(}\DataTypeTok{cota=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $vector
## [1] 0.4025 0.1790 0.9517 0.4537 0.3268 0.9654
## 
## $suma
## [1] 3.279
## 
## $cantidad
## [1] 6
\end{verbatim}

\subsubsection*{Ejemplo}\label{ejemplo-8}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Construya una función que reciba dos números de la recta real y que
entregue el punto médio de estos números. El resultado debe ser un
mensaje por pantalla.

El punto médio entre dos valores es la suma de los números divido entre
dos. La función \texttt{cat} sirve para concatenar objetos y
presentarlos por pantalla. A continuación el código para la función
requerida.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{medio <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(a, b) \{}
\NormalTok{  medio <-}\StringTok{ }\NormalTok{(a }\OperatorTok{+}\StringTok{ }\NormalTok{b) }\OperatorTok{/}\StringTok{ }\DecValTok{2}
  \KeywordTok{cat}\NormalTok{(}\StringTok{"El punto medio de los valores"}\NormalTok{,}
\NormalTok{      a, }\StringTok{"y"}\NormalTok{, b,}
      \StringTok{"ingresados es"}\NormalTok{, medio)}
\NormalTok{\}}

\KeywordTok{medio}\NormalTok{(}\DataTypeTok{a=}\OperatorTok{-}\DecValTok{3}\NormalTok{, }\DataTypeTok{b=}\OperatorTok{-}\DecValTok{1}\NormalTok{)  }\CommentTok{# Probando la función}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## El punto medio de los valores -3 y -1 ingresados es -2
\end{verbatim}

\BeginKnitrBlock{rmdnote}
La función \texttt{cat} es muy útil para presentar resultados por
pantalla. Consulte la ayuda de la función para ver otros ejemplos.
\EndKnitrBlock{rmdnote}

\subsection*{EJERCICIOS}\label{ejercicios-1}
\addcontentsline{toc}{subsection}{EJERCICIOS}

Construir funciones en R que realicen lo solicitado.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Construya una función que reciba dos números reales \texttt{a} y
  \texttt{b}, la función debe decir cuál es el mayor de ellos.
\item
  Escriba una función llamada \texttt{media} que calcule la media
  muestral de un vector numérico \texttt{x} ingresado a la función. A
  continuación la fórmula para calcular la media muestral.
\end{enumerate}

\[\bar{x}=\frac{\sum_{i=1}^n x_i}{n}\]

Nota: no puede usar la función \texttt{mean(\ )}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  Construya una función que encuentre las raíces de una ecuación de
  segundo grado. El usuario debe suministrar los coeficientes
  \texttt{a}, \texttt{b} y \texttt{c} de la ecuación \(ax^2+bx+c=0\) y
  la función debe entregar las raíces.
\item
  Escribir una función que calcule la velocidad de un proyectil dado que
  el usuario ingresa la distancia recorrida en Km y el tiempo necesario
  en minutos. Expresar el resultado se debe entregar en metros/segundo,
  recuerde que
\end{enumerate}

\[velocidad = \frac{espacio}{tiempo}\] 5. Escribir una función que
reciba dos valores \(a\) y \(b\) y que los intercambie. Es decir, si
ingresa \(a=4\) y \(b=9\) que la función entregue \(a=9\) y \(b=4\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  Construya una función a la cual le ingrese el salario por hora y el
  número de horas trabajadas durante una semana por un trabajador. La
  función debe calcular el salario neto.
\item
  Construya una función llamada \texttt{precio} que calcule el precio
  total de sacar A fotocopias y B impresiones, sabiendo que los precios
  son 50 y 100 pesos para A y B respectivamente si el cliente es un
  estudiante, y de 75 y 150 para A y B si el cliente es un profesor. La
  función debe tener dos argumentos cuantitativos (\texttt{A} y
  \texttt{B}) y el argumento lógico \texttt{estudiante} que por defecto
  tenga el valor de \texttt{TRUE}. Use la estructura mostrada abajo.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{precio <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(A, B, }\DataTypeTok{estudiante=}\OtherTok{TRUE}\NormalTok{) \{}
\NormalTok{  ...}
\NormalTok{  ...}
\NormalTok{  ...}
  \KeywordTok{return}\NormalTok{(precio.total)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Construya una función llamada \texttt{salario} que le ingrese el
  salario por hora y el número de horas trabajadas durante una semana
  por un trabajador. La función debe calcular el salario neto semanal,
  teniendo en cuenta que si el número de horas trabajadas durante la
  semana es mayor de 48, esas horas de demás se consideran horas extras
  y tienen un 35\% de recargo. Imprima el salario neto. Use la
  estructura mostrada abajo.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{salario <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(num.horas, valor.hora) \{}
\NormalTok{  ...}
\NormalTok{  ...}
\NormalTok{  ...}
  \KeywordTok{return}\NormalTok{(salario.neto)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Construya una función llamada \texttt{nota} que calcule la nota
  obtenida por un alumno en una evaluación de tres puntos cuya
  ponderación o importancia son 20\%, 30\% y 50\% para los puntos I, II
  y III respectivamente. Adicionalmente la función debe generar un
  mensaje sobre si el estudiante aprobó la evaluación o no. El usuario
  debe ingresar las notas individuales de los tres puntos y la función
  debe entregar la nota final de la evaluación. Use la estructura
  mostrada abajo.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nota <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(p1, p2, p3) \{}
\NormalTok{  ...}
\NormalTok{  ...}
\NormalTok{  ...}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Escriba una función llamada \texttt{minimo} que permita obtener el
  valor mínimo de un vector numérico. No puede usar ninguna de las
  funciones básicas de R como \texttt{which.min()},
  \texttt{which.max()}, \texttt{order()}, \texttt{min(\ )},
  \texttt{max(\ )}, \texttt{sort(\ )} u \texttt{order(\ )}. Use la
  estructura mostrada abajo.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{minimo <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  ...}
\NormalTok{  ...}
  \KeywordTok{return}\NormalTok{(minimo)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Construya una función que calcule las coordenadas del punto medio
  \(M\) entre dos puntos \(A\) y \(B\). Vea la Figura \ref{fig:midpoint}
  para una ilustración. ¿Cuáles cree usted que deben ser los parámetros
  de entrada de la función?
\end{enumerate}

\begin{figure}

{\centering \includegraphics{images/midpoint} 

}

\caption{Ilustración del punto medio entre dos puntos, tomada de https://www.slideshare.net/bigpassy/midpoint-between-two-points}\label{fig:midpoint}
\end{figure}

\section{Lectura de bases de datos}\label{read}

En este capítulo se mostrará cómo leer una base de datos externa hacia
R.

\subsection{\texorpdfstring{¿En qué formato almacenar una base de datos?
\index{.csv}
\index{.txt}}{¿En qué formato almacenar una base de datos?  }}\label{en-que-formato-almacenar-una-base-de-datos}

Usualmente los archivos con la información para ser leídos por R se
pueden almacenar en formato:

\begin{itemize}
\tightlist
\item
  plano con extensión \textbf{.txt} o,
\item
  Excel con extensión \textbf{.csv}.
\end{itemize}

En las secciones siguientes se mostrará cómo almacenar datos en los dos
formatos para ser leídos en R. En el Cuadro \ref{tab:dt1} se presenta
una base de datos pequeña, tres observaciones y tres variables, que nos
servirá como ejemplo para mostrar cómo se debe almacenar la información.

\begin{table}[t]

\caption{\label{tab:dt1}Ejemplo de una base de datos simple.}
\centering
\begin{tabular}{rll}
\toprule
Edad & Fuma & Pais\\
\midrule
35 & TRUE & Colombia\\
46 & TRUE & Francia\\
23 & FALSE & Malta\\
\bottomrule
\end{tabular}
\end{table}

\subsubsection{\texorpdfstring{Almacenamiento de información en Excel
\index{Excel}}{Almacenamiento de información en Excel }}\label{almacenamiento-de-informacion-en-excel}

Para almacenar la información del Cuadro \ref{tab:dt1} en Excel, abrimos
un archivo nuevo archivo de Excel y copiamos la información tal como se
muestra en la Figura \ref{fig:excel1}. Se debe iniciar en la parte
superior izquierda, no se deben dejar filas vacías, no se debe colorear,
no se deben colocar bordes ni nada, se ingresa la información sin
embellecer el contenido. Por último se guarda el archivo en la carpeta
deseada y al momento de nombrar el archivo se debe modificar la opción
tipo de archivo a \textbf{csv (delimitado por comas)}.

\begin{figure}

{\centering \includegraphics{images/excel1} 

}

\caption{Forma de almacenar los datos en Excel.}\label{fig:excel1}
\end{figure}

\BeginKnitrBlock{rmdwarning}
Recuerde que el archivo de Excel se debe guardar con extensión .csv.
\EndKnitrBlock{rmdwarning}

\subsubsection{\texorpdfstring{Almacenamiento de información en bloc de
notas
\index{bloc de notas}}{Almacenamiento de información en bloc de notas }}\label{almacenamiento-de-informacion-en-bloc-de-notas}

Para almacenar la información del Cuadro \ref{tab:dt1} en bloc de notas,
abrimos un archivo nuevo de bloc de notas y copiamos la información tal
como se muestra en la Figura \ref{fig:bloc1}. Se copian los nombres de
las variables o los datos separados por un espacio obtenido con la tecla
tabuladora, cada línea se finaliza con un \emph{enter}. Se recomienda al
guardar el archivo que el cursor al inicio de una línea vacía, en la
Figura \ref{fig:bloc1} se señala la posición del cursor con la flecha
roja, a pesar de que no éxiste línea número 5, el curso debe quedar al
inicio de esa línea número 5.

\begin{figure}

{\centering \includegraphics{images/bloc1} 

}

\caption{Almacenamiento de los datos en bloc de notas usando la barra espaciadora}\label{fig:bloc1}
\end{figure}

Es posible mejorar la apariencia de la información almacenada en el bloc
de notas si, en lugar de usar espacios con la barra espaciadora, se
colocan los espacios con la barra tabuladora, así la información se ve
más organizada y se puede chequear fácilmente la información ingresada.
En la Figura \ref{fig:bloc2} se muestra la información para el ejemplo,
claramente se nota la organización de la información.

\begin{figure}

{\centering \includegraphics{images/bloc2} 

}

\caption{Almacenamiento de los datos en bloc de notas usando la barra tabuladora}\label{fig:bloc2}
\end{figure}

\BeginKnitrBlock{rmdtip}
Una buena práctica es usar la barra tabuladora para separar, eso permite
que la información se vea ordenada.
\EndKnitrBlock{rmdtip}

\subsection{\texorpdfstring{Función \texttt{read.table}
\index{read.table}}{Función read.table }}\label{funcion-read.table}

La función \texttt{read.table} se puede usar para leer bases de datos
hacia R. La estructura de la función con los parámetros más comunes de
uso es la siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{read.table}\NormalTok{(file, header, sep, dec)}
\end{Highlighting}
\end{Shaded}

Los argumentos de la función \texttt{read.table} son:

\begin{itemize}
\tightlist
\item
  \texttt{file}: nombre o ruta donde están alojados los datos. Puede ser
  un url o una dirección del computador. Es también posible usar
  \texttt{file.choose()} para que se abra un ventana y adjuntar el
  archivo deseado manualmente.
\item
  \texttt{header}: valor lógico, se usa \texttt{TRUE} si la primera
  línea de la base de datos tiene los nombres de las variables, caso
  contrario se usa \texttt{FALSE}.
\item
  \texttt{sep}: tipo de separación interna para los datos dentro del
  archivo. Los valores usuales para este parámetros son:

  \begin{itemize}
  \tightlist
  \item
    \texttt{sep=\textquotesingle{},\textquotesingle{}} si el archivo
    tiene extensión .csv.
  \item
    \texttt{sep=\textquotesingle{}\textquotesingle{}} si el archivo es
    bloc de notas con espacios por la barra \textbf{espaciadora}.
  \item
    \texttt{sep=\textquotesingle{}\textbackslash{}t\textquotesingle{}}
    si el archivo es bloc de notas con espacios por la barra
    \textbf{tabuladora}.
  \end{itemize}
\item
  \texttt{dec}: símbolo con el cual están indicados los decimales.
\end{itemize}

\subsubsection*{Ejemplo}\label{ejemplo-9}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Crear la base de datos del Cuadro \ref{tab:dt1} en Excel y bloc de notas
para practicar la lectura de base de datos desde R.

Lo primero que se debe hacer para realizar lo solicitado es construir
tres archivos (uno de Excel y dos bloc de notas) igual a los mostrados
en las figuras \ref{fig:excel1}, \ref{fig:bloc1} y \ref{fig:bloc2},
vamos a suponer que los nombres para cada uno de ellos son
\texttt{base1.csv}, \texttt{base2.txt} y \texttt{base3.txt}
respectivamente.

\paragraph{Para Excel}\label{para-excel}
\addcontentsline{toc}{paragraph}{Para Excel}

Para leer el archivo de Excel llamado \texttt{base1.csv} podemos usar el
siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\StringTok{'C:/Users/Hernandez/Desktop/base1.csv'}\NormalTok{,}
                    \DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{sep=}\StringTok{','}\NormalTok{)}
\NormalTok{datos}
\end{Highlighting}
\end{Shaded}

La dirección
\texttt{file=\textquotesingle{}C:/Users/Hernandez/Desktop/base1.csv\textquotesingle{}}
le indica a R en qué lugar del computador debe buscar el archivo, note
que se debe usar el símbolo \texttt{/} para que sea un dirección válida.
Substituya la dirección del código anterior con la dirección donde se
encuentra su archivo para que pueda leer la base de datos.

Si no se conoce la ubicación del archivo a leer o si la dirección es muy
extensa, se puede usar \texttt{file.choose()} para que se abra una
ventana y así adjuntar manualmente el archivo. A continuación se muestra
el código para hacerlo de esta manera.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\KeywordTok{file.choose}\NormalTok{(), }\DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{sep=}\StringTok{','}\NormalTok{)}
\NormalTok{datos}
\end{Highlighting}
\end{Shaded}

\paragraph{Para bloc de notas con barra
espaciadora}\label{para-bloc-de-notas-con-barra-espaciadora}
\addcontentsline{toc}{paragraph}{Para bloc de notas con barra
espaciadora}

Para leer el archivo de Excel llamado \texttt{base2.txt} podemos usar el
siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\StringTok{'C:/Users/Hernandez/Desktop/base2.txt'}\NormalTok{,}
                    \DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{sep=}\StringTok{''}\NormalTok{)}
\NormalTok{datos}
\end{Highlighting}
\end{Shaded}

\paragraph{Para bloc de notas con barra
tabuladora}\label{para-bloc-de-notas-con-barra-tabuladora}
\addcontentsline{toc}{paragraph}{Para bloc de notas con barra
tabuladora}

Para leer el archivo de Excel llamado \texttt{base3.txt} podemos usar el
siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\StringTok{'C:/Users/Hernandez/Desktop/base3.txt'}\NormalTok{,}
                    \DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{sep=}\StringTok{'}\CharTok{\textbackslash{}t}\StringTok{'}\NormalTok{)}
\NormalTok{datos}
\end{Highlighting}
\end{Shaded}

\BeginKnitrBlock{rmdnote}
El usuario puede usar indiferentemente
\texttt{file=\textquotesingle{}C:/Users/bla/bla\textquotesingle{}} o
\texttt{file.choose()} para ingresar el archivo, con la práctica se
aprende a decidir cuando conviene una u otra forma.
\EndKnitrBlock{rmdnote}

\BeginKnitrBlock{rmdwarning}
Un error frecuente es escribir la dirección o ubicación del archivo
usando \texttt{\textbackslash{}}, lo correcto es usar \texttt{/}.
\EndKnitrBlock{rmdwarning}

\subsubsection*{Ejemplo}\label{ejemplo-10}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Leer la base de datos sobre apartamentos usados en la ciudad de Medellín
que está disponible en la página web cuya url es:
\url{https://raw.githubusercontent.com/fhernanb/datos/master/aptos2015}

Para leer la base de datos desde una url usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{enlace <-}\StringTok{ 'https://raw.githubusercontent.com/fhernanb/datos/master/aptos2015'}
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\NormalTok{enlace, }\DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

La base de datos ingresada queda en el marco de datos llamado
\texttt{datos} y ya está disponible para usarla.

\subsection{Lectura de bases de datos en
Excel}\label{lectura-de-bases-de-datos-en-excel}

Algunas veces los datos están disponibles en un archivo estándar de
Excel, y dentro de cada archivo hojas con la información a utilizar. En
estos casos se recomienda usar el paquete \textbf{readxl}\index{readxl}
\citep{R-readxl} y en particular la función \texttt{readxl}. A
continuación un ejemplo de cómo proceder en estos casos.

\subsubsection*{Ejemplo}\label{ejemplo-11}
\addcontentsline{toc}{subsubsection}{Ejemplo}

En este
\href{https://github.com/fhernanb/datos/blob/master/BD_Excel.xlsx}{enlace}
está disponible un archivo de Excel llamado BD\_Excel.xlxs, una vez se
ha abierto la página donde está alojado el archivo, se debe descargar y
guardar en alguna carpeta. El archivo contiene dos bases de datos muy
pequeñas, en la primera hoja llamada \textbf{Hijos} está la información
de un grupo de niños y en la segunda hoja llamada \textbf{Padres} está
la información de los padres. ¿Cómo se pueden leer las dos bases de
datos?

Lo primero que se debe hacer es instalar el paquete \textbf{readxl}, la
instalación de cualquier paquete en un computador se hace una sola vez y
éste quedará instalado para ser usado las veces que se requiera. La
función para instalar un paquete cualquiera es
\texttt{install.packages}, a continuación se muestra el código necesario
para instalar el paquete \textbf{readxl}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"readxl"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Una vez instalado el paquete es necesario cargarlo, la función para
cargar el paquete en la sesión actual de R es \texttt{library}. La
instrucción para cargar el paquete es la siguiente:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readxl)}
\end{Highlighting}
\end{Shaded}

\BeginKnitrBlock{rmdwarning}
La instalación de un paquete con \texttt{install.packages} se hace sólo
una vez y no más. Cargar el paquete con \texttt{library} en la sesión
actual se debe hacer siempre que se vaya a usar el paquete.
\EndKnitrBlock{rmdwarning}

Luego de haber cargado el paquete \textbf{readxl} se puede usar la
función \texttt{read\_xl} para leer la información contenida en las
hojas. A continuación el código para crear la base de datos
\texttt{hijos} contenida en el archivo BD\_Excel.xlsx.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hijos <-}\StringTok{ }\KeywordTok{read_excel}\NormalTok{(}\KeywordTok{file.choose}\NormalTok{(), }\DataTypeTok{sheet=}\StringTok{'Hijos'}\NormalTok{)}
\KeywordTok{as.data.frame}\NormalTok{(hijos)  }\CommentTok{# Para ver el contenido}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Edad Grado    ComicFav
## 1    8     2    Superman
## 2    6     1      Batman
## 3    9     3      Batman
## 4   10     5 Bob Esponja
## 5    8     4      Batman
## 6    9     4 Bob Esponja
\end{verbatim}

A continuación el código para crear la base de datos \texttt{padres}
contenida en el archivo BD\_Excel.xlsx.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{padres <-}\StringTok{ }\KeywordTok{read_excel}\NormalTok{(}\StringTok{'BD_Excel.xlsx'}\NormalTok{, }\DataTypeTok{sheet=}\StringTok{'Padres'}\NormalTok{)}
\KeywordTok{as.data.frame}\NormalTok{(padres)  }\CommentTok{# Para ver el contenido}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Edad   EstCivil NumHijos
## 1   45    Soltero        1
## 2   50     Casado        0
## 3   35     Casado        3
## 4   65 Divorciado        1
\end{verbatim}

La función \texttt{read\_excel} tiene otros parámetros adicionales
útiles para leer bases de datos, se recomienda consultar la ayuda de la
función escribiendo en la consola \texttt{help(read\_excel)}.

\subsection*{EJERCICIOS}\label{ejercicios-2}
\addcontentsline{toc}{subsection}{EJERCICIOS}

Realice los siguiente ejercicios propuestos.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  En el Cuadro \ref{tab:toy} se presenta una base de datos sencilla.
  Almacene la información del cuadro en dos archivos diferentes, en
  Excel y en bloc de notas. Lea los dos archivos con la función
  \texttt{read.table} y compare los resultados obtenidos con la del
  Cuadro \ref{tab:toy} fuente.
\end{enumerate}

\begin{table}[t]

\caption{\label{tab:toy}Base de datos para practicar lectura.}
\centering
\begin{tabular}{llrr}
\toprule
Fuma & Pasatiempo & Num\_hermanos & Mesada\\
\midrule
Si & Lectura & 0 & 4500\\
Si & NA & 2 & 2600\\
No & Correr & 4 & 1000\\
No & Correr & NA & 3990\\
Si & TV & 3 & 2570\\
\addlinespace
No & TV & 1 & 2371\\
Si & Correr & 1 & 1389\\
NA & Correr & 0 & 4589\\
Si & Lectura & 2 & NA\\
\bottomrule
\end{tabular}
\end{table}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  En la url
  \url{https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo}
  están disponibles los datos sobre medidas corporales para un grupo de
  estudiante de la universidad, use la función \texttt{read.table} para
  leer la base de datos.
\end{enumerate}

\section{Tablas de frecuencia}\label{tablas}

Las tablas de frecuencia son muy utilizadas en estadística y R permite
crear tablas de una forma sencilla. En este capítulo se explican las
principales funciones para la elaboración de tablas.

\subsection{\texorpdfstring{Tabla de contingencia con \texttt{table}
\index{table}}{Tabla de contingencia con table }}\label{tabla-de-contingencia-con-table}

La función \texttt{table} sirve para construir tablas de frecuencia de
una vía, a continuación la estrctura de la función.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(..., exclude, useNA)}
\end{Highlighting}
\end{Shaded}

Los parámetros de la función son:

\begin{itemize}
\tightlist
\item
  \texttt{...} espacio para ubicar los nombres de los objetos (variables
  o vectores) para los cuales se quiere construir la tabla.
\item
  \texttt{exclude}: vector con los niveles a remover de la tabla. Si
  \texttt{exclude=NULL} implica que se desean ver los \texttt{NA}, lo
  que equivale a
  \texttt{useNA\ =\ \textquotesingle{}always\textquotesingle{}}.
\item
  \texttt{useNA}: instrucción de lo que se desea con los \texttt{NA}.
  Hay tres posibles valores para este parámetro:
  \texttt{\textquotesingle{}no\textquotesingle{}} si no se desean usar,
  \texttt{\textquotesingle{}ifany\textquotesingle{}} y
  \texttt{\textquotesingle{}always\textquotesingle{}} si se desean
  incluir.
\end{itemize}

\subsubsection*{Ejemplo: tabla de frecuencia de una
vía}\label{ejemplo-tabla-de-frecuencia-de-una-via}
\addcontentsline{toc}{subsubsection}{Ejemplo: tabla de frecuencia de una
vía}

Considere el vector \texttt{fuma} mostrado a continuación y construya
una tabla de frecuencias absolutas para los niveles de la variable
frecuencia de fumar.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fuma <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'Frecuente'}\NormalTok{, }\StringTok{'Nunca'}\NormalTok{, }\StringTok{'A veces'}\NormalTok{, }\StringTok{'A veces'}\NormalTok{, }\StringTok{'A veces'}\NormalTok{,}
          \StringTok{'Nunca'}\NormalTok{, }\StringTok{'Frecuente'}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\StringTok{'Frecuente'}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\StringTok{'hola'}\NormalTok{, }
          \StringTok{'Nunca'}\NormalTok{, }\StringTok{'Hola'}\NormalTok{, }\StringTok{'Frecuente'}\NormalTok{, }\StringTok{'Nunca'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

A continuación se muestra el código para crear la tabla de frecuencias
para la variable \texttt{fuma}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(fuma)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## fuma
##   A veces Frecuente      hola      Hola     Nunca 
##         3         4         1         1         4
\end{verbatim}

De la tabla anterior vemos que NO aparece el conteo de los \texttt{NA},
para obtenerlo usamos lo siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(fuma, }\DataTypeTok{useNA=}\StringTok{'always'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## fuma
##   A veces Frecuente      hola      Hola     Nunca 
##         3         4         1         1         4 
##      <NA> 
##         2
\end{verbatim}

Vemos que hay dos niveles errados en la tabla anterior, \texttt{Hola} y
\texttt{hola}. Para construir la tabla sin esos niveles errados usamos
lo siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(fuma, }\DataTypeTok{exclude=}\KeywordTok{c}\NormalTok{(}\StringTok{'Hola'}\NormalTok{, }\StringTok{'hola'}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## fuma
##   A veces Frecuente     Nunca      <NA> 
##         3         4         4         2
\end{verbatim}

Por último construyamos la tabla sin los niveles errados y los
\texttt{NA}, a esta última tabla la llamaremos \texttt{tabla1} para
luego poder usarla. Las instrucciones para hacer esto son las
siguientes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla1 <-}\StringTok{ }\KeywordTok{table}\NormalTok{(fuma, }\DataTypeTok{exclude=}\KeywordTok{c}\NormalTok{(}\StringTok{'Hola'}\NormalTok{, }\StringTok{'hola'}\NormalTok{, }\OtherTok{NA}\NormalTok{))}
\NormalTok{tabla1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## fuma
##   A veces Frecuente     Nunca 
##         3         4         4
\end{verbatim}

\BeginKnitrBlock{rmdnote}
Al crear una tabla con la instrucción \texttt{table(var1,\ var2)}, la
variable 1 quedará por filas mientras que la variable 2 estará en las
columnas.
\EndKnitrBlock{rmdnote}

\subsubsection*{Ejemplo: tabla de frecuencia de dos
vías}\label{ejemplo-tabla-de-frecuencia-de-dos-vias}
\addcontentsline{toc}{subsubsection}{Ejemplo: tabla de frecuencia de dos
vías}

Considere otro vector \texttt{sexo} mostrado a continuación y construya
una tabla de frecuencias absolutas para ver cómo se relaciona el sexo
con fumar del ejemplo anterior.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sexo <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'Hombre'}\NormalTok{, }\StringTok{'Hombre'}\NormalTok{, }\StringTok{'Hombre'}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{,}
          \StringTok{'Casa'}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{, }\StringTok{'Hombre'}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{, }
          \StringTok{'Hombre'}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{, }\StringTok{'Mujer'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Para construir la tabla solicitada usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(sexo, fuma)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fuma
## sexo     A veces Frecuente hola Hola Nunca
##   Casa         0         0    0    0     1
##   Hombre       1         1    0    0     2
##   Mujer        1         3    1    0     1
\end{verbatim}

De la tabla anterior vemos que aparecen niveles errados en fuma y en
sexo, para retirarlos usamos el siguiente código incluyendo en el
parámetro \texttt{exclude} un vector con los niveles que \textbf{NO}
deseamos en la tabla.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla2 <-}\StringTok{ }\KeywordTok{table}\NormalTok{(sexo, fuma, }\DataTypeTok{exclude=}\KeywordTok{c}\NormalTok{(}\StringTok{'Hola'}\NormalTok{, }\StringTok{'hola'}\NormalTok{, }\StringTok{'Casa'}\NormalTok{, }\OtherTok{NA}\NormalTok{))}
\NormalTok{tabla2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fuma
## sexo     A veces Frecuente Nunca
##   Hombre       1         1     2
##   Mujer        1         3     1
\end{verbatim}

\subsection{\texorpdfstring{Función \texttt{prop.table}
\index{prop.table}}{Función prop.table }}\label{funcion-prop.table}

La función \texttt{prop.table} se utiliza para crear tablas de
frecuencia relativa a partir de tablas de frecuencia absoluta, la
estructura de la función se muestra a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(x, }\DataTypeTok{margin=}\OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{x}: tabla de frecuencia.
\item
  \texttt{margin}: valor de 1 si se desean proporciones por filas, 2 si
  se desean por columnas, \texttt{NULL} si se desean frecuencias
  globales.
\end{itemize}

\subsubsection*{Ejemplo: tabla de frecuencia relativa de una
vía}\label{ejemplo-tabla-de-frecuencia-relativa-de-una-via}
\addcontentsline{toc}{subsubsection}{Ejemplo: tabla de frecuencia
relativa de una vía}

Obtener la tabla de frencuencia relativa para la \texttt{tabla1}.

Para obtener la tabla solicitada se usa el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\DataTypeTok{x=}\NormalTok{tabla1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## fuma
##   A veces Frecuente     Nunca 
##    0.2727    0.3636    0.3636
\end{verbatim}

\subsubsection*{Ejemplo: tabla de frecuencia relativa de dos
vías}\label{ejemplo-tabla-de-frecuencia-relativa-de-dos-vias}
\addcontentsline{toc}{subsubsection}{Ejemplo: tabla de frecuencia
relativa de dos vías}

Obtener la tabla de frencuencia relativa para la \texttt{tabla2}.

Si se desea la tabla de frecuencias relativas global se usa el siguiente
código. El resultado se almacena en el objeto \texttt{tabla3} para ser
usado luego.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla3 <-}\StringTok{ }\KeywordTok{prop.table}\NormalTok{(}\DataTypeTok{x=}\NormalTok{tabla2)}
\NormalTok{tabla3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fuma
## sexo     A veces Frecuente  Nunca
##   Hombre  0.1111    0.1111 0.2222
##   Mujer   0.1111    0.3333 0.1111
\end{verbatim}

Si se desea la tabla de frecuencias relativas marginal por
\textbf{columnas} se usa el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla4 <-}\StringTok{ }\KeywordTok{prop.table}\NormalTok{(}\DataTypeTok{x=}\NormalTok{tabla2, }\DataTypeTok{margin=}\DecValTok{2}\NormalTok{)}
\NormalTok{tabla4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fuma
## sexo     A veces Frecuente  Nunca
##   Hombre  0.5000    0.2500 0.6667
##   Mujer   0.5000    0.7500 0.3333
\end{verbatim}

\subsection{\texorpdfstring{Función \texttt{addmargins}
\index{addmargins}}{Función addmargins }}\label{funcion-addmargins}

Esta función se puede utilizar para agregar los totales por filas o por
columnas a una tabla de frecuencia absoluta o relativa. La estructura de
la función es la siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{addmargins}\NormalTok{(A, margin)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{A}: tabla de frecuencia.
\item
  \texttt{margin}: valor de 1 si se desean proporciones por columnas, 2
  si se desean por filas, \texttt{NULL} si se desean frecuencias
  globales.
\end{itemize}

\subsubsection*{Ejemplo}\label{ejemplo-12}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Obtener las tablas \texttt{tabla3} y \texttt{tabla4} con los totales
margines global y por columnas respectivamente.

Para hacer lo solicitado usamos las siguientes instrucciones.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{addmargins}\NormalTok{(tabla3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fuma
## sexo     A veces Frecuente  Nunca    Sum
##   Hombre  0.1111    0.1111 0.2222 0.4444
##   Mujer   0.1111    0.3333 0.1111 0.5556
##   Sum     0.2222    0.4444 0.3333 1.0000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{addmargins}\NormalTok{(tabla4, }\DataTypeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fuma
## sexo     A veces Frecuente  Nunca
##   Hombre  0.5000    0.2500 0.6667
##   Mujer   0.5000    0.7500 0.3333
##   Sum     1.0000    1.0000 1.0000
\end{verbatim}

\BeginKnitrBlock{rmdwarning}
Note que los valores de 1 y 2 en el parámetro \texttt{margin} de las
funciones \texttt{prop.table} y \texttt{addmargins} significan lo
contrario.
\EndKnitrBlock{rmdwarning}

\subsection{\texorpdfstring{Función \texttt{hist}
\index{hist}}{Función hist }}\label{funcion-hist}

Construir tablas de frecuencias para variables cuantitativas es
necesario en muchos procedimientos estadísticos, la función
\texttt{hist} sirve para obtener este tipo de tablas. La estructura de
la función es la siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(x, }\DataTypeTok{breaks=}\StringTok{'Sturges'}\NormalTok{, }\DataTypeTok{include.lowest=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{right=}\OtherTok{TRUE}\NormalTok{, }
     \DataTypeTok{plot=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Los parámetros de la función son:

\begin{itemize}
\tightlist
\item
  \texttt{x}: vector numérico.
\item
  \texttt{breaks}: vector con los límites de los intervalos. Si no se
  especifica se usar la regla de Sturges para definir el número de
  intervalos y el ancho.
\item
  \texttt{include.lowest}: valor lógico, si \texttt{TRUE} una
  observación \(x_i\) que coincida con un límite de intervalo será
  ubicada en el intervalo izquierdo, si \texttt{FALSE} será incluída en
  el intervalo a la derecha.
\item
  \texttt{right}: valor lógico, si \texttt{TRUE} los intervalos serán
  cerrados a derecha de la forma \((lim_{inf}, lim_{sup}]\), si es
  \texttt{FALSE} serán abiertos a derecha.
\item
  \texttt{plot}: valor lógico, si \texttt{FALSE} sólo se obtiene la
  tabla de frecuencias mientras que con \texttt{TRUE} se obtiene la
  representación gráfica llamada histograma.
\end{itemize}

\subsubsection*{Ejemplo}\label{ejemplo-13}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Genere 200 observaciones aleatorias de una distribución normal con media
\(\mu=170\) y desviación \(\sigma=5\), luego construya una tabla de
frecuencias para la muestra obtenida usando (a) la regla de Sturges y
(b) tres intervalos con límites 150, 170, 180 y 190.

Primero se construye el vector \texttt{x} con las observaciones de la
distribución normal por medio de la función \texttt{rnorm} y se
especifica la media y desviación solicitada. Luego se aplica la función
\texttt{hist} con el parámetro
\texttt{breaks=\textquotesingle{}Sturges\textquotesingle{}}, a
continuación el código utilizado.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\KeywordTok{rnorm}\NormalTok{(}\DataTypeTok{n=}\DecValTok{200}\NormalTok{, }\DataTypeTok{mean=}\DecValTok{170}\NormalTok{, }\DataTypeTok{sd=}\DecValTok{5}\NormalTok{)}

\NormalTok{res1 <-}\StringTok{ }\KeywordTok{hist}\NormalTok{(}\DataTypeTok{x=}\NormalTok{x, }\DataTypeTok{breaks=}\StringTok{'Sturges'}\NormalTok{, }\DataTypeTok{plot=}\OtherTok{FALSE}\NormalTok{)}
\NormalTok{res1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1] 155 160 165 170 175 180 185
## 
## $counts
## [1]  6 17 67 83 26  1
## 
## $density
## [1] 0.006 0.017 0.067 0.083 0.026 0.001
## 
## $mids
## [1] 157.5 162.5 167.5 172.5 177.5 182.5
## 
## $xname
## [1] "x"
## 
## $equidist
## [1] TRUE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

El objeto \texttt{res1} es una lista donde se encuentra la información
de la tabla de frecuencias para \texttt{x}. Esa lista tiene en el
elemento \texttt{breaks} los límites inferior y superior de los
intervalos y en el elemento \texttt{counts} están las frecuencias de
cada uno de los intervalos.

Para obtener las frecuencias de tres intervalos con límites 150, 170,
180 y 190 se especifica en el parámetros \texttt{breaks} los límites. El
código para obtener la segunda tabla de frecuencias se muestra a
continuación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res2 <-}\StringTok{ }\KeywordTok{hist}\NormalTok{(}\DataTypeTok{x=}\NormalTok{x, }\DataTypeTok{plot=}\OtherTok{FALSE}\NormalTok{, }
             \DataTypeTok{breaks=}\KeywordTok{c}\NormalTok{(}\DecValTok{150}\NormalTok{, }\DecValTok{170}\NormalTok{, }\DecValTok{180}\NormalTok{, }\DecValTok{190}\NormalTok{))}
\NormalTok{res2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1] 150 170 180 190
## 
## $counts
## [1]  90 109   1
## 
## $density
## [1] 0.0225 0.0545 0.0005
## 
## $mids
## [1] 160 175 185
## 
## $xname
## [1] "x"
## 
## $equidist
## [1] FALSE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

\subsubsection*{Ejemplo}\label{ejemplo-14}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Construya el vector \texttt{x} con los siguientes elementos: 1.0, 1.2,
1.3, 2.0, 2.5, 2.7, 3.0 y 3.4. Obtenga varias tablas de frecuencia con
la función \texttt{hist} variando los parámetros \texttt{include.lowest}
y \texttt{right}. Use como límite de los intervalos los valores 1, 2, 3
y 4.

Lo primero que debemos hacer es crear el vector \texttt{x} solicitado
así:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\FloatTok{1.1}\NormalTok{, }\FloatTok{1.2}\NormalTok{, }\FloatTok{1.3}\NormalTok{, }\FloatTok{2.0}\NormalTok{, }\FloatTok{2.0}\NormalTok{, }\FloatTok{2.5}\NormalTok{, }\FloatTok{2.7}\NormalTok{, }\FloatTok{3.0}\NormalTok{, }\FloatTok{3.4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En la Figura \ref{fig:dots} se muestran los 9 puntos y con color azul se
representan los límites de los intervalos.

\begin{figure}
\centering
\includegraphics{Manual_de_R_files/figure-latex/dots-1.pdf}
\caption{\label{fig:dots}Ubicación de los puntos del ejemplo con límites en
color azul.}
\end{figure}

A continuación se presenta el código para obtener la tabla de frecuencia
usando \texttt{rigth=TRUE}, los resultados se almacenan en el objeto
\texttt{res3} y se solicitan sólo los dos primeros elementos que
corresponden a los límites y frecuencias.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res3 <-}\StringTok{ }\KeywordTok{hist}\NormalTok{(x, }\DataTypeTok{breaks=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{), }\DataTypeTok{right=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{plot=}\OtherTok{FALSE}\NormalTok{)}
\NormalTok{res3[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1] 1 2 3 4
## 
## $counts
## [1] 5 3 1
\end{verbatim}

Ahora vamos a repetir la tabla pero usando \texttt{rigth=FALSE} para ver
la diferencia, en \texttt{res4} están los resultados.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res4 <-}\StringTok{ }\KeywordTok{hist}\NormalTok{(x, }\DataTypeTok{breaks=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{), }\DataTypeTok{right=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{plot=}\OtherTok{FALSE}\NormalTok{)}
\NormalTok{res4[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1] 1 2 3 4
## 
## $counts
## [1] 3 4 2
\end{verbatim}

Al comparar los últimos dos resultados vemos que la primera frecuencia
es 5 cuando \texttt{right=TRUE} porque los intervalos se consideran
cerrados a la derecha.

Ahora vamos a construir una tabla de frecuencia usando \texttt{FALSE}
para los parámetros \texttt{include.lowest} y \texttt{right}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res5 <-}\StringTok{ }\KeywordTok{hist}\NormalTok{(x, }\DataTypeTok{breaks=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{),}
             \DataTypeTok{include.lowest=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{right=}\OtherTok{FALSE}\NormalTok{,}
             \DataTypeTok{plot=}\OtherTok{FALSE}\NormalTok{)}
\NormalTok{res5[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1] 1 2 3 4
## 
## $counts
## [1] 3 4 2
\end{verbatim}

De este último resultado se ve claramente el efecto de los parámetros
\texttt{include.lowest} y \texttt{right} en la construcción de tablas de
frecuencia.

\subsection*{EJERCICIOS}\label{ejercicios-3}
\addcontentsline{toc}{subsection}{EJERCICIOS}

Use funciones o procedimientos (varias líneas) de R para responder cada
una de las siguientes preguntas.

En el Cuadro \ref{tab:toy} se presenta una base de datos sencilla. Lea
la base de datos usando la funcion \texttt{read.table} y construya lo
que se solicita a continuación.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Construya una tabla de frecuencia absoluta para la variable
  pasatiempo.
\item
  Construya una tabla de frecuencia relativa para la variable fuma.
\item
  Construya una tabla de frecuencia relativa para las variables
  pasatiempo y fuma.
\item
  ¿Qué porcentaje de de los que no fuman tienen como pasatiempo la
  lectura.
\item
  ¿Qué porcentaje de los que corren no fuman?
\end{enumerate}

\section{Medidas de tendencia central}\label{central}

En este capítulo se mostrará cómo obtener las diferentes medidas de
tendencia central con R.

Para ilustrar el uso de las funciones se utilizará una base de datos
llamada \textbf{medidas del cuerpo}, esta base de datos cuenta con 6
variables registradas a un grupo de 36 estudiantes de la universidad.
Las variables son:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \texttt{edad} del estudiante (años),
\item
  \texttt{peso} del estudiante (kilogramos),
\item
  \texttt{altura} del estudiante (centímetros),
\item
  \texttt{sexo} del estudiante (Hombre, Mujer),
\item
  \texttt{muneca}: perímetro de la muñeca derecha (centímetros),
\item
  \texttt{biceps}: perímetro del biceps derecho (centímetros).
\end{enumerate}

A continuación se presenta el código para definir la url donde están los
datos, para cargar la base de datos en R y para mostrar por pantalla un
encabezado (usando \texttt{head}) de la base de datos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{url <-}\StringTok{ 'https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo'}
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\NormalTok{url, }\DataTypeTok{header=}\NormalTok{T)}
\KeywordTok{head}\NormalTok{(datos)  }\CommentTok{# Para ver el encabezado de la base de datos}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   edad peso altura   sexo muneca biceps
## 1   43 87.3  188.0 Hombre   12.2   35.8
## 2   65 80.0  174.0 Hombre   12.0   35.0
## 3   45 82.3  176.5 Hombre   11.2   38.5
## 4   37 73.6  180.3 Hombre   11.2   32.2
## 5   55 74.1  167.6 Hombre   11.8   32.9
## 6   33 85.9  188.0 Hombre   12.4   38.5
\end{verbatim}

\subsection{\texorpdfstring{Media \index{media}
\index{mean}}{Media  }}\label{media}

Para calcular la media de una variable cuantitativa se usa la función
\texttt{mean}. Los argumentos básicos de la función \texttt{mean} son
dos y se muestran a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En el parámetro \texttt{x} se indica la variable de interés para la cual
se quiere calcular la media, el parámetro \texttt{na.rm} es un valor
lógico que en caso de ser \texttt{TRUE}, significa que se deben remover
las observaciones con \texttt{NA}, el valor por defecto para este
parámetro es \texttt{FALSE}.

\subsubsection*{Ejemplo}\label{ejemplo-15}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que queremos obtener la altura media del grupo de estudiantes.

Para encontrar la media general se usa la función \texttt{mean} sobre el
vector númerico \texttt{datos\$altura}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(}\DataTypeTok{x=}\NormalTok{datos}\OperatorTok{$}\NormalTok{altura)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 171.6
\end{verbatim}

Del anterior resultado podemos decir que la estatura media o promedio de
los estudiantes es 171.5556 centímetros.

\subsubsection*{Ejemplo}\label{ejemplo-16}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que ahora queremos la altura media pero diferenciando por sexo.

Para hacer esto se debe primero dividir o partir el vector de altura
según los niveles de la variable sexo, esto se consigue por medio de la
función \texttt{split} y el resultado será una lista con tantos
elementos como niveles tenga la variable sexo. Luego a cada uno de los
elementos de la lista se le aplica la función \texttt{mean} con la ayuda
de \texttt{sapply} o \texttt{tapply}. A continuación el código completo
para obtener las alturas medias para hombres y mujeres.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sapply}\NormalTok{(}\KeywordTok{split}\NormalTok{(}\DataTypeTok{x=}\NormalTok{datos}\OperatorTok{$}\NormalTok{altura, }\DataTypeTok{f=}\NormalTok{datos}\OperatorTok{$}\NormalTok{sexo), mean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Hombre  Mujer 
##  179.1  164.0
\end{verbatim}

El resultado es un vector con dos elementos, vemos que la altura media
para hombres es 179.0778 centímetros y que para las mujeres es de
164.0333 centímetros.

¿Qué sucede si se usa \texttt{tapply} en lugar de \texttt{sapply}?
Substituya en el código anterior la función \texttt{sapply} por
\texttt{tapply} y observe la diferencia entre los resultados.

\subsubsection*{Ejemplo}\label{ejemplo-17}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que se tiene el vector \texttt{edad} con las edades de siete
personas y supóngase que para el individuo cinco no se tiene información
de su edad, eso significa que el vector tendrá un \texttt{NA} en la
quinta posición.

¿Cuál será la edad promedio del grupo de personas?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edad <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{18}\NormalTok{, }\DecValTok{23}\NormalTok{, }\DecValTok{26}\NormalTok{, }\DecValTok{32}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\DecValTok{32}\NormalTok{, }\DecValTok{29}\NormalTok{)}
\KeywordTok{mean}\NormalTok{(}\DataTypeTok{x=}\NormalTok{edad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA
\end{verbatim}

Al correr el código anterior se obtiene un error y es debido al símbolo
\texttt{NA} en la quinta posición. Para calcular la media sólo con los
datos de los cuales se tiene información, se incluye el argumento
\texttt{na.rm\ =\ TRUE} para que R remueva los \texttt{NA}. El código
correcto a usar en este caso es:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(}\DataTypeTok{x=}\NormalTok{edad, }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 26.67
\end{verbatim}

De este último resultado se obtiene que la edad promedio de los
individuos es 26.67 años.

\subsection{\texorpdfstring{Mediana \index{mediana}
\index{median}}{Mediana  }}\label{mediana}

Para calcular la mediana de una variable cantitativa se usa la función
\texttt{median}. Los argumentos básicos de la función \texttt{median}
son dos y se muestran a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En el parámetro \texttt{x} se indica la variable de interés para la cual
se quiere calcular la mediana, el parámetro \texttt{na.rm} es un valor
lógico que en caso de ser \texttt{TRUE}, significa que se deben remover
las observaciones con \texttt{NA}, el valor por defecto para este
parámetro es \texttt{FALSE}.

\subsubsection*{Ejemplo}\label{ejemplo-18}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Calcular la edad mediana para los estudiantes de la base de datos.

Para obtener la mediana usamos el siguiente código:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(}\DataTypeTok{x=}\NormalTok{datos}\OperatorTok{$}\NormalTok{edad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 28
\end{verbatim}

y obtenemos que la mitad de los estudiantes tienen edades mayores o
iguales a 28 años.

El resultado anterior se pudo haber obtenido con la función
\texttt{quantile} e indicando que se desea el cuantil 50 así:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{quantile}\NormalTok{(}\DataTypeTok{x=}\NormalTok{datos}\OperatorTok{$}\NormalTok{edad, }\DataTypeTok{probs=}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 50% 
##  28
\end{verbatim}

\subsection{\texorpdfstring{Moda \index{moda}}{Moda }}\label{moda}

La moda de una variable cuantitativa corresponde a valor o valores que
más se repiten, una forma sencilla de encontrar la moda es construir una
tabla de frecuencias y observar los valores con mayor frecuencia.

\subsubsection*{Ejemplo}\label{ejemplo-19}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Calcular la moda para la variable edad de la base de datos de
estudiantes.

Se construye la tabla con la función \texttt{table} y se crea el objeto
\texttt{tabla} para almacenarla.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla <-}\StringTok{ }\KeywordTok{table}\NormalTok{(datos}\OperatorTok{$}\NormalTok{edad)}
\NormalTok{tabla}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 19 20 21 22 23 24 25 26 28 29 30 32 33 35 37 40 43 45 
##  1  1  1  3  2  1  5  3  2  1  2  1  1  2  3  1  2  1 
## 51 55 65 
##  1  1  1
\end{verbatim}

Al mirar con detalle la tabla anterior se observa que el valor que más
se repite es la edad de 25 años en 5 ocasiones. Si la tabla hubiese sido
mayor, la inspección visual nos podría tomar unos segundos o hasta
minutos y podríamos equivocarnos, por esa razón es mejor ordenar los
resultados de la tabla.

Para observar los valores con mayor frecuencia de la tabla se puede
ordenar la tabla usando la función \texttt{sort} de la siguiente manera:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sort}\NormalTok{(tabla, }\DataTypeTok{decreasing=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 25 22 26 37 23 28 30 35 43 19 20 21 24 29 32 33 40 45 
##  5  3  3  3  2  2  2  2  2  1  1  1  1  1  1  1  1  1 
## 51 55 65 
##  1  1  1
\end{verbatim}

De esta manera se ve fácilmente que la variable edad es unimodal con
valor de 25 años.

\section{Medidas de variabilidad}\label{varia}

En este capítulo se mostrará cómo obtener las diferentes medidas de
variabilidad con R.

Para ilustrar el uso de las funciones se utilizará la base de datos
llamada \textbf{aptos2015}, esta base de datos cuenta con 11 variables
registradas a apartamentos usados en la ciudad de Medellín. Las
variables de la base de datos son:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \texttt{precio}: precio de venta del apartamento (millones de pesos),
\item
  \texttt{mt2}: área del apartamento (\(m^2\)),
\item
  \texttt{ubicacion}: lugar de ubicación del aparamentos en la ciudad
  (cualitativa),
\item
  \texttt{estrato}: nivel socioeconómico donde está el apartamento (2 a
  6),
\item
  \texttt{alcobas}: número de alcobas del apartamento,
\item
  \texttt{banos}: número de baños del apartamento,
\item
  \texttt{balcon}: si el apartamento tiene balcón (si o no),
\item
  \texttt{parqueadero}: si el apartamento tiene parqueadero (si o no),
\item
  \texttt{administracion}: valor mensual del servicio de administración
  (millones de pesos),
\item
  \texttt{avaluo}: valor del apartamento en escrituras (millones de
  pesos),
\item
  \texttt{terminado}: si el apartamento se encuentra terminado (si o
  no).
\end{enumerate}

A continuación se presenta el código para definir la url donde están los
datos, para cargar la base de datos en R y para mostrar por pantalla un
encabezado (usando \texttt{head}) de la base de datos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{url <-}\StringTok{ 'https://raw.githubusercontent.com/fhernanb/datos/master/aptos2015'}
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\NormalTok{url, }\DataTypeTok{header=}\NormalTok{T)}
\KeywordTok{head}\NormalTok{(datos)  }\CommentTok{# Para ver el encabezado de la base de datos}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   precio   mt2 ubicacion estrato alcobas banos balcon
## 1     79 43.16     norte       3       3     1     si
## 2     93 56.92     norte       2       2     1     si
## 3    100 66.40     norte       3       2     2     no
## 4    123 61.85     norte       2       3     2     si
## 5    135 89.80     norte       4       3     2     si
## 6    140 71.00     norte       3       3     2     no
##   parqueadero administracion avaluo terminado
## 1          si          0.050  14.92        no
## 2          si          0.069  27.00        si
## 3          no          0.000  15.74        no
## 4          si          0.130  27.00        no
## 5          no          0.000  39.57        si
## 6          si          0.120  31.15        si
\end{verbatim}

\subsection{\texorpdfstring{Rango \index{rango}
\index{range}}{Rango  }}\label{rango}

Para calcular el rango de una variable cuantitativa se usa la función
\texttt{range}. Los argumentos básicos de la función \texttt{range} son
dos y se muestran abajo.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{range}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En el parámetro \texttt{x} se indica la variable de interés para la cual
se quiere calcular el rango, el parámetro \texttt{na.rm} es un valor
lógico que en caso de ser \texttt{TRUE}, significa que se deben remover
las observaciones con \texttt{NA}, el valor por defecto para este
parámetro es \texttt{FALSE}.

La función \texttt{range} entrega el valor mínimo y máximo de la
variable ingresada y el valor de rango se puede obtener restando del
valor máximo el valor mínimo.

\subsubsection*{Ejemplo}\label{ejemplo-20}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que queremos obtener el rango para la variable precio de los
apartamentos.

Para obtener el rango usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{range}\NormalTok{(datos}\OperatorTok{$}\NormalTok{precio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]   25 1700
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{max}\NormalTok{(datos}\OperatorTok{$}\NormalTok{precio) }\OperatorTok{-}\StringTok{ }\KeywordTok{min}\NormalTok{(datos}\OperatorTok{$}\NormalTok{precio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1675
\end{verbatim}

Del resultado anterior podemos ver que los precios de todos los
apartamentos van desde 25 hasta 1700 millones de pesos, es decir, el
rango de la variable precio es 1675 millones de pesos.

\subsubsection*{Ejemplo}\label{ejemplo-21}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que queremos obtener nuevamente el rango para la variable precio
de los apartamentos pero diferenciando por el estrato.

Primero vamos a crear una función auxiliar llamada \texttt{myrange} que
calculará el rango directamente (\(max - min\)). Luego vamos a partir la
información de los precios por cada estrato usando \texttt{split}, la
partición se almacenará en la lista \texttt{precios}. Finalmente se
aplicará la función \texttt{myrange} a la lista \texttt{precios} para
obtener los rangos del precio por estrato socioeconómico. El código para
realizar esto se muestra a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{myrange <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{max}\NormalTok{(x) }\OperatorTok{-}\StringTok{ }\KeywordTok{min}\NormalTok{(x)}
\NormalTok{precios <-}\StringTok{ }\KeywordTok{split}\NormalTok{(datos}\OperatorTok{$}\NormalTok{precio, }\DataTypeTok{f=}\NormalTok{datos}\OperatorTok{$}\NormalTok{estrato)}
\KeywordTok{sapply}\NormalTok{(precios, myrange)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    2    3    4    5    6 
##  103  225  610 1325 1560
\end{verbatim}

De los resultados podemos ver claramente que a medida que aumenta de
estrato el rango (variabilidad) del precio de los apartamentos aumenta.
Apartamentos de estrato bajo tienden a tener precios similares mientras
que los precios de venta para apartamentos de estratos altos tienden a
ser muy diferentes entre si.

\subsection{\texorpdfstring{Desviación estándar muestral (\(S\))
\index{desviación}
\index{sd}}{Desviación estándar muestral (S)  }}\label{desviacion-estandar-muestral-s}

Para calcular la desviación muestral de una variable cuantitativa se usa
la función \texttt{sd}. Los argumentos básicos de la función \texttt{sd}
son dos y se muestran abajo.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En el parámetro \texttt{x} se indica la variable de interés para la cual
se quiere calcular la desviación estándar muestral, el parámetro
\texttt{na.rm} es un valor lógico que en caso de ser \texttt{TRUE},
significa que se deben remover las observaciones con \texttt{NA}, el
valor por defecto para este parámetro es \texttt{FALSE}.

\subsubsection*{Ejemplo}\label{ejemplo-22}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que queremos obtener la desviación estándar muestral para la
variable precio de los apartamentos.

Para obtener la desviación solicitada usamos el siguiente código:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(}\DataTypeTok{x=}\NormalTok{datos}\OperatorTok{$}\NormalTok{precio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 247.6
\end{verbatim}

\subsubsection*{Ejemplo}\label{ejemplo-23}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Calcular la desviación estándar \textbf{poblacional} (\(\sigma\)) para
el siguiente conjunto de 5 observaciones: 12, 25, 32, 15, 26.

Recordemos que las expresiones matemáticas para obtener \(S\) y
\(\sigma\) son muy similares, la diferencia está en el denominador, para
\(S\) el denominador es \(n-1\) mientras que para \(\sigma\) es \(n\).
Teniendo esto en cuenta podemos calcular la desviación poblacional
apoyándonos en la función \texttt{sd}, para esto podemos construir una
función llamada \texttt{Sigma} que calcule la desviación poblacional, a
continuación el código necesario.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Sigma <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(x)}
  \KeywordTok{sd}\NormalTok{(x) }\OperatorTok{*}\StringTok{ }\NormalTok{(n}\OperatorTok{-}\DecValTok{1}\NormalTok{) }\OperatorTok{/}\StringTok{ }\NormalTok{n}
\NormalTok{\} }
\end{Highlighting}
\end{Shaded}

Ahora para obtener la desviación estándar \textbf{poblacional} de los
datos usamos el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{32}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{26}\NormalTok{)}
\KeywordTok{Sigma}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.621
\end{verbatim}

\subsection{\texorpdfstring{Varianza muestral (\(S^2\)) \index{varianza}
\index{var}}{Varianza muestral (S\^{}2)  }}\label{varianza-muestral-s2}

Para calcular la varianza muestral de una variable cuantitativa se usa
la función \texttt{var}. Los argumentos básicos de la función
\texttt{var} son dos y se muestran abajo.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En el parámetro \texttt{x} se indica la variable de interés para la cual
se quiere calcular la varianza muestral, el parámetro \texttt{na.rm} es
un valor lógico que en caso de ser \texttt{TRUE}, significa que se deben
remover las observaciones con \texttt{NA}, el valor por defecto para
este parámetro es \texttt{FALSE}.

\subsubsection*{Ejemplo}\label{ejemplo-24}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que queremos determinar cuál región en la ciudad presenta mayor
varianza en los precios de los apartamentos.

Para realizar esto debemos usar en conjunto la función \texttt{split},
\texttt{sapply} y \texttt{var} ya que se quiere la varianza de una
variable (\texttt{precio}) dado los valores de otra variable
(\texttt{ubicacion}). El código para obtener las varianzas es el
siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{precios <-}\StringTok{ }\KeywordTok{split}\NormalTok{(datos}\OperatorTok{$}\NormalTok{precio, }\DataTypeTok{f=}\NormalTok{datos}\OperatorTok{$}\NormalTok{ubicacion)}
\KeywordTok{sapply}\NormalTok{(precios, var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     aburra sur belen guayabal         centro 
##           4169           2528           2588 
##       laureles          norte      occidente 
##          25351           1009           3596 
##        poblado 
##          84497
\end{verbatim}

De los resultados anteriores se nota que los apartamentos ubicados en el
Poblado tienen la mayor variabilidad en el precio, este resultado se
confirma al dibujar un boxplot para la variable precio dada la
ubicación, en la Figura \ref{fig:box1} se muestra el boxplot y se ve
claramente la dispersión de los precios en el Poblado. El código usado
para generar la Figura \ref{fig:box1} se presenta a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{with}\NormalTok{(datos, }\KeywordTok{boxplot}\NormalTok{(precio }\OperatorTok{~}\StringTok{ }\NormalTok{ubicacion, }\DataTypeTok{ylab=}\StringTok{'Precio (millones)'}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Manual_de_R_files/figure-latex/box1-1.pdf}
\caption{\label{fig:box1}Boxplot para el precio de los apartamentos dada la
ubicación.}
\end{figure}

\subsubsection*{Ejemplo}\label{ejemplo-25}
\addcontentsline{toc}{subsubsection}{Ejemplo}

¿Son los resultados de la función \texttt{var} los mismos que los
resultados de la función \texttt{sd} elevados al cuadrado?

La respuesta es \textbf{NO}. La función \texttt{sd} se aplica sólo a
vectores mientras que la función \texttt{var} de puede aplicar tanto a
vectores como a marcos de datos. Al ser aplicada a marcos de datos
numéricos se obtiene una matriz en que la diagonal representa las
varianzas de las de cada una de las variables mientras que arriba y
abajo de la diagonal se encuentran las covarianzas entre pares de
variables.

Por ejemplo, si aplicamos la función \texttt{var} al marco de datos sólo
con las variables precio, área y avaluo se obtiene una matriz de
dimensión \(3 \times 3\), a continuación el código usado.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var}\NormalTok{(datos[, }\KeywordTok{c}\NormalTok{(}\StringTok{'precio'}\NormalTok{, }\StringTok{'mt2'}\NormalTok{, }\StringTok{'avaluo'}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        precio   mt2 avaluo
## precio  61313 15874  33056
## mt2     15874  5579   9508
## avaluo  33056  9508  28589
\end{verbatim}

Del anterior resultado se observa la matriz de varianzas y covarianzas
de dimensión \(3 \times 3\).

\subsection{\texorpdfstring{Coeficiente de variación (\(CV\))
\index{coeficiente de variación}}{Coeficiente de variación (CV) }}\label{coeficiente-de-variacion-cv}

El coeficiente de variación se define como \(CV=s/\bar{x}\) y es muy
sencillo de obtenerlo, la función \texttt{CV} mostrada abajo permite
calcularlo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CV <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{) \{}
  \KeywordTok{sd}\NormalTok{(x, }\DataTypeTok{na.rm=}\NormalTok{na.rm) }\OperatorTok{/}\StringTok{ }\KeywordTok{mean}\NormalTok{(x, }\DataTypeTok{na.rm=}\NormalTok{na.rm)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\subsubsection*{Ejemplo}\label{ejemplo-26}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Calcular el \(CV\) para el vector \texttt{w} definido a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{w <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\OperatorTok{-}\DecValTok{3}\NormalTok{, }\OtherTok{NA}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Vemos que el vector \texttt{w} tiene 6 observaciones y la tercera de
ellas es un \texttt{NA}. Lo correcto aquí es usar la función \texttt{CV}
definida antes pero indicándole que remueva los valores faltantes, para
eso se usa el siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{CV}\NormalTok{(}\DataTypeTok{x=}\NormalTok{w, }\DataTypeTok{na.rm=}\NormalTok{T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9274
\end{verbatim}

\section{Medidas de posición}\label{posi}

En este capítulo se mostrará cómo obtener las diferentes medidas de
posición con R.

Para ilustrar el uso de las funciones se utilizará una base de datos
llamada \textbf{medidas del cuerpo}, esta base de datos cuenta con 6
variables registradas a un grupo de 36 estudiantes de la universidad.
Las variables son:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \texttt{edad} del estudiante (años),
\item
  \texttt{peso} del estudiante (kilogramos),
\item
  \texttt{altura} del estudiante (centímetros),
\item
  \texttt{sexo} del estudiante (Hombre, Mujer),
\item
  \texttt{muneca}: perímetro de la muñeca derecha (centímetros),
\item
  \texttt{biceps}: perímetro del biceps derecho (centímetros).
\end{enumerate}

A continuación se presenta el código para definir la url donde están los
datos, para cargar la base de datos en R y para mostrar por pantalla un
encabezado (usando \texttt{head}) de la base de datos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{url <-}\StringTok{ 'https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo'}
\NormalTok{datos <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file=}\NormalTok{url, }\DataTypeTok{header=}\NormalTok{T)}
\KeywordTok{head}\NormalTok{(datos)  }\CommentTok{# Para ver el encabezado de la base de datos}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   edad peso altura   sexo muneca biceps
## 1   43 87.3  188.0 Hombre   12.2   35.8
## 2   65 80.0  174.0 Hombre   12.0   35.0
## 3   45 82.3  176.5 Hombre   11.2   38.5
## 4   37 73.6  180.3 Hombre   11.2   32.2
## 5   55 74.1  167.6 Hombre   11.8   32.9
## 6   33 85.9  188.0 Hombre   12.4   38.5
\end{verbatim}

\subsection{\texorpdfstring{Cuantiles \index{cuantiles} \index{quantile}
\index{cuartiles} \index{deciles}
\index{percentiles}}{Cuantiles     }}\label{cuantiles}

Para obtener cualquier cuantil (cuartiles, deciles y percentiles) se usa
la función \texttt{quantile}. Los argumentos básicos de la función
\texttt{quantile} son tres y se muestran a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{quantile}\NormalTok{(x, probs, }\DataTypeTok{na.rm =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

En el parámetro \texttt{x} se indica la variable de interés para la cual
se quieren calcular los cuantiles, el parámetro \texttt{probs} sirve
para definir los cuantiles de interés y el parámetro \texttt{na.rm} es
un valor lógico que en caso de ser \texttt{TRUE}, significa que se deben
remover las observaciones con \texttt{NA}, el valor por defecto para
este parámetro es \texttt{FALSE}.

\subsubsection*{Ejemplo}\label{ejemplo-27}
\addcontentsline{toc}{subsubsection}{Ejemplo}

Suponga que queremos obtener el percentil 5, la mediana y el decil 8 pa
la altura del grupo de estudiantes.

Se solicita el percentil 5, la mediana que es el percentil 50 y el decil
8 que corresponde al percentil 80, por lo tanto es necesario indicarle a
la función \texttt{quantile} que calcule los cuantiles para las
ubicaciones 0.05, 0.5 y 0.8, el código para obtener las tres medidas
solicitadas es el siguiente.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{quantile}\NormalTok{(}\DataTypeTok{x=}\NormalTok{datos}\OperatorTok{$}\NormalTok{altura, }\DataTypeTok{probs=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.8}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    5%   50%   80% 
## 155.2 172.7 180.3
\end{verbatim}

\section{Curiosidades}\label{curio}

En este capítulo se mostrarán algunos procedimientos de R para
solucionar problemas frecuentes.

\subsection{¿Cómo verificar si un paquete no está instalado para
instalarlo de forma
automática?}\label{como-verificar-si-un-paquete-no-esta-instalado-para-instalarlo-de-forma-automatica}

Muchas veces compartimos código de R con otros colegas y si ellos no
tienen instalados ciertos paquetes el código no funcionará. Para evitar
ese problema podemos colocar al inicio del código unas líneas que
chequeen si ciertos paquetes están instalados o no, si están instalados,
se cargan esos paquetes y caso contrario, el código instala los paquetes
y luego los carga, todo de forma automática sin que el usuario tenga que
identificar los paquetes que le faltan.

\subsubsection*{Ejemplo}\label{ejemplo-28}
\addcontentsline{toc}{subsubsection}{Ejemplo}

El código mostrado abajo revisa si los paquetes \texttt{knitr},
\texttt{png} y \texttt{markdown} están instalados e instala los ausentes
y luego carga todos los paquetes que estén en el vector
\texttt{packages}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{packages <-}\StringTok{  }\KeywordTok{c}\NormalTok{(}\StringTok{"knitr"}\NormalTok{, }\StringTok{"png"}\NormalTok{, }\StringTok{"markdown"}\NormalTok{)}
\NormalTok{package.check <-}\StringTok{ }\KeywordTok{lapply}\NormalTok{(packages, }\DataTypeTok{FUN =} \ControlFlowTok{function}\NormalTok{(x) \{}
  \ControlFlowTok{if}\NormalTok{ (}\OperatorTok{!}\KeywordTok{require}\NormalTok{(x, }\DataTypeTok{character.only =} \OtherTok{TRUE}\NormalTok{)) \{}
    \KeywordTok{install.packages}\NormalTok{(x, }\DataTypeTok{dependencies =} \OtherTok{TRUE}\NormalTok{)}
    \KeywordTok{library}\NormalTok{(x, }\DataTypeTok{character.only =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{  \}}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\bibliography{book.bib,packages.bib}


\end{document}
