<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>19 Distribución normal | Manual de R</title>
  <meta name="description" content="19 Distribución normal | Manual de R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="19 Distribución normal | Manual de R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/portada.png" />
  <meta property="og:description" content="19 Distribución normal | Manual de R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="github-repo" content="fhernanb/Manual-de-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="19 Distribución normal | Manual de R" />
  
  <meta name="twitter:description" content="19 Distribución normal | Manual de R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="twitter:image" content="/images/portada.png" />

<meta name="author" content="Freddy Hernández" />
<meta name="author" content="Olga Usuga" />


<meta name="date" content="2024-11-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="continuas.html"/>
<link rel="next" href="normalidad.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Manual de R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#información-del-software-y-convenciones"><i class="fa fa-check"></i>Información del software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#agradecimientos"><i class="fa fa-check"></i>Agradecimientos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-los-autores.html"><a href="sobre-los-autores.html"><i class="fa fa-check"></i>Sobre los autores</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#orígenes"><i class="fa fa-check"></i><b>1.1</b> Orígenes</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#instalación"><i class="fa fa-check"></i><b>1.2</b> Instalación</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#apariencia-del-programa"><i class="fa fa-check"></i><b>1.3</b> Apariencia del programa</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="objetos.html"><a href="objetos.html"><i class="fa fa-check"></i><b>2</b> Tipos de objetos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="objetos.html"><a href="objetos.html#variables"><i class="fa fa-check"></i><b>2.1</b> Variables</a></li>
<li class="chapter" data-level="2.2" data-path="objetos.html"><a href="objetos.html#vectores"><i class="fa fa-check"></i><b>2.2</b> Vectores </a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-un-vector"><i class="fa fa-check"></i><b>2.2.1</b> ¿Cómo extraer elementos de un vector?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="objetos.html"><a href="objetos.html#matrices"><i class="fa fa-check"></i><b>2.3</b> Matrices</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-una-matriz"><i class="fa fa-check"></i><b>2.3.1</b> ¿Cómo extraer elementos de una matriz?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="objetos.html"><a href="objetos.html#arreglos"><i class="fa fa-check"></i><b>2.4</b> Arreglos </a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-un-arreglo"><i class="fa fa-check"></i><b>2.4.1</b> ¿Cómo extraer elementos de un arreglo?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="objetos.html"><a href="objetos.html#marco-de-datos"><i class="fa fa-check"></i><b>2.5</b> Marco de datos </a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-un-marco-de-datos"><i class="fa fa-check"></i><b>2.5.1</b> ¿Cómo extraer elementos de un marco de datos?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="2.5.2" data-path="objetos.html"><a href="objetos.html#cómo-extraer-subconjuntos-de-un-marco-de-datos"><i class="fa fa-check"></i><b>2.5.2</b> ¿Cómo extraer subconjuntos de un marco de datos? </a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplos"><i class="fa fa-check"></i>Ejemplos</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="objetos.html"><a href="objetos.html#listas"><i class="fa fa-check"></i><b>2.6</b> Listas </a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="objetos.html"><a href="objetos.html#cómo-extraer-elementos-de-una-lista"><i class="fa fa-check"></i><b>2.6.1</b> ¿Cómo extraer elementos de una lista?</a></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejemplos-1"><i class="fa fa-check"></i>Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="objetos.html"><a href="objetos.html#ejercicios"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estilo.html"><a href="estilo.html"><i class="fa fa-check"></i><b>3</b> Guía de estilo</a>
<ul>
<li class="chapter" data-level="3.1" data-path="estilo.html"><a href="estilo.html#nombres-de-los-archivos"><i class="fa fa-check"></i><b>3.1</b> Nombres de los archivos</a></li>
<li class="chapter" data-level="3.2" data-path="estilo.html"><a href="estilo.html#nombres-de-los-objetos"><i class="fa fa-check"></i><b>3.2</b> Nombres de los objetos</a></li>
<li class="chapter" data-level="3.3" data-path="estilo.html"><a href="estilo.html#longitud-de-una-línea-de-código"><i class="fa fa-check"></i><b>3.3</b> Longitud de una línea de código</a></li>
<li class="chapter" data-level="3.4" data-path="estilo.html"><a href="estilo.html#espacios"><i class="fa fa-check"></i><b>3.4</b> Espacios</a></li>
<li class="chapter" data-level="3.5" data-path="estilo.html"><a href="estilo.html#asignación-en-r"><i class="fa fa-check"></i><b>3.5</b> Asignación en R</a>
<ul>
<li class="chapter" data-level="" data-path="estilo.html"><a href="estilo.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="estilo.html"><a href="estilo.html#punto-y-coma"><i class="fa fa-check"></i><b>3.6</b> Punto y coma</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html"><i class="fa fa-check"></i><b>4</b> Ingresando datos a R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html#usando-la-consola"><i class="fa fa-check"></i><b>4.1</b> Usando la consola</a></li>
<li class="chapter" data-level="4.2" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html#usando-ventana-emergente-con-svdialogs"><i class="fa fa-check"></i><b>4.2</b> Usando ventana emergente con <strong>svDialogs</strong></a></li>
<li class="chapter" data-level="4.3" data-path="ingresando-datos-a-r.html"><a href="ingresando-datos-a-r.html#botones-para-responder"><i class="fa fa-check"></i><b>4.3</b> Botones para responder</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="funbas.html"><a href="funbas.html"><i class="fa fa-check"></i><b>5</b> Funciones básicas de R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="funbas.html"><a href="funbas.html#qué-es-una-función-de-r"><i class="fa fa-check"></i><b>5.1</b> ¿Qué es una función de R?</a></li>
<li class="chapter" data-level="5.2" data-path="funbas.html"><a href="funbas.html#funciones-básicas"><i class="fa fa-check"></i><b>5.2</b> Funciones básicas</a></li>
<li class="chapter" data-level="5.3" data-path="funbas.html"><a href="funbas.html#operadores-binarios"><i class="fa fa-check"></i><b>5.3</b> Operadores binarios</a></li>
<li class="chapter" data-level="5.4" data-path="funbas.html"><a href="funbas.html#pruebas-lógicas"><i class="fa fa-check"></i><b>5.4</b> Pruebas lógicas</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="funbas.html"><a href="funbas.html#operadores-lógicos"><i class="fa fa-check"></i><b>5.5</b> Operadores lógicos</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="funbas.html"><a href="funbas.html#funciones-sobre-vectores"><i class="fa fa-check"></i><b>5.6</b> Funciones sobre vectores</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="funbas.html"><a href="funbas.html#funciones-matemáticas"><i class="fa fa-check"></i><b>5.7</b> Funciones matemáticas</a></li>
<li class="chapter" data-level="5.8" data-path="funbas.html"><a href="funbas.html#función-seq"><i class="fa fa-check"></i><b>5.8</b> Función <code>seq</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="funbas.html"><a href="funbas.html#función-rep"><i class="fa fa-check"></i><b>5.9</b> Función <code>rep</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="funbas.html"><a href="funbas.html#funciones-round-ceiling-floor-y-trunc"><i class="fa fa-check"></i><b>5.10</b> Funciones <code>round</code>, <code>ceiling</code>, <code>floor</code> y <code>trunc</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="funbas.html"><a href="funbas.html#funciones-sort-y-rank"><i class="fa fa-check"></i><b>5.11</b> Funciones <code>sort</code> y <code>rank</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-14"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejercicios-1"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bucles.html"><a href="bucles.html"><i class="fa fa-check"></i><b>6</b> Instrucciones de control</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bucles.html"><a href="bucles.html#instrucción-if"><i class="fa fa-check"></i><b>6.1</b> Instrucción <code>if</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-15"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bucles.html"><a href="bucles.html#instrucción-if-else"><i class="fa fa-check"></i><b>6.2</b> Instrucción <code>if</code> <code>else</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-16"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="bucles.html"><a href="bucles.html#instrucción-ifelse"><i class="fa fa-check"></i><b>6.3</b> Instrucción <code>ifelse</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-17"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="bucles.html"><a href="bucles.html#instrucción-for"><i class="fa fa-check"></i><b>6.4</b> Instrucción <code>for</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-18"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="bucles.html"><a href="bucles.html#instrucción-while"><i class="fa fa-check"></i><b>6.5</b> Instrucción <code>while</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-19"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="bucles.html"><a href="bucles.html#instrucción-repeat"><i class="fa fa-check"></i><b>6.6</b> Instrucción <code>repeat</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-20"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejercicios-2"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="creafun.html"><a href="creafun.html"><i class="fa fa-check"></i><b>7</b> Creación de funciones en R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="creafun.html"><a href="creafun.html#qué-es-una-función-en-r"><i class="fa fa-check"></i><b>7.1</b> ¿Qué es una función en R?</a></li>
<li class="chapter" data-level="7.2" data-path="creafun.html"><a href="creafun.html#partes-de-una-función-en-r"><i class="fa fa-check"></i><b>7.2</b> Partes de una función en R</a>
<ul>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-21"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-22"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-23"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejemplo-24"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="creafun.html"><a href="creafun.html#ejercicios-3"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="vecfun.html"><a href="vecfun.html"><i class="fa fa-check"></i><b>8</b> Vectorización de funciones</a>
<ul>
<li class="chapter" data-level="" data-path="vecfun.html"><a href="vecfun.html#ejemplo-25"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="8.1" data-path="vecfun.html"><a href="vecfun.html#forma-1-asegurando-la-vectorización-desde-el-origen"><i class="fa fa-check"></i><b>8.1</b> Forma 1: asegurando la vectorización desde el origen</a></li>
<li class="chapter" data-level="8.2" data-path="vecfun.html"><a href="vecfun.html#forma-2-usando-vectorize"><i class="fa fa-check"></i><b>8.2</b> Forma 2: usando <code>Vectorize</code></a></li>
<li class="chapter" data-level="8.3" data-path="vecfun.html"><a href="vecfun.html#comparando-los-tiempos-de-procesamiento"><i class="fa fa-check"></i><b>8.3</b> Comparando los tiempos de procesamiento</a></li>
<li class="chapter" data-level="8.4" data-path="vecfun.html"><a href="vecfun.html#otros-recursos-para-aprender-sobre-vectorización"><i class="fa fa-check"></i><b>8.4</b> Otros recursos para aprender sobre vectorización</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>9</b> Lectura de bases de datos</a>
<ul>
<li class="chapter" data-level="9.1" data-path="read.html"><a href="read.html#qué-es-una-base-de-datos"><i class="fa fa-check"></i><b>9.1</b> ¿Qué es una base de datos?</a></li>
<li class="chapter" data-level="9.2" data-path="read.html"><a href="read.html#en-qué-formato-almacenar-una-base-de-datos"><i class="fa fa-check"></i><b>9.2</b> ¿En qué formato almacenar una base de datos?</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="read.html"><a href="read.html#almacenamiento-de-información-en-excel"><i class="fa fa-check"></i><b>9.2.1</b> Almacenamiento de información en Excel</a></li>
<li class="chapter" data-level="9.2.2" data-path="read.html"><a href="read.html#almacenamiento-de-información-en-bloc-de-notas"><i class="fa fa-check"></i><b>9.2.2</b> Almacenamiento de información en bloc de notas</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="read.html"><a href="read.html#función-read.table"><i class="fa fa-check"></i><b>9.3</b> Función <code>read.table</code></a>
<ul>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-26"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-27"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="read.html"><a href="read.html#lectura-de-bases-de-datos-en-excel"><i class="fa fa-check"></i><b>9.4</b> Lectura de bases de datos en Excel</a>
<ul>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejemplo-28"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="read.html"><a href="read.html#ejercicios-4"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tablas.html"><a href="tablas.html"><i class="fa fa-check"></i><b>10</b> Tablas de frecuencia</a>
<ul>
<li class="chapter" data-level="10.1" data-path="tablas.html"><a href="tablas.html#tabla-de-contingencia-con-table"><i class="fa fa-check"></i><b>10.1</b> Tabla de contingencia con <code>table</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-de-una-vía"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia de una vía</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-de-dos-vías"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia de dos vías</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="tablas.html"><a href="tablas.html#función-prop.table"><i class="fa fa-check"></i><b>10.2</b> Función <code>prop.table</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-relativa-de-una-vía"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia relativa de una vía</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-tabla-de-frecuencia-relativa-de-dos-vías"><i class="fa fa-check"></i>Ejemplo: tabla de frecuencia relativa de dos vías</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="tablas.html"><a href="tablas.html#función-addmargins"><i class="fa fa-check"></i><b>10.3</b> Función <code>addmargins</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-29"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="tablas.html"><a href="tablas.html#función-hist"><i class="fa fa-check"></i><b>10.4</b> Función <code>hist</code> </a>
<ul>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-30"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejemplo-31"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tablas.html"><a href="tablas.html#ejercicios-5"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="central.html"><a href="central.html"><i class="fa fa-check"></i><b>11</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="11.1" data-path="central.html"><a href="central.html#media"><i class="fa fa-check"></i><b>11.1</b> Media </a>
<ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-32"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-33"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-34"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="central.html"><a href="central.html#mediana"><i class="fa fa-check"></i><b>11.2</b> Mediana </a>
<ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-35"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="central.html"><a href="central.html#moda"><i class="fa fa-check"></i><b>11.3</b> Moda </a>
<ul>
<li class="chapter" data-level="" data-path="central.html"><a href="central.html#ejemplo-36"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="varia.html"><a href="varia.html"><i class="fa fa-check"></i><b>12</b> Medidas de variabilidad</a>
<ul>
<li class="chapter" data-level="12.1" data-path="varia.html"><a href="varia.html#rango"><i class="fa fa-check"></i><b>12.1</b> Rango </a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-37"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-38"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="varia.html"><a href="varia.html#varianza"><i class="fa fa-check"></i><b>12.2</b> Varianza</a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-39"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-40"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="varia.html"><a href="varia.html#desviación-estándar"><i class="fa fa-check"></i><b>12.3</b> Desviación estándar</a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-41"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-42"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="varia.html"><a href="varia.html#coeficiente-de-variación-cv"><i class="fa fa-check"></i><b>12.4</b> Coeficiente de variación (<span class="math inline">\(CV\)</span>) </a>
<ul>
<li class="chapter" data-level="" data-path="varia.html"><a href="varia.html#ejemplo-43"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="posi.html"><a href="posi.html"><i class="fa fa-check"></i><b>13</b> Medidas de posición</a>
<ul>
<li class="chapter" data-level="13.1" data-path="posi.html"><a href="posi.html#cuantiles"><i class="fa fa-check"></i><b>13.1</b> Cuantiles </a>
<ul>
<li class="chapter" data-level="" data-path="posi.html"><a href="posi.html#ejemplo-44"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>14</b> Medidas de correlación</a>
<ul>
<li class="chapter" data-level="14.1" data-path="correl.html"><a href="correl.html#función-cor"><i class="fa fa-check"></i><b>14.1</b> Función <code>cor</code> </a>
<ul>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-45"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-46"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-47"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejemplo-48"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="correl.html"><a href="correl.html#ejercicios-6"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html"><i class="fa fa-check"></i><b>15</b> Estadística descriptiva con dplyr</a>
<ul>
<li class="chapter" data-level="15.1" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#medidas-de-tendencia-central-variabilidad-posición-y-correlación"><i class="fa fa-check"></i><b>15.1</b> Medidas de tendencia central, variabilidad, posición y correlación</a></li>
<li class="chapter" data-level="15.2" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#paquete-dplyr"><i class="fa fa-check"></i><b>15.2</b> Paquete dplyr</a></li>
<li class="chapter" data-level="15.3" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#pipes-en-r"><i class="fa fa-check"></i><b>15.3</b> Pipes en R</a></li>
<li class="chapter" data-level="15.4" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#estadística-descriptiva-con-dplyr-1"><i class="fa fa-check"></i><b>15.4</b> Estadística descriptiva con dplyr</a></li>
<li class="chapter" data-level="15.5" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#creando-nuevas-variables"><i class="fa fa-check"></i><b>15.5</b> Creando nuevas variables</a></li>
<li class="chapter" data-level="15.6" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#tablas-de-frecuencia"><i class="fa fa-check"></i><b>15.6</b> Tablas de frecuencia</a></li>
<li class="chapter" data-level="15.7" data-path="estadística-descriptiva-con-dplyr.html"><a href="estadística-descriptiva-con-dplyr.html#gráficos"><i class="fa fa-check"></i><b>15.7</b> Gráficos</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html"><i class="fa fa-check"></i><b>16</b> Variables aleatorias</a>
<ul>
<li class="chapter" data-level="16.1" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#variable-aleatoria-discreta"><i class="fa fa-check"></i><b>16.1</b> Variable aleatoria discreta</a>
<ul>
<li class="chapter" data-level="" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#ejemplo-49"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#app-shiny-pmf"><i class="fa fa-check"></i><b>16.2</b> App shiny pmf</a></li>
<li class="chapter" data-level="16.3" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#variable-aleatoria-continua"><i class="fa fa-check"></i><b>16.3</b> Variable aleatoria continua</a>
<ul>
<li class="chapter" data-level="" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#ejemplo-50"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="variables-aleatorias.html"><a href="variables-aleatorias.html#app-shiny-pdf"><i class="fa fa-check"></i><b>16.4</b> App shiny pdf</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="discretas.html"><a href="discretas.html"><i class="fa fa-check"></i><b>17</b> Distribuciones discretas</a>
<ul>
<li class="chapter" data-level="17.1" data-path="discretas.html"><a href="discretas.html#funciones-disponibles-para-distribuciones-discretas"><i class="fa fa-check"></i><b>17.1</b> Funciones disponibles para distribuciones discretas</a>
<ul>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-binomial"><i class="fa fa-check"></i>Ejemplo binomial</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-geométrica"><i class="fa fa-check"></i>Ejemplo geométrica</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-binomial-negativa"><i class="fa fa-check"></i>Ejemplo binomial negativa</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-hipergeométrica"><i class="fa fa-check"></i>Ejemplo hipergeométrica</a></li>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-poisson"><i class="fa fa-check"></i>Ejemplo Poisson</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="discretas.html"><a href="discretas.html#distribuciones-discretas-generales"><i class="fa fa-check"></i><b>17.2</b> Distribuciones discretas generales</a>
<ul>
<li class="chapter" data-level="" data-path="discretas.html"><a href="discretas.html#ejemplo-51"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="continuas.html"><a href="continuas.html"><i class="fa fa-check"></i><b>18</b> Distribuciones continuas</a>
<ul>
<li class="chapter" data-level="18.1" data-path="continuas.html"><a href="continuas.html#funciones-disponibles-para-distribuciones-continuas"><i class="fa fa-check"></i><b>18.1</b> Funciones disponibles para distribuciones continuas</a></li>
<li class="chapter" data-level="18.2" data-path="continuas.html"><a href="continuas.html#distribución-beta"><i class="fa fa-check"></i><b>18.2</b> Distribución beta</a>
<ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-beta"><i class="fa fa-check"></i>Ejemplo beta</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="continuas.html"><a href="continuas.html#distribución-exponencial"><i class="fa fa-check"></i><b>18.3</b> Distribución exponencial</a>
<ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-exponencial"><i class="fa fa-check"></i>Ejemplo exponencial</a></li>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-normal-estándar"><i class="fa fa-check"></i>Ejemplo normal estándar</a></li>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-normal-general"><i class="fa fa-check"></i>Ejemplo normal general</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="continuas.html"><a href="continuas.html#distribuciones-continuas-generales"><i class="fa fa-check"></i><b>18.4</b> Distribuciones continuas generales</a>
<ul>
<li class="chapter" data-level="" data-path="continuas.html"><a href="continuas.html#ejemplo-52"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>19</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="19.1" data-path="normal.html"><a href="normal.html#función-de-densidad"><i class="fa fa-check"></i><b>19.1</b> Función de densidad</a></li>
<li class="chapter" data-level="19.2" data-path="normal.html"><a href="normal.html#visualización-de-la-distribución"><i class="fa fa-check"></i><b>19.2</b> Visualización de la distribución</a></li>
<li class="chapter" data-level="19.3" data-path="normal.html"><a href="normal.html#características-de-la-distribución-normal"><i class="fa fa-check"></i><b>19.3</b> Características de la Distribución Normal</a></li>
<li class="chapter" data-level="19.4" data-path="normal.html"><a href="normal.html#funciones-útiles-asociadas-a-la-normal"><i class="fa fa-check"></i><b>19.4</b> Funciones útiles asociadas a la normal</a></li>
<li class="chapter" data-level="19.5" data-path="normal.html"><a href="normal.html#cálculo-de-probabilidades"><i class="fa fa-check"></i><b>19.5</b> Cálculo de Probabilidades</a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-53"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-54"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-55"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-56"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-57"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="normal.html"><a href="normal.html#cálculo-de-cuantiles"><i class="fa fa-check"></i><b>19.6</b> Cálculo de cuantiles</a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-58"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.7" data-path="normal.html"><a href="normal.html#ejemplo-de-generación-de-datos"><i class="fa fa-check"></i><b>19.7</b> Ejemplo de generación de datos</a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-59"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.8" data-path="normal.html"><a href="normal.html#estimación-de-los-parámetros-mu-y-sigma"><i class="fa fa-check"></i><b>19.8</b> Estimación de los parámetros <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#ejemplo-60"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="19.9" data-path="normal.html"><a href="normal.html#ejercicios-7"><i class="fa fa-check"></i><b>19.9</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="normalidad.html"><a href="normalidad.html"><i class="fa fa-check"></i><b>20</b> Estudiando la normalidad</a>
<ul>
<li class="chapter" data-level="20.1" data-path="normalidad.html"><a href="normalidad.html#consideraciones-iniciales"><i class="fa fa-check"></i><b>20.1</b> Consideraciones iniciales</a></li>
<li class="chapter" data-level="20.2" data-path="normalidad.html"><a href="normalidad.html#histograma-y-densidad"><i class="fa fa-check"></i><b>20.2</b> Histograma y densidad</a>
<ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-densidad-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo densidad con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-densidad-del-peso-corporal"><i class="fa fa-check"></i>Ejemplo densidad del peso corporal</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="normalidad.html"><a href="normalidad.html#gráficos-cuantil-cuantil"><i class="fa fa-check"></i><b>20.3</b> Gráficos cuantil cuantil </a>
<ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-1-qqplot-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo 1 QQplot con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-2-qqplot-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo 2 QQplot con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-qqplot-para-peso-corporal"><i class="fa fa-check"></i>Ejemplo QQplot para peso corporal</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-qqplot-con-bandas"><i class="fa fa-check"></i>Ejemplo QQplot con bandas</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="normalidad.html"><a href="normalidad.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>20.4</b> Pruebas de normalidad</a>
<ul>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-con-datos-simulados"><i class="fa fa-check"></i>Ejemplo con datos simulados</a></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejemplo-normalidad-para-peso-corporal"><i class="fa fa-check"></i>Ejemplo normalidad para peso corporal</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="normalidad.html"><a href="normalidad.html#ejercicios-8"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="loglik.html"><a href="loglik.html"><i class="fa fa-check"></i><b>21</b> Verosimilitud</a>
<ul>
<li class="chapter" data-level="21.1" data-path="loglik.html"><a href="loglik.html#función-de-verosimilitud"><i class="fa fa-check"></i><b>21.1</b> Función de verosimilitud</a></li>
<li class="chapter" data-level="21.2" data-path="loglik.html"><a href="loglik.html#función-de-log-verosimilitud"><i class="fa fa-check"></i><b>21.2</b> Función de log-verosimilitud</a></li>
<li class="chapter" data-level="21.3" data-path="loglik.html"><a href="loglik.html#método-de-máxima-verosimilitud-para-estimar-parámetros"><i class="fa fa-check"></i><b>21.3</b> Método de máxima verosimilitud para estimar parámetros</a>
<ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-61"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-62"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-63"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="loglik.html"><a href="loglik.html#score-e-información-de-fisher"><i class="fa fa-check"></i><b>21.4</b> Score e Información de Fisher</a>
<ul>
<li class="chapter" data-level="21.4.1" data-path="loglik.html"><a href="loglik.html#score-e-información-de-fisher-en-el-caso-univariado."><i class="fa fa-check"></i><b>21.4.1</b> Score e Información de Fisher en el caso univariado.</a></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-64"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="loglik.html"><a href="loglik.html#método-de-máxima-verosimilitud-para-estimar-parámetros-en-modelos-de-regresión"><i class="fa fa-check"></i><b>21.5</b> Método de máxima verosimilitud para estimar parámetros en modelos de regresión</a>
<ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-65"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="loglik.html"><a href="loglik.html#paquete-maxlik"><i class="fa fa-check"></i><b>21.6</b> Paquete maxLik</a>
<ul>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejemplo-66"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="loglik.html"><a href="loglik.html#ejercicios-9"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="select_dist.html"><a href="select_dist.html"><i class="fa fa-check"></i><b>22</b> Selección de la distribución</a>
<ul>
<li class="chapter" data-level="22.1" data-path="select_dist.html"><a href="select_dist.html#función-fitdists"><i class="fa fa-check"></i><b>22.1</b> Función <code>fitDists</code></a>
<ul>
<li class="chapter" data-level="" data-path="select_dist.html"><a href="select_dist.html#ejemplo-67"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="select_dist.html"><a href="select_dist.html#qué-tipo-de-preguntas-se-podrían-responder-luego"><i class="fa fa-check"></i><b>22.2</b> ¿Qué tipo de preguntas se podrían responder luego?</a>
<ul>
<li class="chapter" data-level="" data-path="select_dist.html"><a href="select_dist.html#ejemplo-68"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="select_dist.html"><a href="select_dist.html#ejercicios-10"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="ic.html"><a href="ic.html"><i class="fa fa-check"></i><b>23</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="23.1" data-path="ic.html"><a href="ic.html#función-t.test"><i class="fa fa-check"></i><b>23.1</b> Función <code>t.test</code></a>
<ul>
<li class="chapter" data-level="23.1.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-media-mu"><i class="fa fa-check"></i><b>23.1.1</b> Intervalo de confianza bilateral para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-69"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.1.2" data-path="ic.html"><a href="ic.html#ICDifMed"><i class="fa fa-check"></i><b>23.1.2</b> Intervalo de confianza bilateral para la diferencia de medias (<span class="math inline">\(\mu_1-\mu_2\)</span>) de muestras independientes</a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-70"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.1.3" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-medias-mu_1-mu_2-de-muestras-dependientes-o-pareadas"><i class="fa fa-check"></i><b>23.1.3</b> Intervalo de confianza bilateral para la diferencia de medias (<span class="math inline">\(\mu_1-\mu_2\)</span>) de muestras dependientes o pareadas</a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-71"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.1.4" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-unilateral-para-la-media-mu"><i class="fa fa-check"></i><b>23.1.4</b> Intervalo de confianza unilateral para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-72"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="ic.html"><a href="ic.html#función-var.test"><i class="fa fa-check"></i><b>23.2</b> Función <code>var.test</code></a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-varianza-sigma2"><i class="fa fa-check"></i><b>23.2.1</b> Intervalo de confianza bilateral para la varianza <span class="math inline">\(\sigma^2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-73"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.2.2" data-path="ic.html"><a href="ic.html#ICCocVar"><i class="fa fa-check"></i><b>23.2.2</b> Intervalo de confianza bilateral para la razón de varianzas <span class="math inline">\(\sigma_1^2 / \sigma_2^2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-74"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="ic.html"><a href="ic.html#función-prop.test"><i class="fa fa-check"></i><b>23.3</b> Función <code>prop.test</code></a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-proporción-p"><i class="fa fa-check"></i><b>23.3.1</b> Intervalo de confianza bilateral para la proporción <span class="math inline">\(p\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-75"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="23.3.2" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-bilateral-para-la-diferencia-de-proporciones-p_1---p_2"><i class="fa fa-check"></i><b>23.3.2</b> Intervalo de confianza bilateral para la diferencia de proporciones <span class="math inline">\(p_1 - p_2\)</span></a></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-76"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="24" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>24</b> Prueba de hipótesis</a>
<ul>
<li class="chapter" data-level="24.1" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-mu-de-una-población-normal"><i class="fa fa-check"></i><b>24.1</b> Prueba de hipótesis para <span class="math inline">\(\mu\)</span> de una población normal</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-77"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-mu-con-muestras-grandes"><i class="fa fa-check"></i><b>24.2</b> Prueba de hipótesis para <span class="math inline">\(\mu\)</span> con muestras grandes</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-78"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-proporción-p"><i class="fa fa-check"></i><b>24.3</b> Prueba de hipótesis para la proporción <span class="math inline">\(p\)</span></a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="ph.html"><a href="ph.html#prueba-de-wald"><i class="fa fa-check"></i><b>24.3.1</b> Prueba de Wald</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-79"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="24.3.2" data-path="ph.html"><a href="ph.html#prueba-chi2-de-pearson"><i class="fa fa-check"></i><b>24.3.2</b> Prueba <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-80"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="24.3.3" data-path="ph.html"><a href="ph.html#prueba-binomial-exacta"><i class="fa fa-check"></i><b>24.3.3</b> Prueba binomial exacta</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-81"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-varianza-sigma2-de-una-población-normal"><i class="fa fa-check"></i><b>24.4</b> Prueba de hipótesis para la varianza <span class="math inline">\(\sigma^2\)</span> de una población normal</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-82"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-el-cociente-de-varianzas-sigma_12-sigma_22"><i class="fa fa-check"></i><b>24.5</b> Prueba de hipótesis para el cociente de varianzas <span class="math inline">\(\sigma_1^2 / \sigma_2^2\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-83"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-84"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.6" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-iguales"><i class="fa fa-check"></i><b>24.6</b> Prueba de hipótesis para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> con varianzas iguales</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-85"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.7" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-diferentes"><i class="fa fa-check"></i><b>24.7</b> Prueba de hipótesis para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> con varianzas diferentes</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-86"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.8" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-proporciones-p_1---p_2"><i class="fa fa-check"></i><b>24.8</b> Prueba de hipótesis para la diferencia de proporciones <span class="math inline">\(p_1 - p_2\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-87"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="24.9" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-para-la-diferencia-de-medias-pareadas"><i class="fa fa-check"></i><b>24.9</b> Prueba de hipótesis para la diferencia de medias pareadas</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-88"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="aproxint.html"><a href="aproxint.html"><i class="fa fa-check"></i><b>25</b> Aproximación de integrales</a>
<ul>
<li class="chapter" data-level="25.1" data-path="aproxint.html"><a href="aproxint.html#aproximación-de-laplace-unidimensional"><i class="fa fa-check"></i><b>25.1</b> Aproximación de Laplace unidimensional</a>
<ul>
<li class="chapter" data-level="" data-path="aproxint.html"><a href="aproxint.html#ejemplo-89"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="empiricaldists.html"><a href="empiricaldists.html"><i class="fa fa-check"></i><b>26</b> Distribuciones empíricas</a>
<ul>
<li class="chapter" data-level="26.1" data-path="empiricaldists.html"><a href="empiricaldists.html#una-variable"><i class="fa fa-check"></i><b>26.1</b> Una variable</a>
<ul>
<li class="chapter" data-level="" data-path="empiricaldists.html"><a href="empiricaldists.html#ejemplo-90"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="normalmulti.html"><a href="normalmulti.html"><i class="fa fa-check"></i><b>27</b> Distribución normal multivariada</a>
<ul>
<li class="chapter" data-level="27.1" data-path="normalmulti.html"><a href="normalmulti.html#función-de-densidad-1"><i class="fa fa-check"></i><b>27.1</b> Función de densidad</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-91"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-92"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-93"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="27.2" data-path="normalmulti.html"><a href="normalmulti.html#simulando-de-una-normal-multivariada"><i class="fa fa-check"></i><b>27.2</b> Simulando de una normal multivariada</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-94"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-95"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-96"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="normalmulti.html"><a href="normalmulti.html#calculando-probabilidades"><i class="fa fa-check"></i><b>27.3</b> Calculando probabilidades</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-97"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="normalmulti.html"><a href="normalmulti.html#distancia-de-mahalanobis"><i class="fa fa-check"></i><b>27.4</b> Distancia de Mahalanobis</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-98"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="normalmulti.html"><a href="normalmulti.html#ellipse-o-contornos-de-confianza"><i class="fa fa-check"></i><b>27.5</b> Ellipse o contornos de confianza</a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-99"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-100"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="27.6" data-path="normalmulti.html"><a href="normalmulti.html#estimando-los-parámetros-boldsymbolmu-y-boldsymbolsigma"><i class="fa fa-check"></i><b>27.6</b> Estimando los parámetros <span class="math inline">\(\boldsymbol{\mu}\)</span> y <span class="math inline">\(\boldsymbol{\Sigma}\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-101"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejemplo-102"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="27.7" data-path="normalmulti.html"><a href="normalmulti.html#distribución-wishart"><i class="fa fa-check"></i><b>27.7</b> Distribución Wishart</a></li>
<li class="chapter" data-level="27.8" data-path="normalmulti.html"><a href="normalmulti.html#mezcla-de-dos-normales-multivariadas"><i class="fa fa-check"></i><b>27.8</b> Mezcla de dos normales multivariadas</a></li>
<li class="chapter" data-level="" data-path="normalmulti.html"><a href="normalmulti.html#ejercicios-11"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="curio.html"><a href="curio.html"><i class="fa fa-check"></i><b>28</b> Curiosidades</a>
<ul>
<li class="chapter" data-level="28.1" data-path="curio.html"><a href="curio.html#cómo-verificar-si-un-paquete-no-está-instalado-para-instalarlo-de-forma-automática"><i class="fa fa-check"></i><b>28.1</b> ¿Cómo verificar si un paquete no está instalado para instalarlo de forma automática?</a>
<ul>
<li class="chapter" data-level="" data-path="curio.html"><a href="curio.html#ejemplo-103"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Manual de R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="normal" class="section level1 hasAnchor" number="19">
<h1><span class="header-section-number">19</span> Distribución normal<a href="normal.html#normal" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se mostrará en detalle la distribución normal, la distribución más importante en estadística.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:personasnormal"></span>
<img src="images/personas_en_normal.jpg" alt="Personas formando la normal con su estatura." width="100%" />
<p class="caption">
Figure 19.1: Personas formando la normal con su estatura.
</p>
</div>
<p>A continuación un video donde se explica de manera sencilla la distribución normal.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/ga9md4GPFhE?si=Ow6JmnAQfLXNuWEL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
</iframe>
<div id="función-de-densidad" class="section level2 hasAnchor" number="19.1">
<h2><span class="header-section-number">19.1</span> Función de densidad<a href="normal.html#función-de-densidad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La distribución normal, también conocida como distribución gaussiana o curva de campana, es una de las distribuciones de probabilidad más importantes en estadística. Se caracteriza por ser simétrica y tiene una forma de campana. Su función de densidad de probabilidad se define mediante la siguiente ecuación:</p>
<p><span class="math display">\[
f(x | \mu, \sigma^2) = \frac{1}{\sigma \sqrt{2\pi}} e^{-\frac{1}{2} \left(\frac{x - \mu}{\sigma}\right)^2},
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(x\)</span> es el valor de la variable aleatoria <span class="math inline">\(X\)</span>.</li>
<li><span class="math inline">\(\mu\)</span> es la media (promedio) de la distribución.</li>
<li><span class="math inline">\(\sigma\)</span> es la desviación estándar, que mide la dispersión de los datos.</li>
</ul>

<div class="rmdnote">
Si una variable aleatoria <span class="math inline">\(X\)</span> se distribuye normal con media <span class="math inline">\(\mu\)</span> y varianza <span class="math inline">\(\sigma^2\)</span>, esto se denota por <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>. El segundo elemento de la notación es la varianza, no la desviación estándar.
</div>
</div>
<div id="visualización-de-la-distribución" class="section level2 hasAnchor" number="19.2">
<h2><span class="header-section-number">19.2</span> Visualización de la distribución<a href="normal.html#visualización-de-la-distribución" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Generemos un gráfico de la función de densidad de probabilidad de la distribución normal estándar.</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="normal.html#cb628-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>), </span>
<span id="cb628-2"><a href="normal.html#cb628-2" tabindex="-1"></a>      <span class="at">from=</span><span class="sc">-</span><span class="dv">4</span>, <span class="at">to=</span><span class="dv">4</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,</span>
<span id="cb628-3"><a href="normal.html#cb628-3" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;N(0, 1)&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;X&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;f(x)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:distnorm1"></span>
<img src="Manual_de_R_files/figure-html/distnorm1-1.png" alt="Ejemplo 1 de distribución normal." width="576" />
<p class="caption">
Figure 19.2: Ejemplo 1 de distribución normal.
</p>
</div>
<p>En el gráfico anterior, la curva azul representa la distribución normal estándar. Como se puede observar, tiene una forma de campana y es simétrica en torno a la media de 0.</p>
<div class="sourceCode" id="cb629"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb629-1"><a href="normal.html#cb629-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fl">1.65</span>, <span class="at">sd=</span><span class="fl">0.15</span>), </span>
<span id="cb629-2"><a href="normal.html#cb629-2" tabindex="-1"></a>      <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">4</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">&quot;tomato&quot;</span>,</span>
<span id="cb629-3"><a href="normal.html#cb629-3" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;N(mu=1.65, sigma2=0.15^2)&quot;</span>, </span>
<span id="cb629-4"><a href="normal.html#cb629-4" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">&quot;X&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;f(x)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:distnorm2"></span>
<img src="Manual_de_R_files/figure-html/distnorm2-1.png" alt="Ejemplo 2 de distribución normal." width="576" />
<p class="caption">
Figure 19.3: Ejemplo 2 de distribución normal.
</p>
</div>
<p>Vamos a comparar el efecto de la media y la desviación.</p>
<div class="figure"><span style="display:block;" id="fig:norm3"></span>
<img src="Manual_de_R_files/figure-html/norm3-1.png" alt="Varias densidades normal." width="576" />
<p class="caption">
Figure 19.4: Varias densidades normal.
</p>
</div>
</div>
<div id="características-de-la-distribución-normal" class="section level2 hasAnchor" number="19.3">
<h2><span class="header-section-number">19.3</span> Características de la Distribución Normal<a href="normal.html#características-de-la-distribución-normal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La distribución normal tiene las siguientes características clave:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Simetría</strong>: Es simétrica alrededor de la media (<span class="math inline">\(\mu\)</span>), lo que significa que las colas izquierda y derecha de la distribución son idénticas.</p></li>
<li><p><strong>Unimodal</strong>: Tiene un solo pico en la media (<span class="math inline">\(\mu\)</span>).</p></li>
<li><p><strong>Forma de Campana</strong>: La función de densidad de probabilidad forma una curva en forma de campana.</p></li>
<li><p><strong>Regla Empírica</strong>: Aproximadamente el 68% de los datos caen dentro de una desviación estándar de la media, el 95% dentro de dos desviaciones estándar y el 99.7% dentro de tres desviaciones estándar.</p></li>
</ol>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:reglaEmpiricNormal"></span>
<img src="images/regla_empirica_normal.png" alt="Regla empírica normal." width="80%" />
<p class="caption">
Figure 19.5: Regla empírica normal.
</p>
</div>
</div>
<div id="funciones-útiles-asociadas-a-la-normal" class="section level2 hasAnchor" number="19.4">
<h2><span class="header-section-number">19.4</span> Funciones útiles asociadas a la normal<a href="normal.html#funciones-útiles-asociadas-a-la-normal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Algunas de las funciones asociadas a la normal son</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="normal.html#cb630-1" tabindex="-1"></a><span class="fu">dnorm</span>(x, mean, sd)                    <span class="co"># Calcula f(x)</span></span>
<span id="cb630-2"><a href="normal.html#cb630-2" tabindex="-1"></a><span class="fu">pnorm</span>(q, mean, sd, <span class="at">lower.tail=</span><span class="cn">TRUE</span>)   <span class="co"># Calcula P(X&lt;q)</span></span>
<span id="cb630-3"><a href="normal.html#cb630-3" tabindex="-1"></a><span class="fu">qnorm</span>(p, mean, sd, <span class="at">lower.tail=</span><span class="cn">TRUE</span>)   <span class="co"># Calcula q tal que P(X&lt;q) = p</span></span>
<span id="cb630-4"><a href="normal.html#cb630-4" tabindex="-1"></a><span class="fu">rnorm</span>(n, mean, sd)                    <span class="co"># Genera números aleatorios</span></span></code></pre></div>
</div>
<div id="cálculo-de-probabilidades" class="section level2 hasAnchor" number="19.5">
<h2><span class="header-section-number">19.5</span> Cálculo de Probabilidades<a href="normal.html#cálculo-de-probabilidades" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Calculemos algunas probabilidades utilizando la función <code>pnorm(q, mean, sd)</code>. Los casos usuales de probabilidades en distribución normal se muestran en la siguiente figura.</p>
<div class="figure"><span style="display:block;" id="fig:casesDistNormal"></span>
<img src="Manual_de_R_files/figure-html/casesDistNormal-1.png" alt="Casos de probabilidades en distribución normal." width="768" />
<p class="caption">
Figure 19.6: Casos de probabilidades en distribución normal.
</p>
</div>

<div class="rmdwarning">
Recuerde que <code>pnorm()</code> entrega la probabilidad de cola a izquierda.
</div>
<div id="ejemplo-53" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-53" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que <span class="math inline">\(Z \sim N(0, 1)\)</span>. Calcular <span class="math inline">\(P(Z &lt; 1.5)\)</span>.</p>
<p><em>Solución</em></p>
<p>Para calcular esta probabilidad utilizamos el siguiente código:</p>
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb631-1"><a href="normal.html#cb631-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q=</span><span class="fl">1.5</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.9331928</code></pre>
<p>La probabilidad de que <span class="math inline">\(Z\)</span> sea menor que 1.5 en la distribución normal estándar es aproximadamente 93.32%.</p>
</div>
<div id="ejemplo-54" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-54" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que <span class="math inline">\(Y \sim N(5, 9)\)</span>. Calcular <span class="math inline">\(P(Y &gt; 5.3)\)</span>.</p>
<p><em>Solución</em></p>
<p>Para obtener la probabilidad lo podemos hacer de dos formas.</p>
<p><strong>Forma 1</strong></p>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb633-1"><a href="normal.html#cb633-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="fl">5.3</span>, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.4601722</code></pre>
<p><strong>Forma 2</strong></p>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb635-1"><a href="normal.html#cb635-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q=</span><span class="fl">5.3</span>, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">3</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.4601722</code></pre>
<p>La probabilidad de que <span class="math inline">\(Y\)</span> sea mayor que 5.3 es aproximadamente 46.01%.</p>
</div>
<div id="ejemplo-55" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-55" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que <span class="math inline">\(W \sim N(150, 25)\)</span>. Calcular <span class="math inline">\(P(140 &lt; W &lt; 156)\)</span>.</p>
<p><em>Solución</em></p>
<p>Para calcular esta probabilidad utilizamos el siguiente código:</p>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="normal.html#cb637-1" tabindex="-1"></a>p_156 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">156</span>, <span class="at">mean=</span><span class="dv">150</span>, <span class="at">sd=</span><span class="dv">5</span>)</span>
<span id="cb637-2"><a href="normal.html#cb637-2" tabindex="-1"></a>p_140 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">140</span>, <span class="at">mean=</span><span class="dv">150</span>, <span class="at">sd=</span><span class="dv">5</span>)</span>
<span id="cb637-3"><a href="normal.html#cb637-3" tabindex="-1"></a>p_156 <span class="sc">-</span> p_140</span></code></pre></div>
<pre><code>## [1] 0.8621802</code></pre>
<p>La probabilidad de que <span class="math inline">\(P(140 &lt; W &lt; 156)\)</span> es aproximadamente 86.21%.</p>
</div>
<div id="ejemplo-56" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-56" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que <span class="math inline">\(Q \sim N(16, 16)\)</span>. Calcular <span class="math inline">\(P(Q &lt; 14 \, \text{ó} \, Q &gt; 18)\)</span>.</p>
<p><em>Solución</em></p>
<p>Para calcular esta probabilidad utilizamos el siguiente código:</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="normal.html#cb639-1" tabindex="-1"></a>cola_izq_de_14 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">14</span>, <span class="at">mean=</span><span class="dv">16</span>, <span class="at">sd=</span><span class="dv">4</span>)</span>
<span id="cb639-2"><a href="normal.html#cb639-2" tabindex="-1"></a>cola_der_de_18 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">18</span>, <span class="at">mean=</span><span class="dv">16</span>, <span class="at">sd=</span><span class="dv">4</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb639-3"><a href="normal.html#cb639-3" tabindex="-1"></a>rta <span class="ot">&lt;-</span> cola_izq_de_14 <span class="sc">+</span> cola_der_de_18</span>
<span id="cb639-4"><a href="normal.html#cb639-4" tabindex="-1"></a>rta</span></code></pre></div>
<pre><code>## [1] 0.6170751</code></pre>
<p>La probabilidad de que <span class="math inline">\(P(Q &lt; 14 \, \text{ó} \, Q &gt; 18)\)</span> es aproximadamente 61.71%.</p>
</div>
<div id="ejemplo-57" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-57" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una empresa tiene 1700 empleados y los sueldos mensuales de los empleados siguen una distribución normal con media de 4.5 millones de pesos, con una desviación estándar de 1.2 millones de pesos. ¿Cuál es el número esperado de trabajadores que reciben sueldos entre 3 y 5 millones de pesos?</p>
<p><em>Solución</em></p>
<p>Para calcular esta probabilidad utilizamos el siguiente código:</p>
<div class="sourceCode" id="cb641"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb641-1"><a href="normal.html#cb641-1" tabindex="-1"></a>p_3 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">3</span>, <span class="at">mean=</span><span class="fl">4.5</span>, <span class="at">sd=</span><span class="fl">1.2</span>)</span>
<span id="cb641-2"><a href="normal.html#cb641-2" tabindex="-1"></a>p_5 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">5</span>, <span class="at">mean=</span><span class="fl">4.5</span>, <span class="at">sd=</span><span class="fl">1.2</span>)</span>
<span id="cb641-3"><a href="normal.html#cb641-3" tabindex="-1"></a><span class="dv">1700</span> <span class="sc">*</span> (p_5 <span class="sc">-</span> p_3)</span></code></pre></div>
<pre><code>## [1] 945.0115</code></pre>
<p>Primero se calcula la probabilidad de que <span class="math inline">\(P(3 &lt; S &lt; 5)\)</span> y luego se multiplica por el número de empleados, eso nos da que aproximadamente 945 empleados reciben sueldos entre 3 y 5 millones de pesos.</p>
</div>
</div>
<div id="cálculo-de-cuantiles" class="section level2 hasAnchor" number="19.6">
<h2><span class="header-section-number">19.6</span> Cálculo de cuantiles<a href="normal.html#cálculo-de-cuantiles" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Calcular un cuantil significa que estamos interesados en averiguar el valor de la variable aleatoria <span class="math inline">\(X\)</span> tal que <span class="math inline">\(P(X&lt;q) = p\)</span>, en otras palabras, aquí sabemos que la probabilidad vale <span class="math inline">\(p\)</span> y nosotros debemos obtener el valor de <span class="math inline">\(q\)</span> que la probabilidad a la izquierda sea ese valor <span class="math inline">\(p\)</span>. En la siguiente figura se muestra una ilustración del problema.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:quantileProblem"></span>
<img src="images/quantile_problem.png" alt="Calculando un cuantil." width="80%" />
<p class="caption">
Figure 19.7: Calculando un cuantil.
</p>
</div>
<div id="ejemplo-58" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-58" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>(Ejercicio propuesto 14) La duración de un determinado tipo de lavadora automática tiene una distribución normal con una media de 3.1 años y una desviación estándar de 1.2 años. El fabricante quiere ofrecer un cambio de lavadora al 15% de las lavadoras que duren menos. ¿Cuál es el tiempo de duración máximo que debería poner en la publicidad para reponer solo el 15% de las lavadoras.</p>
<p><em>Solución</em></p>
<p>Gráficamente el problema se puede resumir de la siguiente manera.</p>
<div class="sourceCode" id="cb643"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb643-1"><a href="normal.html#cb643-1" tabindex="-1"></a><span class="fu">shadow.dist</span>(<span class="at">dist=</span><span class="st">&#39;dnorm&#39;</span>, <span class="at">param=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="fl">3.1</span>, <span class="at">sd=</span><span class="fl">1.2</span>),</span>
<span id="cb643-2"><a href="normal.html#cb643-2" tabindex="-1"></a>            <span class="at">a=</span><span class="fu">qnorm</span>(<span class="at">p=</span><span class="fl">0.15</span>, <span class="at">mean=</span><span class="fl">3.1</span>, <span class="at">sd=</span><span class="fl">1.2</span>), <span class="at">type=</span><span class="st">&#39;lower&#39;</span>, <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">6</span>,</span>
<span id="cb643-3"><a href="normal.html#cb643-3" tabindex="-1"></a>            <span class="at">main=</span><span class="st">&#39;&#39;</span>, <span class="at">las=</span><span class="dv">1</span>,</span>
<span id="cb643-4"><a href="normal.html#cb643-4" tabindex="-1"></a>            <span class="at">col.shadow=</span><span class="st">&#39;springgreen3&#39;</span>, <span class="at">xlab=</span><span class="st">&#39;X&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Densidad&#39;</span>)</span>
<span id="cb643-5"><a href="normal.html#cb643-5" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">1.3</span>, <span class="at">y=</span><span class="fl">0.05</span>, <span class="st">&quot;0.15&quot;</span>, <span class="at">col=</span><span class="st">&quot;yellow1&quot;</span>, <span class="at">cex=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Manual_de_R_files/figure-html/cuantilNormal1-1.png" width="672" /></p>
<p>Para calcular el valor solicitado usamos el siguiente código:</p>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="normal.html#cb644-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p=</span><span class="fl">0.15</span>, <span class="at">mean=</span><span class="fl">3.1</span>, <span class="at">sd=</span><span class="fl">1.2</span>)</span></code></pre></div>
<pre><code>## [1] 1.85628</code></pre>
<p>Del resultado anterior podemos afirmar que el anuncio publicitario debería decir algo como “Si su lavadora dura 1.85 años o menos, nosotros se la reemplazaremos por una nueva lavadora”. De esa manera el fabricante sólo debería tener un 15% de reclamaciones.</p>
</div>
</div>
<div id="ejemplo-de-generación-de-datos" class="section level2 hasAnchor" number="19.7">
<h2><span class="header-section-number">19.7</span> Ejemplo de generación de datos<a href="normal.html#ejemplo-de-generación-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La función <code>rnorm()</code> es muy utilizada para simular datos de una población normal. Con los datos simulados se pueden poner a prueba procedimientos estadísticos o realizar simulaciones de sistemas reales.</p>
<div id="ejemplo-59" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-59" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Generar <span class="math inline">\(n=350\)</span> observaciones de una <span class="math inline">\(N(150, 25)\)</span>. Con los datos simulados construya un histograma y sobre el histograma superponga la curva de densidad de una <span class="math inline">\(N(150, 25)\)</span>. Comente los resultados gráficos.</p>
<p><em>Solución</em></p>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="normal.html#cb646-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)  <span class="co"># Funcion para fijar la semilla y poder replicar la simulacion</span></span>
<span id="cb646-2"><a href="normal.html#cb646-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">350</span>, <span class="at">mean=</span><span class="dv">150</span>, <span class="at">sd=</span><span class="dv">5</span>)</span></code></pre></div>
<p>Vamos a explorar los primeros diez valores que están dentro del vector <code>x</code>.</p>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="normal.html#cb647-1" tabindex="-1"></a>x[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] 152.9276 153.5473 149.4535 147.7325 153.0294 140.9102 153.1505 148.6191
##  [9] 148.5792 145.4034</code></pre>
<p>Usando el vector <code>x</code> vamos ahora a dibujar el histograma y la densidad.</p>
<div class="sourceCode" id="cb649"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb649-1"><a href="normal.html#cb649-1" tabindex="-1"></a><span class="fu">hist</span>(x, <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">border=</span><span class="st">&quot;black&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.10</span>),</span>
<span id="cb649-2"><a href="normal.html#cb649-2" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Histograma y densidad&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;X&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;f(x)&quot;</span>)</span>
<span id="cb649-3"><a href="normal.html#cb649-3" tabindex="-1"></a></span>
<span id="cb649-4"><a href="normal.html#cb649-4" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="dv">150</span>, <span class="at">sd=</span><span class="dv">5</span>), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">&quot;tomato&quot;</span>, <span class="at">add=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="Manual_de_R_files/figure-html/histNormalAleat-1.png" width="672" /></p>
<p>En el histograma tiene una forma de campana y es parecido a la densidad teórica de color rojo. Entre más valores se simulen, mejor se verá el histograma y se parecerá cada vez más a la densidad teórica.</p>
</div>
</div>
<div id="estimación-de-los-parámetros-mu-y-sigma" class="section level2 hasAnchor" number="19.8">
<h2><span class="header-section-number">19.8</span> Estimación de los parámetros <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span><a href="normal.html#estimación-de-los-parámetros-mu-y-sigma" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En el paquete <strong>MASS</strong> de R hay una función llamada <code>fitdistr()</code> que sirve para estimar los parámetros de varias distribuciones, entre ellas la distribución normal. La estructura de la función es la siguiente:</p>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="normal.html#cb650-1" tabindex="-1"></a><span class="fu">fitdistr</span>(x, densfun)</span></code></pre></div>
<p>Los parámetros de la función son:</p>
<ul>
<li><code>x</code>: vector con los datos.</li>
<li><code>densfun</code>: nombre de la distribución que se asume para los datos. Los posibles valores son “beta”, “cauchy”, “chi-squared”, “exponential”, “gamma”, “geometric”, “log-normal”, “lognormal”, “logistic”, “negative binomial”, “normal”, “Poisson”, “t” y “weibull”.</li>
</ul>
<div id="ejemplo-60" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="normal.html#ejemplo-60" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que vamos a simular observaciones una <span class="math inline">\(N(150, 81)\)</span>.
a) Genere <span class="math inline">\(n=15\)</span> observaciones y con los datos simulados estime <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>.
b) Genere <span class="math inline">\(n=1500\)</span> observaciones y con los datos simulados estime <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>.
c) Compare los resultados y concluya.</p>
<p><em>Solución</em></p>
<p>Vamos a simular la primera muestra.</p>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="normal.html#cb651-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Adjuntando el paquete: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="normal.html#cb654-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb654-2"><a href="normal.html#cb654-2" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">15</span>, <span class="at">mean=</span><span class="dv">150</span>, <span class="at">s=</span><span class="dv">9</span>)</span>
<span id="cb654-3"><a href="normal.html#cb654-3" tabindex="-1"></a><span class="fu">fitdistr</span>(<span class="at">x=</span>x1, <span class="at">densfun=</span><span class="st">&quot;normal&quot;</span>)</span></code></pre></div>
<pre><code>##       mean          sd    
##   151.371459     7.350079 
##  (  1.897782) (  1.341935)</code></pre>
<p>De la salida anterior tenemos que <span class="math inline">\(\hat{\mu}=151.37\)</span> y <span class="math inline">\(\hat{\sigma}=7.35\)</span>.</p>

<div class="rmdnote">
Los valores entre paréntesis que salen al usar <code>fitdistr</code> se llaman “errores estándar”, son la variabilidad que tiene la estimación.
</div>
<p>Vamos a simular la segunda muestra.</p>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb656-1"><a href="normal.html#cb656-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb656-2"><a href="normal.html#cb656-2" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">1500</span>, <span class="at">mean=</span><span class="dv">150</span>, <span class="at">sd=</span><span class="dv">9</span>)</span>
<span id="cb656-3"><a href="normal.html#cb656-3" tabindex="-1"></a><span class="fu">fitdistr</span>(<span class="at">x=</span>x2, <span class="at">densfun=</span><span class="st">&quot;normal&quot;</span>)</span></code></pre></div>
<pre><code>##       mean           sd     
##   149.9354547     8.7982331 
##  (  0.2271694) (  0.1606330)</code></pre>
<p>De la salida anterior tenemos que <span class="math inline">\(\hat{\mu}=149.94\)</span> y <span class="math inline">\(\hat{\sigma}=8.80\)</span>.</p>
<p>Al comparar las estimaciones vemos que <span class="math inline">\(\hat{\mu}\)</span> y <span class="math inline">\(\hat{\sigma}\)</span> son más cercanos a los verdaderos valores cuando <span class="math inline">\(n=1500\)</span>. Esto significa que al tener un tamaño muestral mayor, las estimaciones son mejores.</p>
<p>Otra cosa interesante es que los errores estándar disminuyen al aumentar el tamaño de la muestra. Esto es coherente, al tener mayor información, mejor es la estimación.</p>
</div>
</div>
<div id="ejercicios-7" class="section level2 hasAnchor" number="19.9">
<h2><span class="header-section-number">19.9</span> Ejercicios<a href="normal.html#ejercicios-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>¿Cuáles de los siguientes enunciados son verdaderos?</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>La distribución normal es asimétrica.</li>
<li>Es necesario conocer la media y la desviación estándar para construir una distribución normal específica.</li>
<li>Cada combinación de media y desviación estándar en una distribución normal define una densidad diferente.</li>
<li>La distribución normal se extiende al infinito en cualquier dirección a partir de la media.</li>
<li>La distribución normal se mide en una escala discreta.</li>
<li>El área total bajo la curva es igual a 1.</li>
<li>La probabilidad de que una variable aleatoria tenga un valor entre dos puntos cualesquiera es igual al área bajo la curva entre esos dos puntos.</li>
<li>La distribución normal estándar tiene media 1 y varianza 0.</li>
<li>La tabla de distribución normal estándar sirve para calcular probabilidades de cualquier distribución normal.</li>
<li>Estandarizar un valor x significa restarle la desviación y dividir por la media.</li>
<li>La probabilidad de que una variable aleatoria continua tome un valor dado es cero.</li>
<li>La función de densidad de probabilidad (fdp) de una variable aleatoria continua sirve para conocer en qué región es más probable encontrar valores de la variable.</li>
</ol>
<p>Rtas: F, V, V, V, F, V, V, F, V, F, V, V.</p>
<ol start="2" style="list-style-type: decimal">
<li>Si Z es una variable aleatoria normal estandarizada,</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>¿Cuál es el rango de la variable aleatoria Z?</li>
<li>¿Cuál es la probabilidad de tomar un valor menor que cero?</li>
<li>¿Cuál es la probabilidad de que Z tome un valor entre -3 y +3?</li>
<li>¿Cuál es la probabilidad de obtener un valor en el rango media más menos dos desviaciones estándar?</li>
<li>¿Cuál es la probabilidad de que Z tome un valor comprendido entre -1.28 y +1.65?</li>
</ol>
<p>Rtas: reales, ½, 0.9973, 0.9544, 0.8502</p>
<ol start="3" style="list-style-type: decimal">
<li>Determinar las siguientes probabilidades para la variable aleatoria normal estándar (Dibuje una curva normal y sombree el área bajo la curva):</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>P (Z &lt; 1.32).</li>
<li>P (-2.34 &lt; Z &lt; 1.76).</li>
<li>P (Z &lt; 3).</li>
<li>P (0 &lt; Z &lt; 1).</li>
<li>P (Z &gt; 1.457).</li>
<li>P (-3 &lt; Z &lt; 3).</li>
<li>P (Z &gt; -2.153).</li>
</ol>
<p>Rtas: 0.9066, 0.9511, 0.9986, 0.3413, 0.0726, 0. 9973, 0.9843</p>
<ol start="4" style="list-style-type: decimal">
<li>Suponga que Z tiene una distribución normal estándar. Determine el valor de z que resuelve las siguientes probabilidades (Dibuje una curva normal, sombree el área bajo la curva y ponga los valores correspondientes en el eje horizontal):</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>P (-z &lt; Z &lt; z) = 0.95.</li>
<li>P (Z &lt; z) = 0.9.</li>
<li>P (-z &lt; Z &lt; z) = 0.99.</li>
<li>P (Z &lt; z) = 0.5.</li>
<li>P (-z &lt; Z &lt; z) = 0.684.</li>
<li>P(Z &gt; z) = 0.1.</li>
<li>P (-z &lt; Z &lt; z) = 0.9973.</li>
<li>P (-1.24 &lt; Z &lt; z) = 0.8.</li>
</ol>
<p>Rtas: 1.96, 1.28, 2.58, 0, -1, la misma del literal b, 3,</p>
<ol start="5" style="list-style-type: decimal">
<li>Averigüe el valor z que corresponde a cada área descrita:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>El 70% de los elementos está a la derecha de este valor z.</li>
<li>El 20% de los elementos se encuentra a la izquierda de este valor z.</li>
<li>El 10% de los elementos es mayor que este valor z.</li>
<li>El 60% de los elementos es menor que este valor z.</li>
<li>El 50% de los elementos se encuentran a la derecha de este valor z.</li>
<li>El 30% de los elementos se encuentran a la izquierda de este valor z.</li>
</ol>
<p>Rtas) <code>qnorm(p=0.7, lower.tail=F)</code>; <code>qnorm(p=0.2)</code>, <code>qnorm(p=0.1, lower.tail=F)</code>; <code>qnorm(p=0.6, lower.tail=T)</code>; <code>qnorm(p=0.5)</code>, <code>qnorm(p=0.3)</code>.</p>
<ol start="6" style="list-style-type: decimal">
<li>La duración de un determinado tipo de lavadora automática tiene una distribución normal, con una media de 3.1 años y una desviación estándar de 1.2 años. La compañía ofrece en su garantía que si la lavadora presenta algún defecto será reemplazada.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Describa gráficamente esta distribución en particular.</li>
<li>Si la lavadora está garantizada por un año, ¿qué proporción del total de unidades vendidas tendrá que ser reemplazada?</li>
<li>Si el fabricante de las lavadoras está dispuesto a reemplazar sólo el 3% de las lavadoras que vende. ¿Por cuántos meses debe ofrecer la garantía para asegurar que no más de un 3% de las lavadoras tendrá que ser reemplazada?</li>
<li>¿Qué porcentaje de las lavadoras vendidas van a durar entre 3 y 6 años?</li>
</ol>
<p>Rtas) <code>curve(dnorm(x,mean=3.1,sd=1.2), xlim=c(0,6))</code>; <code>pnorm(q=1, mean=3.1, sd=1.2)</code>; <code>qnorm(p=0.03, mean=3.1, sd=1.2)</code>; <code>pnorm(q=6, mean=3.1, sd=1.2) - pnorm(q=3, mean=3.1, sd=1.2)</code>.</p>
<ol start="7" style="list-style-type: decimal">
<li>El consumo promedio de combustible de una flota de 1000 camiones sigue una distribución normal con una media de 12 millas por galón y una desviación estándar de 2 millas por galón. Escriba las instrucciones en R para calcular cada una de las siguientes probabilidades.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>¿Cuántos camiones tendrán un promedio de 11 millas o más por galón?</li>
<li>¿Cuántos camiones tendrán un promedio de menos de 10 millas por galón?</li>
<li>¿Cuántos camiones tendrán un promedio entre 9.5 y 14 millas por galón?</li>
<li>Averigüe la probabilidad de que un camión elegido al azar tenga un promedio de 13.5 millas por galón o más.</li>
<li>¿El 70% de los camiones tuvo un promedio más alto que cuántas millas por galón?</li>
<li>¿El 10% de los camiones tuvo un promedio menor que cuántas millas por galón?</li>
</ol>
<p>Rtas)
<code>1000*pnorm(q=11, mean=12, sd=2, lower.tail=F)</code>;
<code>1000*pnorm(q=10, mean=12, sd=2)</code>;
<code>1000*(pnorm(q=14, mean=12, sd=2)-pnorm(q=9.5, mean=12, sd=2))</code>;
<code>1-pnorm(q=13.5, mean=12, sd=2)</code>;
<code>qnorm(p=0.3, mean=12, sd=2)</code>;
<code>qnorm(p=0.1, mean=12, sd=2)</code>;</p>
<ol start="8" style="list-style-type: decimal">
<li><p>Para medir los conocimientos sobre cierta materia en una misma población, se utilizan dos tipos de pruebas, A y B. Los resultados en ambas tienen distribución normal y la media de los resultados en la prueba A es 78.3 con una desviación estándar de 4.2 puntos. La media de las puntuaciones en la prueba B es 58.1 y su desviación estándar de 3.2 puntos. Una persona ha obtenido 83.1 puntos en la prueba A y otra persona ha conseguido 67.5 en la prueba B. ¿Cuál de las dos personas se encuentra en mejor posición? ¿Por qué? Rta: La persona que presentó B se encuentra en mejor posición.</p></li>
<li><p>Una empresa ha encontrado que la duración de sus llamadas telefónicas a larga distancia tiene aproximadamente una distribución normal, con media de 30 minutos y desviación típica de 3 minutos. Escriba el código en R para calcular lo siguiente.</p></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>¿Qué proporción de las llamadas a larga distancia tienen una duración de más de 20 minutos, pero de menos de 30 y medio minutos?</li>
<li>¿Qué proporción de llamadas se completan en 10 minutos o menos?</li>
<li>Una secretaria va a hacer una llamada a larga distancia. ¿Cuál es la probabilidad de que dure más de 50 minutos?</li>
</ol>
<p>Rtas)
<code>pnorm(q=30, mean=30, sd=3)- pnorm(q=20, mean=3, sd=3)</code>;
<code>pnorm(q=10, mean=30, sd=3)</code>;
<code>pnorm(q=50, mean=30, sd=3, lower.tail=F)</code>.</p>
<ol start="10" style="list-style-type: decimal">
<li>El gerente de personal de una gran compañía requiere que los postulantes a un puesto efectúen una prueba de aptitud y que en ella obtengan una calificación mínima de 500. Si las calificaciones de la prueba se distribuyen normalmente con una media de 485 y desviación estándar de 30:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>¿Qué porcentaje de postulantes aprobará la prueba?</li>
<li>Si aquellos postulantes que obtienen un puntaje comprendido entre 471 y 499 pueden optar a una segunda oportunidad, y un total de 1200 postulantes rindió la primera prueba, ¿cuántos de los 1200 postulantes tendrán derecho a rendir la prueba por segunda vez?</li>
<li>Si el puntaje de la segunda prueba se relaciona con el puntaje de la primera prueba a través de la expresión: Y=1.25 X + 2.5, donde Y es el puntaje en la segunda prueba y X es el puntaje obtenido en la primera prueba, determine la probabilidad de que en la segunda prueba un postulante cualquiera elegido al azar obtenga el puntaje aprobatorio de 500 puntos o más.</li>
<li>Determine un puntaje “k” correspondiente al percentil 90 de la distribución. Interprete.</li>
</ol>
<ol start="11" style="list-style-type: decimal">
<li>Se regula una máquina despachadora de refresco para que sirva un promedio de 200 mililitros por vaso. Si la cantidad de bebida se distribuye normalmente con una varianza igual a 225 mililitros2,</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>¿cuál es la probabilidad de que un vaso contenga entre 191 y 209 mililitros?</li>
<li>¿cuántos vasos probablemente se derramarán si se utilizan vasos de 230 mililitros para las siguientes 800 bebidas?</li>
</ol>
<p>Rtas: 0.4514; aproximadamente 18 vasos.</p>
<ol start="12" style="list-style-type: decimal">
<li>Los salarios de los profesionales en cierto departamento son en promedio 11.9$ por hora y la desviación estándar de 0.4$. Si los salarios tienen una distribución normal. ¿Cuál es la probabilidad de que un profesional seleccionado al azar:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Reciba salarios entre 10.9 y 11.9.</li>
<li>Reciba salarios inferiores a 11.</li>
<li>Reciba salarios superiores a 12.95.</li>
<li>¿Cuál debe ser el salario menor que gana un trabajador que se encuentra entre el 10% de los trabajadores que más ganan?</li>
<li>Si el dueño de la industria va a aumentarle el salario al 15% de los trabajadores que menos ganan. ¿Cuál será el salario máximo que deberá ganar un trabajador para ser beneficiado con el aumento?</li>
</ol>
<p>Rtas: 0.4938; 0.0122; 0.0043; 12.412$; 11.484$.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="continuas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="normalidad.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/Manual-de-R/edit/master/23_Normal.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Manual_de_R.pdf", "Manual_de_R.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
